//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/testing/mockito/build_result/java/org/mockito/stubbing/Answer3.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoStubbingAnswer3")
#ifdef RESTRICT_OrgMockitoStubbingAnswer3
#define INCLUDE_ALL_OrgMockitoStubbingAnswer3 0
#else
#define INCLUDE_ALL_OrgMockitoStubbingAnswer3 1
#endif
#undef RESTRICT_OrgMockitoStubbingAnswer3

#if !defined (OrgMockitoStubbingAnswer3_) && (INCLUDE_ALL_OrgMockitoStubbingAnswer3 || defined(INCLUDE_OrgMockitoStubbingAnswer3))
#define OrgMockitoStubbingAnswer3_

@protocol OrgMockitoStubbingAnswer3 < JavaObject >

- (id)answerWithId:(id)argument0
            withId:(id)argument1
            withId:(id)argument2;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoStubbingAnswer3)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoStubbingAnswer3)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoStubbingAnswer3")
