//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/testing/mockito/build_result/java/org/mockito/stubbing/Stubber.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoStubbingStubber")
#ifdef RESTRICT_OrgMockitoStubbingStubber
#define INCLUDE_ALL_OrgMockitoStubbingStubber 0
#else
#define INCLUDE_ALL_OrgMockitoStubbingStubber 1
#endif
#undef RESTRICT_OrgMockitoStubbingStubber

#if !defined (OrgMockitoStubbingStubber_) && (INCLUDE_ALL_OrgMockitoStubbingStubber || defined(INCLUDE_OrgMockitoStubbingStubber))
#define OrgMockitoStubbingStubber_

#define RESTRICT_OrgMockitoStubbingBaseStubber 1
#define INCLUDE_OrgMockitoStubbingBaseStubber 1
#include "org/mockito/stubbing/BaseStubber.h"

@protocol OrgMockitoStubbingStubber < OrgMockitoStubbingBaseStubber, JavaObject >

- (id)whenWithId:(id)mock;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoStubbingStubber)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoStubbingStubber)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoStubbingStubber")
