//
// Xalan.h
//

#include <org/apache/xpath/Arg.h>
#include <org/apache/xpath/res/XPATHErrorResources.h>
#include <org/apache/xpath/res/XPATHMessages.h>
#include <org/apache/xpath/WhitespaceStrippingElementMatcher.h>
#include <org/apache/xpath/VariableStack.h>
#include <org/apache/xpath/XPath.h>
#include <org/apache/xpath/patterns/StepPattern.h>
#include <org/apache/xpath/patterns/ContextMatchStepPattern.h>
#include <org/apache/xpath/patterns/NodeTest.h>
#include <org/apache/xpath/patterns/NodeTestFilter.h>
#include <org/apache/xpath/patterns/FunctionPattern.h>
#include <org/apache/xpath/patterns/UnionPattern.h>
#include <org/apache/xpath/axes/IteratorPool.h>
#include <org/apache/xpath/axes/UnionChildIterator.h>
#include <org/apache/xpath/axes/DescendantIterator.h>
#include <org/apache/xpath/axes/PredicatedNodeTest.h>
#include <org/apache/xpath/axes/WalkerFactory.h>
#include <org/apache/xpath/axes/ReverseAxesWalker.h>
#include <org/apache/xpath/axes/PathComponent.h>
#include <org/apache/xpath/axes/MatchPatternIterator.h>
#include <org/apache/xpath/axes/HasPositionalPredChecker.h>
#include <org/apache/xpath/axes/UnionPathIterator.h>
#include <org/apache/xpath/axes/FilterExprIterator.h>
#include <org/apache/xpath/axes/WalkingIterator.h>
#include <org/apache/xpath/axes/LocPathIterator.h>
#include <org/apache/xpath/axes/BasicTestIterator.h>
#include <org/apache/xpath/axes/FilterExprWalker.h>
#include <org/apache/xpath/axes/AxesWalker.h>
#include <org/apache/xpath/axes/ContextNodeList.h>
#include <org/apache/xpath/axes/RTFIterator.h>
#include <org/apache/xpath/axes/ChildTestIterator.h>
#include <org/apache/xpath/axes/OneStepIteratorForward.h>
#include <org/apache/xpath/axes/OneStepIterator.h>
#include <org/apache/xpath/axes/ChildIterator.h>
#include <org/apache/xpath/axes/FilterExprIteratorSimple.h>
#include <org/apache/xpath/axes/SelfIteratorNoPredicate.h>
#include <org/apache/xpath/axes/WalkingIteratorSorted.h>
#include <org/apache/xpath/axes/NodeSequence.h>
#include <org/apache/xpath/axes/SubContextList.h>
#include <org/apache/xpath/axes/AttributeIterator.h>
#include <org/apache/xpath/XPathAPI.h>
#include <org/apache/xpath/XPathProcessorException.h>
#include <org/apache/xpath/objects/XRTreeFragSelectWrapper.h>
#include <org/apache/xpath/objects/XStringForFSB.h>
#include <org/apache/xpath/objects/XRTreeFrag.h>
#include <org/apache/xpath/objects/XBooleanStatic.h>
#include <org/apache/xpath/objects/XString.h>
#include <org/apache/xpath/objects/XObject.h>
#include <org/apache/xpath/objects/XNull.h>
#include <org/apache/xpath/objects/XNodeSet.h>
#include <org/apache/xpath/objects/XNumber.h>
#include <org/apache/xpath/objects/XMLStringFactoryImpl.h>
#include <org/apache/xpath/objects/DTMXRTreeFrag.h>
#include <org/apache/xpath/objects/XStringForChars.h>
#include <org/apache/xpath/objects/XNodeSetForDOM.h>
#include <org/apache/xpath/objects/XObjectFactory.h>
#include <org/apache/xpath/objects/XBoolean.h>
#include <org/apache/xpath/SourceTreeManager.h>
#include <org/apache/xpath/ExtensionsProvider.h>
#include <org/apache/xpath/Expression.h>
#include <org/apache/xpath/operations/UnaryOperation.h>
#include <org/apache/xpath/operations/Mult.h>
#include <org/apache/xpath/operations/Neg.h>
#include <org/apache/xpath/operations/Operation.h>
#include <org/apache/xpath/operations/Lte.h>
#include <org/apache/xpath/operations/VariableSafeAbsRef.h>
#include <org/apache/xpath/operations/Gt.h>
#include <org/apache/xpath/operations/Div.h>
#include <org/apache/xpath/operations/String.h>
#include <org/apache/xpath/operations/Variable.h>
#include <org/apache/xpath/operations/Number.h>
#include <org/apache/xpath/operations/Quo.h>
#include <org/apache/xpath/operations/And.h>
#include <org/apache/xpath/operations/Gte.h>
#include <org/apache/xpath/operations/Equals.h>
#include <org/apache/xpath/operations/Minus.h>
#include <org/apache/xpath/operations/Mod.h>
#include <org/apache/xpath/operations/Bool.h>
#include <org/apache/xpath/operations/NotEquals.h>
#include <org/apache/xpath/operations/Plus.h>
#include <org/apache/xpath/operations/Lt.h>
#include <org/apache/xpath/operations/Or.h>
#include <org/apache/xpath/NodeSet.h>
#include <org/apache/xpath/FoundIndex.h>
#include <org/apache/xpath/XPathFactory.h>
#include <org/apache/xpath/jaxp/JAXPPrefixResolver.h>
#include <org/apache/xpath/jaxp/JAXPExtensionsProvider.h>
#include <org/apache/xpath/jaxp/XPathImpl.h>
#include <org/apache/xpath/jaxp/JAXPVariableStack.h>
#include <org/apache/xpath/jaxp/XPathExpressionImpl.h>
#include <org/apache/xpath/jaxp/XPathFactoryImpl.h>
#include <org/apache/xpath/NodeSetDTM.h>
#include <org/apache/xpath/CachedXPathAPI.h>
#include <org/apache/xpath/XPathVisitor.h>
#include <org/apache/xpath/XPathContext.h>
#include <org/apache/xpath/functions/FuncConcat.h>
#include <org/apache/xpath/functions/FuncTranslate.h>
#include <org/apache/xpath/functions/FuncSubstring.h>
#include <org/apache/xpath/functions/FuncRound.h>
#include <org/apache/xpath/functions/FuncSubstringBefore.h>
#include <org/apache/xpath/functions/FuncSum.h>
#include <org/apache/xpath/functions/FuncSystemProperty.h>
#include <org/apache/xpath/functions/FuncNormalizeSpace.h>
#include <org/apache/xpath/functions/FuncFalse.h>
#include <org/apache/xpath/functions/FuncContains.h>
#include <org/apache/xpath/functions/WrongNumberArgsException.h>
#include <org/apache/xpath/functions/FuncCount.h>
#include <org/apache/xpath/functions/FuncGenerateId.h>
#include <org/apache/xpath/functions/FuncCurrent.h>
#include <org/apache/xpath/functions/FuncExtFunction.h>
#include <org/apache/xpath/functions/FunctionMultiArgs.h>
#include <org/apache/xpath/functions/FuncStringLength.h>
#include <org/apache/xpath/functions/FuncNumber.h>
#include <org/apache/xpath/functions/FuncTrue.h>
#include <org/apache/xpath/functions/FuncCeiling.h>
#include <org/apache/xpath/functions/Function3Args.h>
#include <org/apache/xpath/functions/Function2Args.h>
#include <org/apache/xpath/functions/FuncDoclocation.h>
#include <org/apache/xpath/functions/FuncLocalPart.h>
#include <org/apache/xpath/functions/FuncExtElementAvailable.h>
#include <org/apache/xpath/functions/FuncString.h>
#include <org/apache/xpath/functions/FuncNamespace.h>
#include <org/apache/xpath/functions/FuncNot.h>
#include <org/apache/xpath/functions/FuncLang.h>
#include <org/apache/xpath/functions/FuncId.h>
#include <org/apache/xpath/functions/FuncLast.h>
#include <org/apache/xpath/functions/FuncPosition.h>
#include <org/apache/xpath/functions/FunctionOneArg.h>
#include <org/apache/xpath/functions/FuncStartsWith.h>
#include <org/apache/xpath/functions/FuncBoolean.h>
#include <org/apache/xpath/functions/FuncSubstringAfter.h>
#include <org/apache/xpath/functions/Function.h>
#include <org/apache/xpath/functions/FuncQname.h>
#include <org/apache/xpath/functions/FunctionDef1Arg.h>
#include <org/apache/xpath/functions/FuncExtFunctionAvailable.h>
#include <org/apache/xpath/functions/FuncUnparsedEntityURI.h>
#include <org/apache/xpath/functions/FuncFloor.h>
#include <org/apache/xpath/ExpressionOwner.h>
#include <org/apache/xpath/SourceTree.h>
#include <org/apache/xpath/ExpressionNode.h>
#include <org/apache/xpath/XPathException.h>
#include <org/apache/xpath/compiler/Keywords.h>
#include <org/apache/xpath/compiler/XPathDumper.h>
#include <org/apache/xpath/compiler/FunctionTable.h>
#include <org/apache/xpath/compiler/OpMap.h>
#include <org/apache/xpath/compiler/Compiler.h>
#include <org/apache/xpath/compiler/XPathParser.h>
#include <org/apache/xpath/compiler/OpCodes.h>
#include <org/apache/xpath/compiler/PsuedoNames.h>
#include <org/apache/xpath/compiler/OpMapVector.h>
#include <org/apache/xpath/XPathVisitable.h>
#include <org/apache/xml/res/XMLMessages.h>
#include <org/apache/xml/res/XMLErrorResources.h>
#include <org/apache/xml/serializer/ToUnknownStream.h>
#include <org/apache/xml/serializer/ToTextStream.h>
#include <org/apache/xml/serializer/Method.h>
#include <org/apache/xml/serializer/AttributesImplSerializer.h>
#include <org/apache/xml/serializer/DOMSerializer.h>
#include <org/apache/xml/serializer/SerializerBase.h>
#include <org/apache/xml/serializer/ToHTMLStream.h>
#include <org/apache/xml/serializer/utils/StringToIntTable.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_fr.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_ca.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_ko.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_cs.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_sv.h>
#include <org/apache/xml/serializer/utils/Utils.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_es.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_zh_CN.h>
#include <org/apache/xml/serializer/utils/AttList.h>
#include <org/apache/xml/serializer/utils/XML11Char.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_pt_BR.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_zh.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_sl.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_tr.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_zh_TW.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_hu.h>
#include <org/apache/xml/serializer/utils/Messages.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_ja.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_pl.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_ru.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_de.h>
#include <org/apache/xml/serializer/utils/DOM2Helper.h>
#include <org/apache/xml/serializer/utils/XMLChar.h>
#include <org/apache/xml/serializer/utils/MsgKey.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_sk.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_en.h>
#include <org/apache/xml/serializer/utils/SystemIDResolver.h>
#include <org/apache/xml/serializer/utils/WrappedRuntimeException.h>
#include <org/apache/xml/serializer/utils/SerializerMessages.h>
#include <org/apache/xml/serializer/utils/SerializerMessages_it.h>
#include <org/apache/xml/serializer/NamespaceMappings.h>
#include <org/apache/xml/serializer/SerializationHandler.h>
#include <org/apache/xml/serializer/dom3/DOMErrorImpl.h>
#include <org/apache/xml/serializer/dom3/DOM3SerializerImpl.h>
#include <org/apache/xml/serializer/dom3/NamespaceSupport.h>
#include <org/apache/xml/serializer/OutputPropertyUtils.h>
#include <org/apache/xml/serializer/SerializerTrace.h>
#include <org/apache/xml/serializer/ElemDesc.h>
#include <org/apache/xml/serializer/OutputPropertiesFactory.h>
#include <org/apache/xml/serializer/TreeWalker.h>
#include <org/apache/xml/serializer/ToSAXHandler.h>
#include <org/apache/xml/serializer/ExtendedContentHandler.h>
#include <org/apache/xml/serializer/Serializer.h>
#include <org/apache/xml/serializer/ToTextSAXHandler.h>
#include <org/apache/xml/serializer/ExtendedLexicalHandler.h>
#include <org/apache/xml/serializer/ToXMLSAXHandler.h>
#include <org/apache/xml/serializer/Encodings.h>
#include <org/apache/xml/serializer/EncodingInfo.h>
#include <org/apache/xml/serializer/ToXMLStream.h>
#include <org/apache/xml/serializer/SerializerFactory.h>
#include <org/apache/xml/serializer/Version.h>
#include <org/apache/xml/serializer/DOM3Serializer.h>
#include <org/apache/xml/serializer/TransformStateSetter.h>
#include <org/apache/xml/utils/XMLStringDefault.h>
#include <org/apache/xml/utils/StringToIntTable.h>
#include <org/apache/xml/utils/BoolStack.h>
#include <org/apache/xml/utils/res/XResources_ja_JP_I.h>
#include <org/apache/xml/utils/res/XResources_zh_CN.h>
#include <org/apache/xml/utils/res/XResources_sv.h>
#include <org/apache/xml/utils/res/XResources_es.h>
#include <org/apache/xml/utils/res/XResourceBundle.h>
#include <org/apache/xml/utils/res/XResources_fr.h>
#include <org/apache/xml/utils/res/XResources_cy.h>
#include <org/apache/xml/utils/res/XResources_ko.h>
#include <org/apache/xml/utils/res/XResources_he.h>
#include <org/apache/xml/utils/res/XResources_el.h>
#include <org/apache/xml/utils/res/XResources_ja_JP_HI.h>
#include <org/apache/xml/utils/res/XResources_de.h>
#include <org/apache/xml/utils/res/XResources_it.h>
#include <org/apache/xml/utils/res/XResources_ja_JP_A.h>
#include <org/apache/xml/utils/res/XResources_ka.h>
#include <org/apache/xml/utils/res/XResources_en.h>
#include <org/apache/xml/utils/res/XResources_zh_TW.h>
#include <org/apache/xml/utils/res/CharArrayWrapper.h>
#include <org/apache/xml/utils/res/XResources_hy.h>
#include <org/apache/xml/utils/res/StringArrayWrapper.h>
#include <org/apache/xml/utils/res/IntArrayWrapper.h>
#include <org/apache/xml/utils/res/XResources_ja_JP_HA.h>
#include <org/apache/xml/utils/res/LongArrayWrapper.h>
#include <org/apache/xml/utils/PrefixResolverDefault.h>
#include <org/apache/xml/utils/NodeVector.h>
#include <org/apache/xml/utils/NamespaceSupport2.h>
#include <org/apache/xml/utils/NameSpace.h>
#include <org/apache/xml/utils/XMLStringFactory.h>
#include <org/apache/xml/utils/DOMHelper.h>
#include <org/apache/xml/utils/XMLReaderManager.h>
#include <org/apache/xml/utils/DOMOrder.h>
#include <org/apache/xml/utils/ObjectStack.h>
#include <org/apache/xml/utils/StylesheetPIHandler.h>
#include <org/apache/xml/utils/NodeConsumer.h>
#include <org/apache/xml/utils/FastStringBuffer.h>
#include <org/apache/xml/utils/UnImplNode.h>
#include <org/apache/xml/utils/AttList.h>
#include <org/apache/xml/utils/DefaultErrorHandler.h>
#include <org/apache/xml/utils/XML11Char.h>
#include <org/apache/xml/utils/SAXSourceLocator.h>
#include <org/apache/xml/utils/DOMBuilder.h>
#include <org/apache/xml/utils/SuballocatedIntVector.h>
#include <org/apache/xml/utils/XMLString.h>
#include <org/apache/xml/utils/ThreadControllerWrapper.h>
#include <org/apache/xml/utils/ObjectVector.h>
#include <org/apache/xml/utils/TreeWalker.h>
#include <org/apache/xml/utils/URI.h>
#include <org/apache/xml/utils/QName.h>
#include <org/apache/xml/utils/ObjectPool.h>
#include <org/apache/xml/utils/StopParseException.h>
#include <org/apache/xml/utils/StringBufferPool.h>
#include <org/apache/xml/utils/IntStack.h>
#include <org/apache/xml/utils/XMLCharacterRecognizer.h>
#include <org/apache/xml/utils/IntVector.h>
#include <org/apache/xml/utils/NSInfo.h>
#include <org/apache/xml/utils/DOM2Helper.h>
#include <org/apache/xml/utils/XMLChar.h>
#include <org/apache/xml/utils/PrefixResolver.h>
#include <org/apache/xml/utils/StringVector.h>
#include <org/apache/xml/utils/SystemIDResolver.h>
#include <org/apache/xml/utils/WrappedRuntimeException.h>
#include <org/apache/xml/utils/Constants.h>
#include <org/apache/xml/dtm/DTMAxisIterator.h>
#include <org/apache/xml/dtm/DTMFilter.h>
#include <org/apache/xml/dtm/ref/ExpandedNameTable.h>
#include <org/apache/xml/dtm/ref/DTMAxisIteratorBase.h>
#include <org/apache/xml/dtm/ref/DTMDefaultBase.h>
#include <org/apache/xml/dtm/ref/sax2dtm/SAX2RTFDTM.h>
#include <org/apache/xml/dtm/ref/sax2dtm/SAX2DTM2.h>
#include <org/apache/xml/dtm/ref/sax2dtm/SAX2DTM.h>
#include <org/apache/xml/dtm/ref/DTMTreeWalker.h>
#include <org/apache/xml/dtm/ref/dom2dtm/DOM2DTMdefaultNamespaceDeclarationNode.h>
#include <org/apache/xml/dtm/ref/dom2dtm/DOM2DTM.h>
#include <org/apache/xml/dtm/ref/ExtendedType.h>
#include <org/apache/xml/dtm/ref/DTMNodeListBase.h>
#include <org/apache/xml/dtm/ref/DTMNodeList.h>
#include <org/apache/xml/dtm/ref/DTMNodeIterator.h>
#include <org/apache/xml/dtm/ref/DTMDefaultBaseTraversers.h>
#include <org/apache/xml/dtm/ref/DTMChildIterNodeList.h>
#include <org/apache/xml/dtm/ref/DTMDocumentImpl.h>
#include <org/apache/xml/dtm/ref/DTMDefaultBaseIterators.h>
#include <org/apache/xml/dtm/ref/DTMManagerDefault.h>
#include <org/apache/xml/dtm/ref/NodeLocator.h>
#include <org/apache/xml/dtm/ref/IncrementalSAXSource.h>
#include <org/apache/xml/dtm/ref/IncrementalSAXSource_Filter.h>
#include <org/apache/xml/dtm/ref/DTMNamedNodeMap.h>
#include <org/apache/xml/dtm/ref/DTMAxisIterNodeList.h>
#include <org/apache/xml/dtm/ref/DTMStringPool.h>
#include <org/apache/xml/dtm/ref/CoroutineManager.h>
#include <org/apache/xml/dtm/ref/DTMNodeProxy.h>
#include <org/apache/xml/dtm/DTMAxisTraverser.h>
#include <org/apache/xml/dtm/DTMManager.h>
#include <org/apache/xml/dtm/DTMIterator.h>
#include <org/apache/xml/dtm/Axis.h>
#include <org/apache/xml/dtm/DTMDOMException.h>
#include <org/apache/xml/dtm/DTM.h>
#include <org/apache/xml/dtm/DTMException.h>
#include <org/apache/xml/dtm/DTMWSFilter.h>
#include <org/apache/xml/dtm/DTMConfigurationException.h>
#include <org/apache/xalan/res/XSLMessages.h>
#include <org/apache/xalan/res/XSLTErrorResources.h>
#include <org/apache/xalan/transformer/KeyIterator.h>
#include <org/apache/xalan/transformer/TransformerImpl.h>
#include <org/apache/xalan/transformer/XalanTransformState.h>
#include <org/apache/xalan/transformer/TransformerHandlerImpl.h>
#include <org/apache/xalan/transformer/XalanProperties.h>
#include <org/apache/xalan/transformer/KeyTable.h>
#include <org/apache/xalan/transformer/TreeWalker2Result.h>
#include <org/apache/xalan/transformer/TrAXFilter.h>
#include <org/apache/xalan/transformer/DecimalToRoman.h>
#include <org/apache/xalan/transformer/TransformState.h>
#include <org/apache/xalan/transformer/TransformerClient.h>
#include <org/apache/xalan/transformer/Counter.h>
#include <org/apache/xalan/transformer/ClonerToResultTree.h>
#include <org/apache/xalan/transformer/KeyManager.h>
#include <org/apache/xalan/transformer/CountersTable.h>
#include <org/apache/xalan/transformer/NodeSorter.h>
#include <org/apache/xalan/transformer/TransformerIdentityImpl.h>
#include <org/apache/xalan/transformer/MsgMgr.h>
#include <org/apache/xalan/transformer/SerializerSwitcher.h>
#include <org/apache/xalan/processor/StylesheetHandler.h>
#include <org/apache/xalan/processor/ProcessorExsltFunction.h>
#include <org/apache/xalan/processor/ProcessorExsltFuncResult.h>
#include <org/apache/xalan/processor/ProcessorTemplateElem.h>
#include <org/apache/xalan/processor/ProcessorStylesheetElement.h>
#include <org/apache/xalan/processor/TransformerFactoryImpl.h>
#include <org/apache/xalan/processor/XSLTAttributeDef.h>
#include <org/apache/xalan/processor/WhitespaceInfoPaths.h>
#include <org/apache/xalan/processor/ProcessorInclude.h>
#include <org/apache/xalan/processor/ProcessorUnknown.h>
#include <org/apache/xalan/processor/XSLTSchema.h>
#include <org/apache/xalan/processor/XSLTElementProcessor.h>
#include <org/apache/xalan/processor/ProcessorStylesheetDoc.h>
#include <org/apache/xalan/processor/ProcessorImport.h>
#include <org/apache/xalan/processor/ProcessorText.h>
#include <org/apache/xalan/processor/ProcessorLRE.h>
#include <org/apache/xalan/processor/XSLTElementDef.h>
#include <org/apache/xalan/processor/ProcessorCharacters.h>
#include <org/apache/xalan/serialize/SerializerUtils.h>
#include <org/apache/xalan/extensions/ExtensionsTable.h>
#include <org/apache/xalan/extensions/ExpressionContext.h>
#include <org/apache/xalan/extensions/ExpressionVisitor.h>
#include <org/apache/xalan/extensions/ExtensionNamespacesManager.h>
#include <org/apache/xalan/extensions/ExtensionHandler.h>
#include <org/apache/xalan/extensions/ExtensionNamespaceSupport.h>
#include <org/apache/xalan/templates/VarNameCollector.h>
#include <org/apache/xalan/templates/ElemText.h>
#include <org/apache/xalan/templates/ElemWhen.h>
#include <org/apache/xalan/templates/AVTPartXPath.h>
#include <org/apache/xalan/templates/ElemSort.h>
#include <org/apache/xalan/templates/OutputProperties.h>
#include <org/apache/xalan/templates/ElemValueOf.h>
#include <org/apache/xalan/templates/ElemUnknown.h>
#include <org/apache/xalan/templates/ElemWithParam.h>
#include <org/apache/xalan/templates/XUnresolvedVariableSimple.h>
#include <org/apache/xalan/templates/FuncDocument.h>
#include <org/apache/xalan/templates/ElemExtensionScript.h>
#include <org/apache/xalan/templates/FuncFormatNumb.h>
#include <org/apache/xalan/templates/ElemExsltFuncResult.h>
#include <org/apache/xalan/templates/ElemApplyImport.h>
#include <org/apache/xalan/templates/StylesheetComposed.h>
#include <org/apache/xalan/templates/ElemMessage.h>
#include <org/apache/xalan/templates/XSLTVisitable.h>
#include <org/apache/xalan/templates/RedundentExprEliminator.h>
#include <org/apache/xalan/templates/ElemEmpty.h>
#include <org/apache/xalan/templates/ElemApplyTemplates.h>
#include <org/apache/xalan/templates/ElemPI.h>
#include <org/apache/xalan/templates/ElemElement.h>
#include <org/apache/xalan/templates/XSLTVisitor.h>
#include <org/apache/xalan/templates/NamespaceAlias.h>
#include <org/apache/xalan/templates/AVT.h>
#include <org/apache/xalan/templates/AVTPartSimple.h>
#include <org/apache/xalan/templates/ElemTextLiteral.h>
#include <org/apache/xalan/templates/ElemChoose.h>
#include <org/apache/xalan/templates/ElemParam.h>
#include <org/apache/xalan/templates/ElemAttribute.h>
#include <org/apache/xalan/templates/ElemNumber.h>
#include <org/apache/xalan/templates/XUnresolvedVariable.h>
#include <org/apache/xalan/templates/ElemLiteralResult.h>
#include <org/apache/xalan/templates/StylesheetRoot.h>
#include <org/apache/xalan/templates/ElemExtensionDecl.h>
#include <org/apache/xalan/templates/ElemTemplate.h>
#include <org/apache/xalan/templates/Stylesheet.h>
#include <org/apache/xalan/templates/ElemVariablePsuedo.h>
#include <org/apache/xalan/templates/KeyDeclaration.h>
#include <org/apache/xalan/templates/ElemIf.h>
#include <org/apache/xalan/templates/FuncKey.h>
#include <org/apache/xalan/templates/ElemTemplateElement.h>
#include <org/apache/xalan/templates/XMLNSDecl.h>
#include <org/apache/xalan/templates/ElemForEach.h>
#include <org/apache/xalan/templates/DecimalFormatProperties.h>
#include <org/apache/xalan/templates/ElemUse.h>
#include <org/apache/xalan/templates/WhiteSpaceInfo.h>
#include <org/apache/xalan/templates/AVTPart.h>
#include <org/apache/xalan/templates/ElemExtensionCall.h>
#include <org/apache/xalan/templates/ElemCopy.h>
#include <org/apache/xalan/templates/ElemVariable.h>
#include <org/apache/xalan/templates/ElemExsltFunction.h>
#include <org/apache/xalan/templates/ElemComment.h>
#include <org/apache/xalan/templates/ElemAttributeSet.h>
#include <org/apache/xalan/templates/ElemCopyOf.h>
#include <org/apache/xalan/templates/TemplateList.h>
#include <org/apache/xalan/templates/ElemOtherwise.h>
#include <org/apache/xalan/templates/AbsPathChecker.h>
#include <org/apache/xalan/templates/Constants.h>
#include <org/apache/xalan/templates/ElemCallTemplate.h>
#include <org/apache/xalan/templates/ElemFallback.h>
#include <org/apache/xalan/xslt/EnvironmentCheck.h>
#include <org/apache/xalan/Version.h>
