//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/junit/build_result/java/org/junit/internal/requests/ClassRequest.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitInternalRequestsClassRequest")
#ifdef RESTRICT_OrgJunitInternalRequestsClassRequest
#define INCLUDE_ALL_OrgJunitInternalRequestsClassRequest 0
#else
#define INCLUDE_ALL_OrgJunitInternalRequestsClassRequest 1
#endif
#undef RESTRICT_OrgJunitInternalRequestsClassRequest

#if !defined (OrgJunitInternalRequestsClassRequest_) && (INCLUDE_ALL_OrgJunitInternalRequestsClassRequest || defined(INCLUDE_OrgJunitInternalRequestsClassRequest))
#define OrgJunitInternalRequestsClassRequest_

#define RESTRICT_OrgJunitInternalRequestsMemoizingRequest 1
#define INCLUDE_OrgJunitInternalRequestsMemoizingRequest 1
#include "org/junit/internal/requests/MemoizingRequest.h"

@class IOSClass;
@class JavaLangBoolean;
@class OrgJunitRunnerRunner;

@interface OrgJunitInternalRequestsClassRequest : OrgJunitInternalRequestsMemoizingRequest

#pragma mark Public

- (instancetype)initWithIOSClass:(IOSClass *)testClass;

- (instancetype)initWithIOSClass:(IOSClass *)testClass
                     withBoolean:(jboolean)canUseSuiteMethod;

#pragma mark Protected

- (OrgJunitRunnerRunner *)createRunner;

// Disallowed inherited constructors, do not use.

- (instancetype)initPackagePrivate NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitInternalRequestsClassRequest)

FOUNDATION_EXPORT void OrgJunitInternalRequestsClassRequest_initWithIOSClass_withBoolean_(OrgJunitInternalRequestsClassRequest *self, IOSClass *testClass, jboolean canUseSuiteMethod);

FOUNDATION_EXPORT OrgJunitInternalRequestsClassRequest *new_OrgJunitInternalRequestsClassRequest_initWithIOSClass_withBoolean_(IOSClass *testClass, jboolean canUseSuiteMethod) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitInternalRequestsClassRequest *create_OrgJunitInternalRequestsClassRequest_initWithIOSClass_withBoolean_(IOSClass *testClass, jboolean canUseSuiteMethod);

FOUNDATION_EXPORT void OrgJunitInternalRequestsClassRequest_initWithIOSClass_(OrgJunitInternalRequestsClassRequest *self, IOSClass *testClass);

FOUNDATION_EXPORT OrgJunitInternalRequestsClassRequest *new_OrgJunitInternalRequestsClassRequest_initWithIOSClass_(IOSClass *testClass) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitInternalRequestsClassRequest *create_OrgJunitInternalRequestsClassRequest_initWithIOSClass_(IOSClass *testClass);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitInternalRequestsClassRequest)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgJunitInternalRequestsClassRequest")
