//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/android/build_result/java/com/google/common/base/ExtraObjectsMethodsForWeb.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonBaseExtraObjectsMethodsForWeb")
#ifdef RESTRICT_ComGoogleCommonBaseExtraObjectsMethodsForWeb
#define INCLUDE_ALL_ComGoogleCommonBaseExtraObjectsMethodsForWeb 0
#else
#define INCLUDE_ALL_ComGoogleCommonBaseExtraObjectsMethodsForWeb 1
#endif
#undef RESTRICT_ComGoogleCommonBaseExtraObjectsMethodsForWeb

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonBaseExtraObjectsMethodsForWeb_) && (INCLUDE_ALL_ComGoogleCommonBaseExtraObjectsMethodsForWeb || defined(INCLUDE_ComGoogleCommonBaseExtraObjectsMethodsForWeb))
#define ComGoogleCommonBaseExtraObjectsMethodsForWeb_

@interface ComGoogleCommonBaseExtraObjectsMethodsForWeb : NSObject

#pragma mark Package-Private

- (instancetype)initPackagePrivate;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonBaseExtraObjectsMethodsForWeb)

FOUNDATION_EXPORT void ComGoogleCommonBaseExtraObjectsMethodsForWeb_initPackagePrivate(ComGoogleCommonBaseExtraObjectsMethodsForWeb *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonBaseExtraObjectsMethodsForWeb)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonBaseExtraObjectsMethodsForWeb")
