//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/junit/build_result/java/org/junit/experimental/theories/DataPoint.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitExperimentalTheoriesDataPoint")
#ifdef RESTRICT_OrgJunitExperimentalTheoriesDataPoint
#define INCLUDE_ALL_OrgJunitExperimentalTheoriesDataPoint 0
#else
#define INCLUDE_ALL_OrgJunitExperimentalTheoriesDataPoint 1
#endif
#undef RESTRICT_OrgJunitExperimentalTheoriesDataPoint

#if !defined (OrgJunitExperimentalTheoriesDataPoint_) && (INCLUDE_ALL_OrgJunitExperimentalTheoriesDataPoint || defined(INCLUDE_OrgJunitExperimentalTheoriesDataPoint))
#define OrgJunitExperimentalTheoriesDataPoint_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;

@protocol OrgJunitExperimentalTheoriesDataPoint < JavaLangAnnotationAnnotation >

@property (readonly) IOSObjectArray *value;
@property (readonly) IOSObjectArray *ignoredExceptions;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface OrgJunitExperimentalTheoriesDataPoint : NSObject < OrgJunitExperimentalTheoriesDataPoint > {
 @public
  IOSObjectArray *value_;
  IOSObjectArray *ignoredExceptions_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitExperimentalTheoriesDataPoint)

FOUNDATION_EXPORT id<OrgJunitExperimentalTheoriesDataPoint> create_OrgJunitExperimentalTheoriesDataPoint(IOSObjectArray *ignoredExceptions, IOSObjectArray *value);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitExperimentalTheoriesDataPoint)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgJunitExperimentalTheoriesDataPoint")
