//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/junit/build_result/java/com/tngtech/java/junit/dataprovider/internal/placeholder/BasePlaceholder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder")
#ifdef RESTRICT_ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder
#define INCLUDE_ALL_ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder 0
#else
#define INCLUDE_ALL_ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder 1
#endif
#undef RESTRICT_ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder

#if !defined (ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder_) && (INCLUDE_ALL_ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder || defined(INCLUDE_ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder))
#define ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder_

@class IOSObjectArray;
@class JavaLangInteger;
@class JavaLangReflectMethod;

@interface ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder : NSObject {
 @public
  JavaLangReflectMethod *method_;
  jint idx_;
  IOSObjectArray *parameters_;
}

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)placeholderRegex;

- (NSString *)processWithNSString:(NSString *)formatPattern;

- (void)setContextWithJavaLangReflectMethod:(JavaLangReflectMethod *)method
                                    withInt:(jint)idx
                          withNSObjectArray:(IOSObjectArray *)parameters;

#pragma mark Protected

- (NSString *)getReplacementForWithNSString:(NSString *)placeholder;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder)

J2OBJC_FIELD_SETTER(ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder, method_, JavaLangReflectMethod *)
J2OBJC_FIELD_SETTER(ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder, parameters_, IOSObjectArray *)

FOUNDATION_EXPORT void ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder_initWithNSString_(ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder *self, NSString *placeholderRegex);

J2OBJC_TYPE_LITERAL_HEADER(ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder)

#endif

#pragma pop_macro("INCLUDE_ALL_ComTngtechJavaJunitDataproviderInternalPlaceholderBasePlaceholder")
