//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xml/dtm/ref/DTMNodeList.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXmlDtmRefDTMNodeList")
#ifdef RESTRICT_OrgApacheXmlDtmRefDTMNodeList
#define INCLUDE_ALL_OrgApacheXmlDtmRefDTMNodeList 0
#else
#define INCLUDE_ALL_OrgApacheXmlDtmRefDTMNodeList 1
#endif
#undef RESTRICT_OrgApacheXmlDtmRefDTMNodeList

#if !defined (OrgApacheXmlDtmRefDTMNodeList_) && (INCLUDE_ALL_OrgApacheXmlDtmRefDTMNodeList || defined(INCLUDE_OrgApacheXmlDtmRefDTMNodeList))
#define OrgApacheXmlDtmRefDTMNodeList_

#define RESTRICT_OrgApacheXmlDtmRefDTMNodeListBase 1
#define INCLUDE_OrgApacheXmlDtmRefDTMNodeListBase 1
#include "org/apache/xml/dtm/ref/DTMNodeListBase.h"

@class JavaLangInteger;
@protocol OrgApacheXmlDtmDTMIterator;
@protocol OrgW3cDomNode;

@interface OrgApacheXmlDtmRefDTMNodeList : OrgApacheXmlDtmRefDTMNodeListBase

#pragma mark Public

- (instancetype)initWithOrgApacheXmlDtmDTMIterator:(id<OrgApacheXmlDtmDTMIterator>)dtmIterator;

- (id<OrgApacheXmlDtmDTMIterator>)getDTMIterator;

- (jint)getLength;

- (id<OrgW3cDomNode>)itemWithInt:(jint)index;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXmlDtmRefDTMNodeList)

FOUNDATION_EXPORT void OrgApacheXmlDtmRefDTMNodeList_initWithOrgApacheXmlDtmDTMIterator_(OrgApacheXmlDtmRefDTMNodeList *self, id<OrgApacheXmlDtmDTMIterator> dtmIterator);

FOUNDATION_EXPORT OrgApacheXmlDtmRefDTMNodeList *new_OrgApacheXmlDtmRefDTMNodeList_initWithOrgApacheXmlDtmDTMIterator_(id<OrgApacheXmlDtmDTMIterator> dtmIterator) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXmlDtmRefDTMNodeList *create_OrgApacheXmlDtmRefDTMNodeList_initWithOrgApacheXmlDtmDTMIterator_(id<OrgApacheXmlDtmDTMIterator> dtmIterator);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXmlDtmRefDTMNodeList)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXmlDtmRefDTMNodeList")
