//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xml/dtm/ref/SecuritySupport.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXmlDtmRefSecuritySupport")
#ifdef RESTRICT_OrgApacheXmlDtmRefSecuritySupport
#define INCLUDE_ALL_OrgApacheXmlDtmRefSecuritySupport 0
#else
#define INCLUDE_ALL_OrgApacheXmlDtmRefSecuritySupport 1
#endif
#undef RESTRICT_OrgApacheXmlDtmRefSecuritySupport

#if !defined (OrgApacheXmlDtmRefSecuritySupport_) && (INCLUDE_ALL_OrgApacheXmlDtmRefSecuritySupport || defined(INCLUDE_OrgApacheXmlDtmRefSecuritySupport))
#define OrgApacheXmlDtmRefSecuritySupport_

@class JavaIoFile;
@class JavaIoFileInputStream;
@class JavaIoInputStream;
@class JavaLangBoolean;
@class JavaLangClassLoader;
@class JavaLangLong;

@interface OrgApacheXmlDtmRefSecuritySupport : NSObject

#pragma mark Package-Private

- (instancetype)initPackagePrivate;

- (JavaLangClassLoader *)getContextClassLoader;

- (jboolean)getFileExistsWithJavaIoFile:(JavaIoFile *)f;

- (JavaIoFileInputStream *)getFileInputStreamWithJavaIoFile:(JavaIoFile *)file;

+ (OrgApacheXmlDtmRefSecuritySupport *)getInstance;

- (jlong)getLastModifiedWithJavaIoFile:(JavaIoFile *)f;

- (JavaLangClassLoader *)getParentClassLoaderWithJavaLangClassLoader:(JavaLangClassLoader *)cl;

- (JavaIoInputStream *)getResourceAsStreamWithJavaLangClassLoader:(JavaLangClassLoader *)cl
                                                     withNSString:(NSString *)name;

- (JavaLangClassLoader *)getSystemClassLoader;

- (NSString *)getSystemPropertyWithNSString:(NSString *)propName;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(OrgApacheXmlDtmRefSecuritySupport)

FOUNDATION_EXPORT void OrgApacheXmlDtmRefSecuritySupport_initPackagePrivate(OrgApacheXmlDtmRefSecuritySupport *self);

FOUNDATION_EXPORT OrgApacheXmlDtmRefSecuritySupport *new_OrgApacheXmlDtmRefSecuritySupport_initPackagePrivate(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXmlDtmRefSecuritySupport *create_OrgApacheXmlDtmRefSecuritySupport_initPackagePrivate(void);

FOUNDATION_EXPORT OrgApacheXmlDtmRefSecuritySupport *OrgApacheXmlDtmRefSecuritySupport_getInstance(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXmlDtmRefSecuritySupport)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXmlDtmRefSecuritySupport")
