//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/build_result/java/com/google/common/collect/CollectCollectors.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonCollectCollectCollectors")
#ifdef RESTRICT_ComGoogleCommonCollectCollectCollectors
#define INCLUDE_ALL_ComGoogleCommonCollectCollectCollectors 0
#else
#define INCLUDE_ALL_ComGoogleCommonCollectCollectCollectors 1
#endif
#undef RESTRICT_ComGoogleCommonCollectCollectCollectors

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonCollectCollectCollectors_) && (INCLUDE_ALL_ComGoogleCommonCollectCollectCollectors || defined(INCLUDE_ComGoogleCommonCollectCollectCollectors))
#define ComGoogleCommonCollectCollectCollectors_

@protocol JavaUtilComparator;
@protocol JavaUtilFunctionBinaryOperator;
@protocol JavaUtilFunctionFunction;
@protocol JavaUtilFunctionSupplier;
@protocol JavaUtilFunctionToIntFunction;
@protocol JavaUtilStreamCollector;

@interface ComGoogleCommonCollectCollectCollectors : NSObject

#pragma mark Public

+ (id<JavaUtilStreamCollector>)toImmutableMapWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)keyFunction
                                             withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valueFunction
                                       withJavaUtilFunctionBinaryOperator:(id<JavaUtilFunctionBinaryOperator>)mergeFunction;

#pragma mark Package-Private

- (instancetype)initPackagePrivate;

+ (id<JavaUtilStreamCollector>)flatteningToImmutableListMultimapWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)keyFunction
                                                                withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valuesFunction;

+ (id<JavaUtilStreamCollector>)flatteningToImmutableSetMultimapWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)keyFunction
                                                               withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valuesFunction;

+ (id<JavaUtilStreamCollector>)flatteningToMultimapWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)keyFunction
                                                   withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valueFunction
                                                   withJavaUtilFunctionSupplier:(id<JavaUtilFunctionSupplier>)multimapSupplier;

+ (id<JavaUtilStreamCollector>)toImmutableBiMapWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)keyFunction
                                               withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valueFunction;

+ (id<JavaUtilStreamCollector>)toImmutableEnumMapWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)keyFunction
                                                 withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valueFunction;

+ (id<JavaUtilStreamCollector>)toImmutableEnumMapWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)keyFunction
                                                 withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valueFunction
                                           withJavaUtilFunctionBinaryOperator:(id<JavaUtilFunctionBinaryOperator>)mergeFunction;

+ (id<JavaUtilStreamCollector>)toImmutableEnumSet;

+ (id<JavaUtilStreamCollector>)toImmutableList;

+ (id<JavaUtilStreamCollector>)toImmutableListMultimapWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)keyFunction
                                                      withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valueFunction;

+ (id<JavaUtilStreamCollector>)toImmutableMapWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)keyFunction
                                             withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valueFunction;

+ (id<JavaUtilStreamCollector>)toImmutableMultisetWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)elementFunction
                                             withJavaUtilFunctionToIntFunction:(id<JavaUtilFunctionToIntFunction>)countFunction;

+ (id<JavaUtilStreamCollector>)toImmutableRangeMapWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)keyFunction
                                                  withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valueFunction;

+ (id<JavaUtilStreamCollector>)toImmutableRangeSet;

+ (id<JavaUtilStreamCollector>)toImmutableSet;

+ (id<JavaUtilStreamCollector>)toImmutableSetMultimapWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)keyFunction
                                                     withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valueFunction;

+ (id<JavaUtilStreamCollector>)toImmutableSortedMapWithJavaUtilComparator:(id<JavaUtilComparator>)comparator
                                             withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)keyFunction
                                             withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valueFunction;

+ (id<JavaUtilStreamCollector>)toImmutableSortedMapWithJavaUtilComparator:(id<JavaUtilComparator>)comparator
                                             withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)keyFunction
                                             withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valueFunction
                                       withJavaUtilFunctionBinaryOperator:(id<JavaUtilFunctionBinaryOperator>)mergeFunction;

+ (id<JavaUtilStreamCollector>)toImmutableSortedSetWithJavaUtilComparator:(id<JavaUtilComparator>)comparator;

+ (id<JavaUtilStreamCollector>)toMultimapWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)keyFunction
                                         withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valueFunction
                                         withJavaUtilFunctionSupplier:(id<JavaUtilFunctionSupplier>)multimapSupplier;

+ (id<JavaUtilStreamCollector>)toMultisetWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)elementFunction
                                    withJavaUtilFunctionToIntFunction:(id<JavaUtilFunctionToIntFunction>)countFunction
                                         withJavaUtilFunctionSupplier:(id<JavaUtilFunctionSupplier>)multisetSupplier;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(ComGoogleCommonCollectCollectCollectors)

FOUNDATION_EXPORT void ComGoogleCommonCollectCollectCollectors_initPackagePrivate(ComGoogleCommonCollectCollectCollectors *self);

FOUNDATION_EXPORT ComGoogleCommonCollectCollectCollectors *new_ComGoogleCommonCollectCollectCollectors_initPackagePrivate(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectCollectCollectors *create_ComGoogleCommonCollectCollectCollectors_initPackagePrivate(void);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toImmutableList(void);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toImmutableSet(void);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toImmutableSortedSetWithJavaUtilComparator_(id<JavaUtilComparator> comparator);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toImmutableEnumSet(void);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toImmutableRangeSet(void);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toImmutableMultisetWithJavaUtilFunctionFunction_withJavaUtilFunctionToIntFunction_(id<JavaUtilFunctionFunction> elementFunction, id<JavaUtilFunctionToIntFunction> countFunction);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toMultisetWithJavaUtilFunctionFunction_withJavaUtilFunctionToIntFunction_withJavaUtilFunctionSupplier_(id<JavaUtilFunctionFunction> elementFunction, id<JavaUtilFunctionToIntFunction> countFunction, id<JavaUtilFunctionSupplier> multisetSupplier);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toImmutableMapWithJavaUtilFunctionFunction_withJavaUtilFunctionFunction_(id<JavaUtilFunctionFunction> keyFunction, id<JavaUtilFunctionFunction> valueFunction);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toImmutableMapWithJavaUtilFunctionFunction_withJavaUtilFunctionFunction_withJavaUtilFunctionBinaryOperator_(id<JavaUtilFunctionFunction> keyFunction, id<JavaUtilFunctionFunction> valueFunction, id<JavaUtilFunctionBinaryOperator> mergeFunction);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toImmutableSortedMapWithJavaUtilComparator_withJavaUtilFunctionFunction_withJavaUtilFunctionFunction_(id<JavaUtilComparator> comparator, id<JavaUtilFunctionFunction> keyFunction, id<JavaUtilFunctionFunction> valueFunction);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toImmutableSortedMapWithJavaUtilComparator_withJavaUtilFunctionFunction_withJavaUtilFunctionFunction_withJavaUtilFunctionBinaryOperator_(id<JavaUtilComparator> comparator, id<JavaUtilFunctionFunction> keyFunction, id<JavaUtilFunctionFunction> valueFunction, id<JavaUtilFunctionBinaryOperator> mergeFunction);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toImmutableBiMapWithJavaUtilFunctionFunction_withJavaUtilFunctionFunction_(id<JavaUtilFunctionFunction> keyFunction, id<JavaUtilFunctionFunction> valueFunction);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toImmutableEnumMapWithJavaUtilFunctionFunction_withJavaUtilFunctionFunction_(id<JavaUtilFunctionFunction> keyFunction, id<JavaUtilFunctionFunction> valueFunction);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toImmutableEnumMapWithJavaUtilFunctionFunction_withJavaUtilFunctionFunction_withJavaUtilFunctionBinaryOperator_(id<JavaUtilFunctionFunction> keyFunction, id<JavaUtilFunctionFunction> valueFunction, id<JavaUtilFunctionBinaryOperator> mergeFunction);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toImmutableRangeMapWithJavaUtilFunctionFunction_withJavaUtilFunctionFunction_(id<JavaUtilFunctionFunction> keyFunction, id<JavaUtilFunctionFunction> valueFunction);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toImmutableListMultimapWithJavaUtilFunctionFunction_withJavaUtilFunctionFunction_(id<JavaUtilFunctionFunction> keyFunction, id<JavaUtilFunctionFunction> valueFunction);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_flatteningToImmutableListMultimapWithJavaUtilFunctionFunction_withJavaUtilFunctionFunction_(id<JavaUtilFunctionFunction> keyFunction, id<JavaUtilFunctionFunction> valuesFunction);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toImmutableSetMultimapWithJavaUtilFunctionFunction_withJavaUtilFunctionFunction_(id<JavaUtilFunctionFunction> keyFunction, id<JavaUtilFunctionFunction> valueFunction);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_flatteningToImmutableSetMultimapWithJavaUtilFunctionFunction_withJavaUtilFunctionFunction_(id<JavaUtilFunctionFunction> keyFunction, id<JavaUtilFunctionFunction> valuesFunction);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_toMultimapWithJavaUtilFunctionFunction_withJavaUtilFunctionFunction_withJavaUtilFunctionSupplier_(id<JavaUtilFunctionFunction> keyFunction, id<JavaUtilFunctionFunction> valueFunction, id<JavaUtilFunctionSupplier> multimapSupplier);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectCollectCollectors_flatteningToMultimapWithJavaUtilFunctionFunction_withJavaUtilFunctionFunction_withJavaUtilFunctionSupplier_(id<JavaUtilFunctionFunction> keyFunction, id<JavaUtilFunctionFunction> valueFunction, id<JavaUtilFunctionSupplier> multimapSupplier);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectCollectCollectors)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonCollectCollectCollectors")
