//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/build_result/java/com/google/common/collect/JdkBackedImmutableSet.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonCollectJdkBackedImmutableSet")
#ifdef RESTRICT_ComGoogleCommonCollectJdkBackedImmutableSet
#define INCLUDE_ALL_ComGoogleCommonCollectJdkBackedImmutableSet 0
#else
#define INCLUDE_ALL_ComGoogleCommonCollectJdkBackedImmutableSet 1
#endif
#undef RESTRICT_ComGoogleCommonCollectJdkBackedImmutableSet

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonCollectJdkBackedImmutableSet_) && (INCLUDE_ALL_ComGoogleCommonCollectJdkBackedImmutableSet || defined(INCLUDE_ComGoogleCommonCollectJdkBackedImmutableSet))
#define ComGoogleCommonCollectJdkBackedImmutableSet_

#define RESTRICT_ComGoogleCommonCollectIndexedImmutableSet 1
#define INCLUDE_ComGoogleCommonCollectIndexedImmutableSet 1
#include "com/google/common/collect/IndexedImmutableSet.h"

@class ComGoogleCommonCollectImmutableList;
@class JavaLangBoolean;
@class JavaLangInteger;
@protocol JavaUtilSet;

@interface ComGoogleCommonCollectJdkBackedImmutableSet : ComGoogleCommonCollectIndexedImmutableSet

#pragma mark Public

- (jboolean)containsWithId:(id)object;

- (jint)size;

#pragma mark Package-Private

- (instancetype)initPackagePrivateWithJavaUtilSet:(id<JavaUtilSet>)delegate
          withComGoogleCommonCollectImmutableList:(ComGoogleCommonCollectImmutableList *)delegateList;

- (id)getWithInt:(jint)index;

- (jboolean)isPartialView;

// Disallowed inherited constructors, do not use.

- (instancetype)initPackagePrivate NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectJdkBackedImmutableSet)

FOUNDATION_EXPORT void ComGoogleCommonCollectJdkBackedImmutableSet_initPackagePrivateWithJavaUtilSet_withComGoogleCommonCollectImmutableList_(ComGoogleCommonCollectJdkBackedImmutableSet *self, id<JavaUtilSet> delegate, ComGoogleCommonCollectImmutableList *delegateList);

FOUNDATION_EXPORT ComGoogleCommonCollectJdkBackedImmutableSet *new_ComGoogleCommonCollectJdkBackedImmutableSet_initPackagePrivateWithJavaUtilSet_withComGoogleCommonCollectImmutableList_(id<JavaUtilSet> delegate, ComGoogleCommonCollectImmutableList *delegateList) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectJdkBackedImmutableSet *create_ComGoogleCommonCollectJdkBackedImmutableSet_initPackagePrivateWithJavaUtilSet_withComGoogleCommonCollectImmutableList_(id<JavaUtilSet> delegate, ComGoogleCommonCollectImmutableList *delegateList);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectJdkBackedImmutableSet)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonCollectJdkBackedImmutableSet")
