//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/build_result/java/com/google/common/collect/SingletonImmutableList.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonCollectSingletonImmutableList")
#ifdef RESTRICT_ComGoogleCommonCollectSingletonImmutableList
#define INCLUDE_ALL_ComGoogleCommonCollectSingletonImmutableList 0
#else
#define INCLUDE_ALL_ComGoogleCommonCollectSingletonImmutableList 1
#endif
#undef RESTRICT_ComGoogleCommonCollectSingletonImmutableList

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonCollectSingletonImmutableList_) && (INCLUDE_ALL_ComGoogleCommonCollectSingletonImmutableList || defined(INCLUDE_ComGoogleCommonCollectSingletonImmutableList))
#define ComGoogleCommonCollectSingletonImmutableList_

#define RESTRICT_ComGoogleCommonCollectImmutableList 1
#define INCLUDE_ComGoogleCommonCollectImmutableList 1
#include "com/google/common/collect/ImmutableList.h"

@class ComGoogleCommonCollectUnmodifiableIterator;
@class JavaLangBoolean;
@class JavaLangInteger;
@protocol JavaUtilSpliterator;

@interface ComGoogleCommonCollectSingletonImmutableList : ComGoogleCommonCollectImmutableList {
 @public
  id element_;
}

#pragma mark Public

- (id)getWithInt:(jint)index;

- (ComGoogleCommonCollectUnmodifiableIterator *)iterator;

- (jint)size;

- (id<JavaUtilSpliterator>)spliterator;

- (ComGoogleCommonCollectImmutableList *)subListWithInt:(jint)fromIndex
                                                withInt:(jint)toIndex;

- (NSString *)description;

#pragma mark Package-Private

- (instancetype)initPackagePrivateWithId:(id)element;

- (jboolean)isPartialView;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectSingletonImmutableList)

J2OBJC_FIELD_SETTER(ComGoogleCommonCollectSingletonImmutableList, element_, id)

FOUNDATION_EXPORT void ComGoogleCommonCollectSingletonImmutableList_initPackagePrivateWithId_(ComGoogleCommonCollectSingletonImmutableList *self, id element);

FOUNDATION_EXPORT ComGoogleCommonCollectSingletonImmutableList *new_ComGoogleCommonCollectSingletonImmutableList_initPackagePrivateWithId_(id element) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonCollectSingletonImmutableList *create_ComGoogleCommonCollectSingletonImmutableList_initPackagePrivateWithId_(id element);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectSingletonImmutableList)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonCollectSingletonImmutableList")
