//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/build_result/java/com/google/common/collect/TableCollectors.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonCollectTableCollectors")
#ifdef RESTRICT_ComGoogleCommonCollectTableCollectors
#define INCLUDE_ALL_ComGoogleCommonCollectTableCollectors 0
#else
#define INCLUDE_ALL_ComGoogleCommonCollectTableCollectors 1
#endif
#undef RESTRICT_ComGoogleCommonCollectTableCollectors

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonCollectTableCollectors_) && (INCLUDE_ALL_ComGoogleCommonCollectTableCollectors || defined(INCLUDE_ComGoogleCommonCollectTableCollectors))
#define ComGoogleCommonCollectTableCollectors_

@protocol JavaUtilFunctionBinaryOperator;
@protocol JavaUtilFunctionFunction;
@protocol JavaUtilFunctionSupplier;
@protocol JavaUtilStreamCollector;

@interface ComGoogleCommonCollectTableCollectors : NSObject

#pragma mark Package-Private

+ (id<JavaUtilStreamCollector>)toImmutableTableWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)rowFunction
                                               withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)columnFunction
                                               withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valueFunction;

+ (id<JavaUtilStreamCollector>)toImmutableTableWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)rowFunction
                                               withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)columnFunction
                                               withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valueFunction
                                         withJavaUtilFunctionBinaryOperator:(id<JavaUtilFunctionBinaryOperator>)mergeFunction;

+ (id<JavaUtilStreamCollector>)toTableWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)rowFunction
                                      withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)columnFunction
                                      withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valueFunction
                                withJavaUtilFunctionBinaryOperator:(id<JavaUtilFunctionBinaryOperator>)mergeFunction
                                      withJavaUtilFunctionSupplier:(id<JavaUtilFunctionSupplier>)tableSupplier;

+ (id<JavaUtilStreamCollector>)toTableWithJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)rowFunction
                                      withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)columnFunction
                                      withJavaUtilFunctionFunction:(id<JavaUtilFunctionFunction>)valueFunction
                                      withJavaUtilFunctionSupplier:(id<JavaUtilFunctionSupplier>)tableSupplier;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectTableCollectors)

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectTableCollectors_toImmutableTableWithJavaUtilFunctionFunction_withJavaUtilFunctionFunction_withJavaUtilFunctionFunction_(id<JavaUtilFunctionFunction> rowFunction, id<JavaUtilFunctionFunction> columnFunction, id<JavaUtilFunctionFunction> valueFunction);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectTableCollectors_toImmutableTableWithJavaUtilFunctionFunction_withJavaUtilFunctionFunction_withJavaUtilFunctionFunction_withJavaUtilFunctionBinaryOperator_(id<JavaUtilFunctionFunction> rowFunction, id<JavaUtilFunctionFunction> columnFunction, id<JavaUtilFunctionFunction> valueFunction, id<JavaUtilFunctionBinaryOperator> mergeFunction);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectTableCollectors_toTableWithJavaUtilFunctionFunction_withJavaUtilFunctionFunction_withJavaUtilFunctionFunction_withJavaUtilFunctionSupplier_(id<JavaUtilFunctionFunction> rowFunction, id<JavaUtilFunctionFunction> columnFunction, id<JavaUtilFunctionFunction> valueFunction, id<JavaUtilFunctionSupplier> tableSupplier);

FOUNDATION_EXPORT id<JavaUtilStreamCollector> ComGoogleCommonCollectTableCollectors_toTableWithJavaUtilFunctionFunction_withJavaUtilFunctionFunction_withJavaUtilFunctionFunction_withJavaUtilFunctionBinaryOperator_withJavaUtilFunctionSupplier_(id<JavaUtilFunctionFunction> rowFunction, id<JavaUtilFunctionFunction> columnFunction, id<JavaUtilFunctionFunction> valueFunction, id<JavaUtilFunctionBinaryOperator> mergeFunction, id<JavaUtilFunctionSupplier> tableSupplier);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectTableCollectors)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonCollectTableCollectors")
