//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xpath/ExpressionNode.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXpathExpressionNode")
#ifdef RESTRICT_OrgApacheXpathExpressionNode
#define INCLUDE_ALL_OrgApacheXpathExpressionNode 0
#else
#define INCLUDE_ALL_OrgApacheXpathExpressionNode 1
#endif
#undef RESTRICT_OrgApacheXpathExpressionNode

#if !defined (OrgApacheXpathExpressionNode_) && (INCLUDE_ALL_OrgApacheXpathExpressionNode || defined(INCLUDE_OrgApacheXpathExpressionNode))
#define OrgApacheXpathExpressionNode_

#define RESTRICT_JavaxXmlTransformSourceLocator 1
#define INCLUDE_JavaxXmlTransformSourceLocator 1
#include "javax/xml/transform/SourceLocator.h"

@class JavaLangInteger;

@protocol OrgApacheXpathExpressionNode < JavaxXmlTransformSourceLocator, JavaObject >

- (void)exprSetParentWithOrgApacheXpathExpressionNode:(id<OrgApacheXpathExpressionNode>)n;

- (id<OrgApacheXpathExpressionNode>)exprGetParent;

- (void)exprAddChildWithOrgApacheXpathExpressionNode:(id<OrgApacheXpathExpressionNode>)n
                                             withInt:(jint)i;

- (id<OrgApacheXpathExpressionNode>)exprGetChildWithInt:(jint)i;

- (jint)exprGetNumChildren;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXpathExpressionNode)

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXpathExpressionNode)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXpathExpressionNode")
