//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/junit/build_result/java/org/junit/ClassRule.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitClassRule")
#ifdef RESTRICT_OrgJunitClassRule
#define INCLUDE_ALL_OrgJunitClassRule 0
#else
#define INCLUDE_ALL_OrgJunitClassRule 1
#endif
#undef RESTRICT_OrgJunitClassRule

#if !defined (OrgJunitClassRule_) && (INCLUDE_ALL_OrgJunitClassRule || defined(INCLUDE_OrgJunitClassRule))
#define OrgJunitClassRule_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;

@protocol OrgJunitClassRule < JavaLangAnnotationAnnotation >

@property (readonly) jint order;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface OrgJunitClassRule : NSObject < OrgJunitClassRule > {
 @public
  jint order_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitClassRule)

FOUNDATION_EXPORT id<OrgJunitClassRule> create_OrgJunitClassRule(jint order);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitClassRule)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgJunitClassRule")
