//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xpath/operations/UnaryOperation.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXpathOperationsUnaryOperation")
#ifdef RESTRICT_OrgApacheXpathOperationsUnaryOperation
#define INCLUDE_ALL_OrgApacheXpathOperationsUnaryOperation 0
#else
#define INCLUDE_ALL_OrgApacheXpathOperationsUnaryOperation 1
#endif
#undef RESTRICT_OrgApacheXpathOperationsUnaryOperation

#if !defined (OrgApacheXpathOperationsUnaryOperation_) && (INCLUDE_ALL_OrgApacheXpathOperationsUnaryOperation || defined(INCLUDE_OrgApacheXpathOperationsUnaryOperation))
#define OrgApacheXpathOperationsUnaryOperation_

#define RESTRICT_OrgApacheXpathExpression 1
#define INCLUDE_OrgApacheXpathExpression 1
#include "org/apache/xpath/Expression.h"

#define RESTRICT_OrgApacheXpathExpressionOwner 1
#define INCLUDE_OrgApacheXpathExpressionOwner 1
#include "org/apache/xpath/ExpressionOwner.h"

@class JavaLangBoolean;
@class JavaLangInteger;
@class JavaLangLong;
@class JavaUtilVector;
@class OrgApacheXpathObjectsXObject;
@class OrgApacheXpathXPathContext;
@class OrgApacheXpathXPathVisitor;

@interface OrgApacheXpathOperationsUnaryOperation : OrgApacheXpathExpression < OrgApacheXpathExpressionOwner > {
 @public
  OrgApacheXpathExpression *m_right_;
}

#pragma mark Public

- (instancetype)init;

- (void)callVisitorsWithOrgApacheXpathExpressionOwner:(id<OrgApacheXpathExpressionOwner>)owner
                       withOrgApacheXpathXPathVisitor:(OrgApacheXpathXPathVisitor *)visitor;

- (jboolean)canTraverseOutsideSubtree;

- (jboolean)deepEqualsWithOrgApacheXpathExpression:(OrgApacheXpathExpression *)expr;

- (OrgApacheXpathObjectsXObject *)executeWithOrgApacheXpathXPathContext:(OrgApacheXpathXPathContext *)xctxt;

- (void)fixupVariablesWithJavaUtilVector:(JavaUtilVector *)vars
                                 withInt:(jint)globalsSize;

- (OrgApacheXpathExpression *)getExpression;

- (OrgApacheXpathExpression *)getOperand;

- (OrgApacheXpathObjectsXObject *)operateWithOrgApacheXpathObjectsXObject:(OrgApacheXpathObjectsXObject *)right;

- (void)setExpressionWithOrgApacheXpathExpression:(OrgApacheXpathExpression *)exp;

- (void)setRightWithOrgApacheXpathExpression:(OrgApacheXpathExpression *)r;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXpathOperationsUnaryOperation)

J2OBJC_FIELD_SETTER(OrgApacheXpathOperationsUnaryOperation, m_right_, OrgApacheXpathExpression *)

inline jlong OrgApacheXpathOperationsUnaryOperation_get_serialVersionUID(void);
#define OrgApacheXpathOperationsUnaryOperation_serialVersionUID 6536083808424286166LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXpathOperationsUnaryOperation, serialVersionUID, jlong)

FOUNDATION_EXPORT void OrgApacheXpathOperationsUnaryOperation_init(OrgApacheXpathOperationsUnaryOperation *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXpathOperationsUnaryOperation)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXpathOperationsUnaryOperation")
