//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/testing/mockito/build_result/java/org/mockito/stubbing/VoidAnswer4.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoStubbingVoidAnswer4")
#ifdef RESTRICT_OrgMockitoStubbingVoidAnswer4
#define INCLUDE_ALL_OrgMockitoStubbingVoidAnswer4 0
#else
#define INCLUDE_ALL_OrgMockitoStubbingVoidAnswer4 1
#endif
#undef RESTRICT_OrgMockitoStubbingVoidAnswer4

#if !defined (OrgMockitoStubbingVoidAnswer4_) && (INCLUDE_ALL_OrgMockitoStubbingVoidAnswer4 || defined(INCLUDE_OrgMockitoStubbingVoidAnswer4))
#define OrgMockitoStubbingVoidAnswer4_

@protocol OrgMockitoStubbingVoidAnswer4 < JavaObject >

- (void)answerWithId:(id)argument0
              withId:(id)argument1
              withId:(id)argument2
              withId:(id)argument3;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoStubbingVoidAnswer4)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoStubbingVoidAnswer4)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoStubbingVoidAnswer4")
