//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xalan/transformer/DecimalToRoman.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXalanTransformerDecimalToRoman")
#ifdef RESTRICT_OrgApacheXalanTransformerDecimalToRoman
#define INCLUDE_ALL_OrgApacheXalanTransformerDecimalToRoman 0
#else
#define INCLUDE_ALL_OrgApacheXalanTransformerDecimalToRoman 1
#endif
#undef RESTRICT_OrgApacheXalanTransformerDecimalToRoman

#if !defined (OrgApacheXalanTransformerDecimalToRoman_) && (INCLUDE_ALL_OrgApacheXalanTransformerDecimalToRoman || defined(INCLUDE_OrgApacheXalanTransformerDecimalToRoman))
#define OrgApacheXalanTransformerDecimalToRoman_

@class JavaLangLong;

@interface OrgApacheXalanTransformerDecimalToRoman : NSObject {
 @public
  jlong m_postValue_;
  NSString *m_postLetter_;
  jlong m_preValue_;
  NSString *m_preLetter_;
}

#pragma mark Public

- (instancetype)initWithLong:(jlong)postValue
                withNSString:(NSString *)postLetter
                    withLong:(jlong)preValue
                withNSString:(NSString *)preLetter;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXalanTransformerDecimalToRoman)

J2OBJC_FIELD_SETTER(OrgApacheXalanTransformerDecimalToRoman, m_postLetter_, NSString *)
J2OBJC_FIELD_SETTER(OrgApacheXalanTransformerDecimalToRoman, m_preLetter_, NSString *)

FOUNDATION_EXPORT void OrgApacheXalanTransformerDecimalToRoman_initWithLong_withNSString_withLong_withNSString_(OrgApacheXalanTransformerDecimalToRoman *self, jlong postValue, NSString *postLetter, jlong preValue, NSString *preLetter);

FOUNDATION_EXPORT OrgApacheXalanTransformerDecimalToRoman *new_OrgApacheXalanTransformerDecimalToRoman_initWithLong_withNSString_withLong_withNSString_(jlong postValue, NSString *postLetter, jlong preValue, NSString *preLetter) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXalanTransformerDecimalToRoman *create_OrgApacheXalanTransformerDecimalToRoman_initWithLong_withNSString_withLong_withNSString_(jlong postValue, NSString *postLetter, jlong preValue, NSString *preLetter);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXalanTransformerDecimalToRoman)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXalanTransformerDecimalToRoman")
