//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/testing/mockito/build_result/java/org/mockito/internal/creation/util/MockitoMethodProxy.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalCreationUtilMockitoMethodProxy")
#ifdef RESTRICT_OrgMockitoInternalCreationUtilMockitoMethodProxy
#define INCLUDE_ALL_OrgMockitoInternalCreationUtilMockitoMethodProxy 0
#else
#define INCLUDE_ALL_OrgMockitoInternalCreationUtilMockitoMethodProxy 1
#endif
#undef RESTRICT_OrgMockitoInternalCreationUtilMockitoMethodProxy

#if !defined (OrgMockitoInternalCreationUtilMockitoMethodProxy_) && (INCLUDE_ALL_OrgMockitoInternalCreationUtilMockitoMethodProxy || defined(INCLUDE_OrgMockitoInternalCreationUtilMockitoMethodProxy))
#define OrgMockitoInternalCreationUtilMockitoMethodProxy_

@class IOSObjectArray;

@protocol OrgMockitoInternalCreationUtilMockitoMethodProxy < JavaObject >

- (id)invokeSuperWithId:(id)target
      withNSObjectArray:(IOSObjectArray *)arguments;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalCreationUtilMockitoMethodProxy)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalCreationUtilMockitoMethodProxy)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalCreationUtilMockitoMethodProxy")
