//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/junit/build_result/java/org/junit/runners/model/FrameworkMember.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitRunnersModelFrameworkMember")
#ifdef RESTRICT_OrgJunitRunnersModelFrameworkMember
#define INCLUDE_ALL_OrgJunitRunnersModelFrameworkMember 0
#else
#define INCLUDE_ALL_OrgJunitRunnersModelFrameworkMember 1
#endif
#undef RESTRICT_OrgJunitRunnersModelFrameworkMember

#if !defined (OrgJunitRunnersModelFrameworkMember_) && (INCLUDE_ALL_OrgJunitRunnersModelFrameworkMember || defined(INCLUDE_OrgJunitRunnersModelFrameworkMember))
#define OrgJunitRunnersModelFrameworkMember_

#define RESTRICT_OrgJunitRunnersModelAnnotatable 1
#define INCLUDE_OrgJunitRunnersModelAnnotatable 1
#include "org/junit/runners/model/Annotatable.h"

@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;
@protocol JavaUtilList;

@interface OrgJunitRunnersModelFrameworkMember : NSObject < OrgJunitRunnersModelAnnotatable >

#pragma mark Public

- (instancetype)init;

- (IOSClass *)getDeclaringClass;

- (NSString *)getName;

- (IOSClass *)getType;

- (jboolean)isPublic;

- (jboolean)isStatic;

#pragma mark Protected

- (jint)getModifiers;

#pragma mark Package-Private

- (OrgJunitRunnersModelFrameworkMember *)handlePossibleBridgeMethodWithJavaUtilList:(id<JavaUtilList>)members;

- (jboolean)isBridgeMethod;

- (jboolean)isShadowedByWithOrgJunitRunnersModelFrameworkMember:(OrgJunitRunnersModelFrameworkMember *)otherMember;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRunnersModelFrameworkMember)

FOUNDATION_EXPORT void OrgJunitRunnersModelFrameworkMember_init(OrgJunitRunnersModelFrameworkMember *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRunnersModelFrameworkMember)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgJunitRunnersModelFrameworkMember")
