//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/build_result/java/com/google/errorprone/annotations/CanIgnoreReturnValue.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleErrorproneAnnotationsCanIgnoreReturnValue")
#ifdef RESTRICT_ComGoogleErrorproneAnnotationsCanIgnoreReturnValue
#define INCLUDE_ALL_ComGoogleErrorproneAnnotationsCanIgnoreReturnValue 0
#else
#define INCLUDE_ALL_ComGoogleErrorproneAnnotationsCanIgnoreReturnValue 1
#endif
#undef RESTRICT_ComGoogleErrorproneAnnotationsCanIgnoreReturnValue

#if !defined (ComGoogleErrorproneAnnotationsCanIgnoreReturnValue_) && (INCLUDE_ALL_ComGoogleErrorproneAnnotationsCanIgnoreReturnValue || defined(INCLUDE_ComGoogleErrorproneAnnotationsCanIgnoreReturnValue))
#define ComGoogleErrorproneAnnotationsCanIgnoreReturnValue_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;

@protocol ComGoogleErrorproneAnnotationsCanIgnoreReturnValue < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface ComGoogleErrorproneAnnotationsCanIgnoreReturnValue : NSObject < ComGoogleErrorproneAnnotationsCanIgnoreReturnValue >

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleErrorproneAnnotationsCanIgnoreReturnValue)

FOUNDATION_EXPORT id<ComGoogleErrorproneAnnotationsCanIgnoreReturnValue> create_ComGoogleErrorproneAnnotationsCanIgnoreReturnValue(void);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleErrorproneAnnotationsCanIgnoreReturnValue)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleErrorproneAnnotationsCanIgnoreReturnValue")
