//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/build_result/java/com/google/errorprone/annotations/DoNotCall.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleErrorproneAnnotationsDoNotCall")
#ifdef RESTRICT_ComGoogleErrorproneAnnotationsDoNotCall
#define INCLUDE_ALL_ComGoogleErrorproneAnnotationsDoNotCall 0
#else
#define INCLUDE_ALL_ComGoogleErrorproneAnnotationsDoNotCall 1
#endif
#undef RESTRICT_ComGoogleErrorproneAnnotationsDoNotCall

#if !defined (ComGoogleErrorproneAnnotationsDoNotCall_) && (INCLUDE_ALL_ComGoogleErrorproneAnnotationsDoNotCall || defined(INCLUDE_ComGoogleErrorproneAnnotationsDoNotCall))
#define ComGoogleErrorproneAnnotationsDoNotCall_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;

@protocol ComGoogleErrorproneAnnotationsDoNotCall < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface ComGoogleErrorproneAnnotationsDoNotCall : NSObject < ComGoogleErrorproneAnnotationsDoNotCall > {
 @public
  NSString *value_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleErrorproneAnnotationsDoNotCall)

FOUNDATION_EXPORT id<ComGoogleErrorproneAnnotationsDoNotCall> create_ComGoogleErrorproneAnnotationsDoNotCall(NSString *value);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleErrorproneAnnotationsDoNotCall)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleErrorproneAnnotationsDoNotCall")
