//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xml/serializer/DOM3Serializer.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXmlSerializerDOM3Serializer")
#ifdef RESTRICT_OrgApacheXmlSerializerDOM3Serializer
#define INCLUDE_ALL_OrgApacheXmlSerializerDOM3Serializer 0
#else
#define INCLUDE_ALL_OrgApacheXmlSerializerDOM3Serializer 1
#endif
#undef RESTRICT_OrgApacheXmlSerializerDOM3Serializer

#if !defined (OrgApacheXmlSerializerDOM3Serializer_) && (INCLUDE_ALL_OrgApacheXmlSerializerDOM3Serializer || defined(INCLUDE_OrgApacheXmlSerializerDOM3Serializer))
#define OrgApacheXmlSerializerDOM3Serializer_

@class IOSCharArray;
@protocol OrgW3cDomDOMErrorHandler;
@protocol OrgW3cDomLsLSSerializerFilter;
@protocol OrgW3cDomNode;

@protocol OrgApacheXmlSerializerDOM3Serializer < JavaObject >

- (void)serializeDOM3WithOrgW3cDomNode:(id<OrgW3cDomNode>)node;

- (void)setErrorHandlerWithOrgW3cDomDOMErrorHandler:(id<OrgW3cDomDOMErrorHandler>)handler;

- (id<OrgW3cDomDOMErrorHandler>)getErrorHandler;

- (void)setNodeFilterWithOrgW3cDomLsLSSerializerFilter:(id<OrgW3cDomLsLSSerializerFilter>)filter;

- (id<OrgW3cDomLsLSSerializerFilter>)getNodeFilter;

- (void)setNewLineWithCharArray:(IOSCharArray *)newLine;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXmlSerializerDOM3Serializer)

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXmlSerializerDOM3Serializer)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXmlSerializerDOM3Serializer")
