//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xml/serializer/utils/SerializerMessages_sk.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXmlSerializerUtilsSerializerMessages_sk")
#ifdef RESTRICT_OrgApacheXmlSerializerUtilsSerializerMessages_sk
#define INCLUDE_ALL_OrgApacheXmlSerializerUtilsSerializerMessages_sk 0
#else
#define INCLUDE_ALL_OrgApacheXmlSerializerUtilsSerializerMessages_sk 1
#endif
#undef RESTRICT_OrgApacheXmlSerializerUtilsSerializerMessages_sk

#if !defined (OrgApacheXmlSerializerUtilsSerializerMessages_sk_) && (INCLUDE_ALL_OrgApacheXmlSerializerUtilsSerializerMessages_sk || defined(INCLUDE_OrgApacheXmlSerializerUtilsSerializerMessages_sk))
#define OrgApacheXmlSerializerUtilsSerializerMessages_sk_

#define RESTRICT_JavaUtilListResourceBundle 1
#define INCLUDE_JavaUtilListResourceBundle 1
#include "java/util/ListResourceBundle.h"

@class IOSObjectArray;

@interface OrgApacheXmlSerializerUtilsSerializerMessages_sk : JavaUtilListResourceBundle

#pragma mark Public

- (instancetype)init;

- (IOSObjectArray *)getContents;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXmlSerializerUtilsSerializerMessages_sk)

FOUNDATION_EXPORT void OrgApacheXmlSerializerUtilsSerializerMessages_sk_init(OrgApacheXmlSerializerUtilsSerializerMessages_sk *self);

FOUNDATION_EXPORT OrgApacheXmlSerializerUtilsSerializerMessages_sk *new_OrgApacheXmlSerializerUtilsSerializerMessages_sk_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXmlSerializerUtilsSerializerMessages_sk *create_OrgApacheXmlSerializerUtilsSerializerMessages_sk_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXmlSerializerUtilsSerializerMessages_sk)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXmlSerializerUtilsSerializerMessages_sk")
