//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/build_result/java/com/google/common/base/NullnessCasts.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonBaseNullnessCasts")
#ifdef RESTRICT_ComGoogleCommonBaseNullnessCasts
#define INCLUDE_ALL_ComGoogleCommonBaseNullnessCasts 0
#else
#define INCLUDE_ALL_ComGoogleCommonBaseNullnessCasts 1
#endif
#undef RESTRICT_ComGoogleCommonBaseNullnessCasts

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonBaseNullnessCasts_) && (INCLUDE_ALL_ComGoogleCommonBaseNullnessCasts || defined(INCLUDE_ComGoogleCommonBaseNullnessCasts))
#define ComGoogleCommonBaseNullnessCasts_

@interface ComGoogleCommonBaseNullnessCasts : NSObject

#pragma mark Package-Private

+ (id)uncheckedCastNullableTToTWithId:(id)t;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonBaseNullnessCasts)

FOUNDATION_EXPORT id ComGoogleCommonBaseNullnessCasts_uncheckedCastNullableTToTWithId_(id t);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonBaseNullnessCasts)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonBaseNullnessCasts")
