//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/android/build_result/java/com/google/common/graph/AbstractGraph.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonGraphAbstractGraph")
#ifdef RESTRICT_ComGoogleCommonGraphAbstractGraph
#define INCLUDE_ALL_ComGoogleCommonGraphAbstractGraph 0
#else
#define INCLUDE_ALL_ComGoogleCommonGraphAbstractGraph 1
#endif
#undef RESTRICT_ComGoogleCommonGraphAbstractGraph

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonGraphAbstractGraph_) && (INCLUDE_ALL_ComGoogleCommonGraphAbstractGraph || defined(INCLUDE_ComGoogleCommonGraphAbstractGraph))
#define ComGoogleCommonGraphAbstractGraph_

#define RESTRICT_ComGoogleCommonGraphAbstractBaseGraph 1
#define INCLUDE_ComGoogleCommonGraphAbstractBaseGraph 1
#include "com/google/common/graph/AbstractBaseGraph.h"

#define RESTRICT_ComGoogleCommonGraphGraph 1
#define INCLUDE_ComGoogleCommonGraphGraph 1
#include "com/google/common/graph/Graph.h"

@class JavaLangBoolean;
@class JavaLangInteger;

@interface ComGoogleCommonGraphAbstractGraph : ComGoogleCommonGraphAbstractBaseGraph < ComGoogleCommonGraphGraph >

#pragma mark Public

- (instancetype)init;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

- (NSString *)description;

// Disallowed inherited constructors, do not use.

- (instancetype)initPackagePrivate NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonGraphAbstractGraph)

FOUNDATION_EXPORT void ComGoogleCommonGraphAbstractGraph_init(ComGoogleCommonGraphAbstractGraph *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonGraphAbstractGraph)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonGraphAbstractGraph")
