//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/android/build_result/java/com/google/common/collect/HashMultimap.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonCollectHashMultimap")
#ifdef RESTRICT_ComGoogleCommonCollectHashMultimap
#define INCLUDE_ALL_ComGoogleCommonCollectHashMultimap 0
#else
#define INCLUDE_ALL_ComGoogleCommonCollectHashMultimap 1
#endif
#undef RESTRICT_ComGoogleCommonCollectHashMultimap

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonCollectHashMultimap_) && (INCLUDE_ALL_ComGoogleCommonCollectHashMultimap || defined(INCLUDE_ComGoogleCommonCollectHashMultimap))
#define ComGoogleCommonCollectHashMultimap_

#define RESTRICT_ComGoogleCommonCollectHashMultimapGwtSerializationDependencies 1
#define INCLUDE_ComGoogleCommonCollectHashMultimapGwtSerializationDependencies 1
#include "com/google/common/collect/HashMultimapGwtSerializationDependencies.h"

@class JavaLangInteger;
@protocol ComGoogleCommonCollectMultimap;
@protocol JavaUtilMap;
@protocol JavaUtilSet;

@interface ComGoogleCommonCollectHashMultimap : ComGoogleCommonCollectHashMultimapGwtSerializationDependencies {
 @public
  jint expectedValuesPerKey_;
}

#pragma mark Public

+ (ComGoogleCommonCollectHashMultimap *)create;

+ (ComGoogleCommonCollectHashMultimap *)createWithInt:(jint)expectedKeys
                                              withInt:(jint)expectedValuesPerKey;

+ (ComGoogleCommonCollectHashMultimap *)createWithComGoogleCommonCollectMultimap:(id<ComGoogleCommonCollectMultimap>)multimap;

#pragma mark Package-Private

- (id<JavaUtilSet>)createCollection;

// Disallowed inherited constructors, do not use.

- (instancetype)initPackagePrivateWithJavaUtilMap:(id<JavaUtilMap>)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonCollectHashMultimap)

FOUNDATION_EXPORT ComGoogleCommonCollectHashMultimap *ComGoogleCommonCollectHashMultimap_create(void);

FOUNDATION_EXPORT ComGoogleCommonCollectHashMultimap *ComGoogleCommonCollectHashMultimap_createWithInt_withInt_(jint expectedKeys, jint expectedValuesPerKey);

FOUNDATION_EXPORT ComGoogleCommonCollectHashMultimap *ComGoogleCommonCollectHashMultimap_createWithComGoogleCommonCollectMultimap_(id<ComGoogleCommonCollectMultimap> multimap);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonCollectHashMultimap)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonCollectHashMultimap")
