//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/android/build_result/java/org/checkerframework/framework/qual/MonotonicQualifier.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgCheckerframeworkFrameworkQualMonotonicQualifier")
#ifdef RESTRICT_OrgCheckerframeworkFrameworkQualMonotonicQualifier
#define INCLUDE_ALL_OrgCheckerframeworkFrameworkQualMonotonicQualifier 0
#else
#define INCLUDE_ALL_OrgCheckerframeworkFrameworkQualMonotonicQualifier 1
#endif
#undef RESTRICT_OrgCheckerframeworkFrameworkQualMonotonicQualifier

#if !defined (OrgCheckerframeworkFrameworkQualMonotonicQualifier_) && (INCLUDE_ALL_OrgCheckerframeworkFrameworkQualMonotonicQualifier || defined(INCLUDE_OrgCheckerframeworkFrameworkQualMonotonicQualifier))
#define OrgCheckerframeworkFrameworkQualMonotonicQualifier_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;

@protocol OrgCheckerframeworkFrameworkQualMonotonicQualifier < JavaLangAnnotationAnnotation >

@property (readonly) IOSClass *value;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface OrgCheckerframeworkFrameworkQualMonotonicQualifier : NSObject < OrgCheckerframeworkFrameworkQualMonotonicQualifier > {
 @public
  IOSClass *value_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(OrgCheckerframeworkFrameworkQualMonotonicQualifier)

FOUNDATION_EXPORT id<OrgCheckerframeworkFrameworkQualMonotonicQualifier> create_OrgCheckerframeworkFrameworkQualMonotonicQualifier(IOSClass *value);

J2OBJC_TYPE_LITERAL_HEADER(OrgCheckerframeworkFrameworkQualMonotonicQualifier)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgCheckerframeworkFrameworkQualMonotonicQualifier")
