//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/android/build_result/java/com/google/common/io/ByteArrayDataInput.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonIoByteArrayDataInput")
#ifdef RESTRICT_ComGoogleCommonIoByteArrayDataInput
#define INCLUDE_ALL_ComGoogleCommonIoByteArrayDataInput 0
#else
#define INCLUDE_ALL_ComGoogleCommonIoByteArrayDataInput 1
#endif
#undef RESTRICT_ComGoogleCommonIoByteArrayDataInput

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonIoByteArrayDataInput_) && (INCLUDE_ALL_ComGoogleCommonIoByteArrayDataInput || defined(INCLUDE_ComGoogleCommonIoByteArrayDataInput))
#define ComGoogleCommonIoByteArrayDataInput_

#define RESTRICT_JavaIoDataInput 1
#define INCLUDE_JavaIoDataInput 1
#include "java/io/DataInput.h"

@class IOSByteArray;
@class JavaLangBoolean;
@class JavaLangByte;
@class JavaLangCharacter;
@class JavaLangDouble;
@class JavaLangFloat;
@class JavaLangInteger;
@class JavaLangLong;
@class JavaLangShort;

@protocol ComGoogleCommonIoByteArrayDataInput < JavaIoDataInput, JavaObject >

- (void)readFullyWithByteArray:(IOSByteArray *)b;

- (void)readFullyWithByteArray:(IOSByteArray *)b
                       withInt:(jint)off
                       withInt:(jint)len;

- (jint)skipBytesWithInt:(jint)n;

- (jboolean)readBoolean;

- (jbyte)readByte;

- (jint)readUnsignedByte;

- (jshort)readShort;

- (jint)readUnsignedShort;

- (jchar)readChar;

- (jint)readInt;

- (jlong)readLong;

- (jfloat)readFloat;

- (jdouble)readDouble;

- (NSString *)readLine;

- (NSString *)readUTF;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonIoByteArrayDataInput)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonIoByteArrayDataInput)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonIoByteArrayDataInput")
