//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xml/dtm/ref/IncrementalSAXSource.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXmlDtmRefIncrementalSAXSource")
#ifdef RESTRICT_OrgApacheXmlDtmRefIncrementalSAXSource
#define INCLUDE_ALL_OrgApacheXmlDtmRefIncrementalSAXSource 0
#else
#define INCLUDE_ALL_OrgApacheXmlDtmRefIncrementalSAXSource 1
#endif
#undef RESTRICT_OrgApacheXmlDtmRefIncrementalSAXSource

#if !defined (OrgApacheXmlDtmRefIncrementalSAXSource_) && (INCLUDE_ALL_OrgApacheXmlDtmRefIncrementalSAXSource || defined(INCLUDE_OrgApacheXmlDtmRefIncrementalSAXSource))
#define OrgApacheXmlDtmRefIncrementalSAXSource_

@class JavaLangBoolean;
@class OrgXmlSaxInputSource;
@protocol OrgXmlSaxContentHandler;
@protocol OrgXmlSaxDTDHandler;
@protocol OrgXmlSaxExtLexicalHandler;

@protocol OrgApacheXmlDtmRefIncrementalSAXSource < JavaObject >

- (void)setContentHandlerWithOrgXmlSaxContentHandler:(id<OrgXmlSaxContentHandler>)handler;

- (void)setLexicalHandlerWithOrgXmlSaxExtLexicalHandler:(id<OrgXmlSaxExtLexicalHandler>)handler;

- (void)setDTDHandlerWithOrgXmlSaxDTDHandler:(id<OrgXmlSaxDTDHandler>)handler;

- (id)deliverMoreNodesWithBoolean:(jboolean)parsemore;

- (void)startParseWithOrgXmlSaxInputSource:(OrgXmlSaxInputSource *)source;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXmlDtmRefIncrementalSAXSource)

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXmlDtmRefIncrementalSAXSource)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXmlDtmRefIncrementalSAXSource")
