//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/testing/mockito/build_result/java/org/mockito/exceptions/misusing/UnnecessaryStubbingException.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoExceptionsMisusingUnnecessaryStubbingException")
#ifdef RESTRICT_OrgMockitoExceptionsMisusingUnnecessaryStubbingException
#define INCLUDE_ALL_OrgMockitoExceptionsMisusingUnnecessaryStubbingException 0
#else
#define INCLUDE_ALL_OrgMockitoExceptionsMisusingUnnecessaryStubbingException 1
#endif
#undef RESTRICT_OrgMockitoExceptionsMisusingUnnecessaryStubbingException

#if !defined (OrgMockitoExceptionsMisusingUnnecessaryStubbingException_) && (INCLUDE_ALL_OrgMockitoExceptionsMisusingUnnecessaryStubbingException || defined(INCLUDE_OrgMockitoExceptionsMisusingUnnecessaryStubbingException))
#define OrgMockitoExceptionsMisusingUnnecessaryStubbingException_

#define RESTRICT_OrgMockitoExceptionsBaseMockitoException 1
#define INCLUDE_OrgMockitoExceptionsBaseMockitoException 1
#include "org/mockito/exceptions/base/MockitoException.h"

@class JavaLangThrowable;

@interface OrgMockitoExceptionsMisusingUnnecessaryStubbingException : OrgMockitoExceptionsBaseMockitoException

#pragma mark Public

- (instancetype)initWithNSString:(NSString *)message;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoExceptionsMisusingUnnecessaryStubbingException)

FOUNDATION_EXPORT void OrgMockitoExceptionsMisusingUnnecessaryStubbingException_initWithNSString_(OrgMockitoExceptionsMisusingUnnecessaryStubbingException *self, NSString *message);

FOUNDATION_EXPORT OrgMockitoExceptionsMisusingUnnecessaryStubbingException *new_OrgMockitoExceptionsMisusingUnnecessaryStubbingException_initWithNSString_(NSString *message) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoExceptionsMisusingUnnecessaryStubbingException *create_OrgMockitoExceptionsMisusingUnnecessaryStubbingException_initWithNSString_(NSString *message);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoExceptionsMisusingUnnecessaryStubbingException)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoExceptionsMisusingUnnecessaryStubbingException")
