//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xalan/processor/ProcessorNamespaceAlias.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXalanProcessorProcessorNamespaceAlias")
#ifdef RESTRICT_OrgApacheXalanProcessorProcessorNamespaceAlias
#define INCLUDE_ALL_OrgApacheXalanProcessorProcessorNamespaceAlias 0
#else
#define INCLUDE_ALL_OrgApacheXalanProcessorProcessorNamespaceAlias 1
#endif
#undef RESTRICT_OrgApacheXalanProcessorProcessorNamespaceAlias

#if !defined (OrgApacheXalanProcessorProcessorNamespaceAlias_) && (INCLUDE_ALL_OrgApacheXalanProcessorProcessorNamespaceAlias || defined(INCLUDE_OrgApacheXalanProcessorProcessorNamespaceAlias))
#define OrgApacheXalanProcessorProcessorNamespaceAlias_

#define RESTRICT_OrgApacheXalanProcessorXSLTElementProcessor 1
#define INCLUDE_OrgApacheXalanProcessorXSLTElementProcessor 1
#include "org/apache/xalan/processor/XSLTElementProcessor.h"

@class JavaLangLong;
@class OrgApacheXalanProcessorStylesheetHandler;
@protocol OrgXmlSaxAttributes;

@interface OrgApacheXalanProcessorProcessorNamespaceAlias : OrgApacheXalanProcessorXSLTElementProcessor

#pragma mark Public

- (void)startElementWithOrgApacheXalanProcessorStylesheetHandler:(OrgApacheXalanProcessorStylesheetHandler *)handler
                                                    withNSString:(NSString *)uri
                                                    withNSString:(NSString *)localName
                                                    withNSString:(NSString *)rawName
                                         withOrgXmlSaxAttributes:(id<OrgXmlSaxAttributes>)attributes;

#pragma mark Package-Private

- (instancetype)initPackagePrivate;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXalanProcessorProcessorNamespaceAlias)

inline jlong OrgApacheXalanProcessorProcessorNamespaceAlias_get_serialVersionUID(void);
#define OrgApacheXalanProcessorProcessorNamespaceAlias_serialVersionUID -6309867839007018964LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXalanProcessorProcessorNamespaceAlias, serialVersionUID, jlong)

FOUNDATION_EXPORT void OrgApacheXalanProcessorProcessorNamespaceAlias_initPackagePrivate(OrgApacheXalanProcessorProcessorNamespaceAlias *self);

FOUNDATION_EXPORT OrgApacheXalanProcessorProcessorNamespaceAlias *new_OrgApacheXalanProcessorProcessorNamespaceAlias_initPackagePrivate(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXalanProcessorProcessorNamespaceAlias *create_OrgApacheXalanProcessorProcessorNamespaceAlias_initPackagePrivate(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXalanProcessorProcessorNamespaceAlias)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXalanProcessorProcessorNamespaceAlias")
