//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xalan/processor/ProcessorKey.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXalanProcessorProcessorKey")
#ifdef RESTRICT_OrgApacheXalanProcessorProcessorKey
#define INCLUDE_ALL_OrgApacheXalanProcessorProcessorKey 0
#else
#define INCLUDE_ALL_OrgApacheXalanProcessorProcessorKey 1
#endif
#undef RESTRICT_OrgApacheXalanProcessorProcessorKey

#if !defined (OrgApacheXalanProcessorProcessorKey_) && (INCLUDE_ALL_OrgApacheXalanProcessorProcessorKey || defined(INCLUDE_OrgApacheXalanProcessorProcessorKey))
#define OrgApacheXalanProcessorProcessorKey_

#define RESTRICT_OrgApacheXalanProcessorXSLTElementProcessor 1
#define INCLUDE_OrgApacheXalanProcessorXSLTElementProcessor 1
#include "org/apache/xalan/processor/XSLTElementProcessor.h"

@class JavaLangLong;
@class OrgApacheXalanProcessorStylesheetHandler;
@class OrgApacheXalanTemplatesElemTemplateElement;
@protocol OrgXmlSaxAttributes;

@interface OrgApacheXalanProcessorProcessorKey : OrgApacheXalanProcessorXSLTElementProcessor

#pragma mark Public

- (void)startElementWithOrgApacheXalanProcessorStylesheetHandler:(OrgApacheXalanProcessorStylesheetHandler *)handler
                                                    withNSString:(NSString *)uri
                                                    withNSString:(NSString *)localName
                                                    withNSString:(NSString *)rawName
                                         withOrgXmlSaxAttributes:(id<OrgXmlSaxAttributes>)attributes;

#pragma mark Package-Private

- (instancetype)initPackagePrivate;

- (void)setPropertiesFromAttributesWithOrgApacheXalanProcessorStylesheetHandler:(OrgApacheXalanProcessorStylesheetHandler *)handler
                                                                   withNSString:(NSString *)rawName
                                                        withOrgXmlSaxAttributes:(id<OrgXmlSaxAttributes>)attributes
                                 withOrgApacheXalanTemplatesElemTemplateElement:(OrgApacheXalanTemplatesElemTemplateElement *)target;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXalanProcessorProcessorKey)

inline jlong OrgApacheXalanProcessorProcessorKey_get_serialVersionUID(void);
#define OrgApacheXalanProcessorProcessorKey_serialVersionUID 4285205417566822979LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXalanProcessorProcessorKey, serialVersionUID, jlong)

FOUNDATION_EXPORT void OrgApacheXalanProcessorProcessorKey_initPackagePrivate(OrgApacheXalanProcessorProcessorKey *self);

FOUNDATION_EXPORT OrgApacheXalanProcessorProcessorKey *new_OrgApacheXalanProcessorProcessorKey_initPackagePrivate(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXalanProcessorProcessorKey *create_OrgApacheXalanProcessorProcessorKey_initPackagePrivate(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXalanProcessorProcessorKey)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXalanProcessorProcessorKey")
