//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xalan/processor/TransformerFactoryImpl.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXalanProcessorTransformerFactoryImpl")
#ifdef RESTRICT_OrgApacheXalanProcessorTransformerFactoryImpl
#define INCLUDE_ALL_OrgApacheXalanProcessorTransformerFactoryImpl 0
#else
#define INCLUDE_ALL_OrgApacheXalanProcessorTransformerFactoryImpl 1
#endif
#undef RESTRICT_OrgApacheXalanProcessorTransformerFactoryImpl

#if !defined (OrgApacheXalanProcessorTransformerFactoryImpl_) && (INCLUDE_ALL_OrgApacheXalanProcessorTransformerFactoryImpl || defined(INCLUDE_OrgApacheXalanProcessorTransformerFactoryImpl))
#define OrgApacheXalanProcessorTransformerFactoryImpl_

#define RESTRICT_JavaxXmlTransformSaxSAXTransformerFactory 1
#define INCLUDE_JavaxXmlTransformSaxSAXTransformerFactory 1
#include "javax/xml/transform/sax/SAXTransformerFactory.h"

@class JavaLangBoolean;
@class JavaxXmlTransformTransformer;
@protocol JavaxXmlTransformErrorListener;
@protocol JavaxXmlTransformSaxTemplatesHandler;
@protocol JavaxXmlTransformSaxTransformerHandler;
@protocol JavaxXmlTransformSource;
@protocol JavaxXmlTransformTemplates;
@protocol JavaxXmlTransformURIResolver;
@protocol OrgW3cDomNode;
@protocol OrgXmlSaxXMLFilter;

@interface OrgApacheXalanProcessorTransformerFactoryImpl : JavaxXmlTransformSaxSAXTransformerFactory {
 @public
  id<JavaxXmlTransformURIResolver> m_uriResolver_;
}

#pragma mark Public

- (instancetype)init;

- (id<JavaxXmlTransformSource>)getAssociatedStylesheetWithJavaxXmlTransformSource:(id<JavaxXmlTransformSource>)source
                                                                     withNSString:(NSString *)media
                                                                     withNSString:(NSString *)title
                                                                     withNSString:(NSString *)charset;

- (id)getAttributeWithNSString:(NSString *)name;

- (id<JavaxXmlTransformErrorListener>)getErrorListener;

- (jboolean)getFeatureWithNSString:(NSString *)name;

- (id<JavaxXmlTransformURIResolver>)getURIResolver;

- (jboolean)isSecureProcessing;

- (id<JavaxXmlTransformTemplates>)newTemplatesWithJavaxXmlTransformSource:(id<JavaxXmlTransformSource>)source OBJC_METHOD_FAMILY_NONE;

- (id<JavaxXmlTransformSaxTemplatesHandler>)newTemplatesHandler OBJC_METHOD_FAMILY_NONE;

- (JavaxXmlTransformTransformer *)newTransformer OBJC_METHOD_FAMILY_NONE;

- (JavaxXmlTransformTransformer *)newTransformerWithJavaxXmlTransformSource:(id<JavaxXmlTransformSource>)source OBJC_METHOD_FAMILY_NONE;

- (id<JavaxXmlTransformSaxTransformerHandler>)newTransformerHandler OBJC_METHOD_FAMILY_NONE;

- (id<JavaxXmlTransformSaxTransformerHandler>)newTransformerHandlerWithJavaxXmlTransformSource:(id<JavaxXmlTransformSource>)src OBJC_METHOD_FAMILY_NONE;

- (id<JavaxXmlTransformSaxTransformerHandler>)newTransformerHandlerWithJavaxXmlTransformTemplates:(id<JavaxXmlTransformTemplates>)templates OBJC_METHOD_FAMILY_NONE;

- (id<OrgXmlSaxXMLFilter>)newXMLFilterWithJavaxXmlTransformSource:(id<JavaxXmlTransformSource>)src OBJC_METHOD_FAMILY_NONE;

- (id<OrgXmlSaxXMLFilter>)newXMLFilterWithJavaxXmlTransformTemplates:(id<JavaxXmlTransformTemplates>)templates OBJC_METHOD_FAMILY_NONE;

- (id<JavaxXmlTransformTemplates>)processFromNodeWithOrgW3cDomNode:(id<OrgW3cDomNode>)node;

- (void)setAttributeWithNSString:(NSString *)name
                          withId:(id)value;

- (void)setErrorListenerWithJavaxXmlTransformErrorListener:(id<JavaxXmlTransformErrorListener>)listener;

- (void)setFeatureWithNSString:(NSString *)name
                   withBoolean:(jboolean)value;

- (void)setURIResolverWithJavaxXmlTransformURIResolver:(id<JavaxXmlTransformURIResolver>)resolver;

#pragma mark Package-Private

- (NSString *)getDOMsystemID;

- (id<JavaxXmlTransformTemplates>)processFromNodeWithOrgW3cDomNode:(id<OrgW3cDomNode>)node
                                                      withNSString:(NSString *)systemID;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXalanProcessorTransformerFactoryImpl)

J2OBJC_FIELD_SETTER(OrgApacheXalanProcessorTransformerFactoryImpl, m_uriResolver_, id<JavaxXmlTransformURIResolver>)

inline NSString *OrgApacheXalanProcessorTransformerFactoryImpl_get_XSLT_PROPERTIES(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgApacheXalanProcessorTransformerFactoryImpl_XSLT_PROPERTIES;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgApacheXalanProcessorTransformerFactoryImpl, XSLT_PROPERTIES, NSString *)

inline NSString *OrgApacheXalanProcessorTransformerFactoryImpl_get_FEATURE_INCREMENTAL(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgApacheXalanProcessorTransformerFactoryImpl_FEATURE_INCREMENTAL;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgApacheXalanProcessorTransformerFactoryImpl, FEATURE_INCREMENTAL, NSString *)

inline NSString *OrgApacheXalanProcessorTransformerFactoryImpl_get_FEATURE_OPTIMIZE(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgApacheXalanProcessorTransformerFactoryImpl_FEATURE_OPTIMIZE;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgApacheXalanProcessorTransformerFactoryImpl, FEATURE_OPTIMIZE, NSString *)

inline NSString *OrgApacheXalanProcessorTransformerFactoryImpl_get_FEATURE_SOURCE_LOCATION(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgApacheXalanProcessorTransformerFactoryImpl_FEATURE_SOURCE_LOCATION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgApacheXalanProcessorTransformerFactoryImpl, FEATURE_SOURCE_LOCATION, NSString *)

FOUNDATION_EXPORT void OrgApacheXalanProcessorTransformerFactoryImpl_init(OrgApacheXalanProcessorTransformerFactoryImpl *self);

FOUNDATION_EXPORT OrgApacheXalanProcessorTransformerFactoryImpl *new_OrgApacheXalanProcessorTransformerFactoryImpl_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXalanProcessorTransformerFactoryImpl *create_OrgApacheXalanProcessorTransformerFactoryImpl_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXalanProcessorTransformerFactoryImpl)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXalanProcessorTransformerFactoryImpl")
