//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/build_result/java/com/google/common/graph/ElementTypesAreNonnullByDefault.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonGraphElementTypesAreNonnullByDefault")
#ifdef RESTRICT_ComGoogleCommonGraphElementTypesAreNonnullByDefault
#define INCLUDE_ALL_ComGoogleCommonGraphElementTypesAreNonnullByDefault 0
#else
#define INCLUDE_ALL_ComGoogleCommonGraphElementTypesAreNonnullByDefault 1
#endif
#undef RESTRICT_ComGoogleCommonGraphElementTypesAreNonnullByDefault

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonGraphElementTypesAreNonnullByDefault_) && (INCLUDE_ALL_ComGoogleCommonGraphElementTypesAreNonnullByDefault || defined(INCLUDE_ComGoogleCommonGraphElementTypesAreNonnullByDefault))
#define ComGoogleCommonGraphElementTypesAreNonnullByDefault_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;

@protocol ComGoogleCommonGraphElementTypesAreNonnullByDefault < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface ComGoogleCommonGraphElementTypesAreNonnullByDefault : NSObject < ComGoogleCommonGraphElementTypesAreNonnullByDefault >

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonGraphElementTypesAreNonnullByDefault)

FOUNDATION_EXPORT id<ComGoogleCommonGraphElementTypesAreNonnullByDefault> create_ComGoogleCommonGraphElementTypesAreNonnullByDefault(void);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonGraphElementTypesAreNonnullByDefault)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonGraphElementTypesAreNonnullByDefault")
