//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/build_result/java/com/google/common/graph/NetworkBuilder.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonGraphNetworkBuilder")
#ifdef RESTRICT_ComGoogleCommonGraphNetworkBuilder
#define INCLUDE_ALL_ComGoogleCommonGraphNetworkBuilder 0
#else
#define INCLUDE_ALL_ComGoogleCommonGraphNetworkBuilder 1
#endif
#undef RESTRICT_ComGoogleCommonGraphNetworkBuilder

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonGraphNetworkBuilder_) && (INCLUDE_ALL_ComGoogleCommonGraphNetworkBuilder || defined(INCLUDE_ComGoogleCommonGraphNetworkBuilder))
#define ComGoogleCommonGraphNetworkBuilder_

#define RESTRICT_ComGoogleCommonGraphAbstractGraphBuilder 1
#define INCLUDE_ComGoogleCommonGraphAbstractGraphBuilder 1
#include "com/google/common/graph/AbstractGraphBuilder.h"

@class ComGoogleCommonBaseOptional;
@class ComGoogleCommonGraphElementOrder;
@class ComGoogleCommonGraphImmutableNetwork_Builder;
@class JavaLangBoolean;
@class JavaLangInteger;
@protocol ComGoogleCommonGraphMutableNetwork;
@protocol ComGoogleCommonGraphNetwork;

@interface ComGoogleCommonGraphNetworkBuilder : ComGoogleCommonGraphAbstractGraphBuilder {
 @public
  jboolean allowsParallelEdges_;
  ComGoogleCommonGraphElementOrder *edgeOrder_;
  ComGoogleCommonBaseOptional *expectedEdgeCount_;
}

#pragma mark Public

- (ComGoogleCommonGraphNetworkBuilder *)allowsParallelEdgesWithBoolean:(jboolean)allowsParallelEdges;

- (ComGoogleCommonGraphNetworkBuilder *)allowsSelfLoopsWithBoolean:(jboolean)allowsSelfLoops;

- (id<ComGoogleCommonGraphMutableNetwork>)build;

+ (ComGoogleCommonGraphNetworkBuilder *)directed;

- (ComGoogleCommonGraphNetworkBuilder *)edgeOrderWithComGoogleCommonGraphElementOrder:(ComGoogleCommonGraphElementOrder *)edgeOrder;

- (ComGoogleCommonGraphNetworkBuilder *)expectedEdgeCountWithInt:(jint)expectedEdgeCount;

- (ComGoogleCommonGraphNetworkBuilder *)expectedNodeCountWithInt:(jint)expectedNodeCount;

+ (ComGoogleCommonGraphNetworkBuilder *)fromWithComGoogleCommonGraphNetwork:(id<ComGoogleCommonGraphNetwork>)network;

- (ComGoogleCommonGraphImmutableNetwork_Builder *)immutable;

- (ComGoogleCommonGraphNetworkBuilder *)nodeOrderWithComGoogleCommonGraphElementOrder:(ComGoogleCommonGraphElementOrder *)nodeOrder;

+ (ComGoogleCommonGraphNetworkBuilder *)undirected;

// Disallowed inherited constructors, do not use.

- (instancetype)initPackagePrivateWithBoolean:(jboolean)arg0 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonGraphNetworkBuilder)

J2OBJC_FIELD_SETTER(ComGoogleCommonGraphNetworkBuilder, edgeOrder_, ComGoogleCommonGraphElementOrder *)
J2OBJC_FIELD_SETTER(ComGoogleCommonGraphNetworkBuilder, expectedEdgeCount_, ComGoogleCommonBaseOptional *)

FOUNDATION_EXPORT ComGoogleCommonGraphNetworkBuilder *ComGoogleCommonGraphNetworkBuilder_directed(void);

FOUNDATION_EXPORT ComGoogleCommonGraphNetworkBuilder *ComGoogleCommonGraphNetworkBuilder_undirected(void);

FOUNDATION_EXPORT ComGoogleCommonGraphNetworkBuilder *ComGoogleCommonGraphNetworkBuilder_fromWithComGoogleCommonGraphNetwork_(id<ComGoogleCommonGraphNetwork> network);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonGraphNetworkBuilder)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonGraphNetworkBuilder")
