//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/android/build_result/java/com/google/errorprone/annotations/InlineMeValidationDisabled.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleErrorproneAnnotationsInlineMeValidationDisabled")
#ifdef RESTRICT_ComGoogleErrorproneAnnotationsInlineMeValidationDisabled
#define INCLUDE_ALL_ComGoogleErrorproneAnnotationsInlineMeValidationDisabled 0
#else
#define INCLUDE_ALL_ComGoogleErrorproneAnnotationsInlineMeValidationDisabled 1
#endif
#undef RESTRICT_ComGoogleErrorproneAnnotationsInlineMeValidationDisabled

#if !defined (ComGoogleErrorproneAnnotationsInlineMeValidationDisabled_) && (INCLUDE_ALL_ComGoogleErrorproneAnnotationsInlineMeValidationDisabled || defined(INCLUDE_ComGoogleErrorproneAnnotationsInlineMeValidationDisabled))
#define ComGoogleErrorproneAnnotationsInlineMeValidationDisabled_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;

@protocol ComGoogleErrorproneAnnotationsInlineMeValidationDisabled < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface ComGoogleErrorproneAnnotationsInlineMeValidationDisabled : NSObject < ComGoogleErrorproneAnnotationsInlineMeValidationDisabled > {
 @public
  NSString *value_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleErrorproneAnnotationsInlineMeValidationDisabled)

FOUNDATION_EXPORT id<ComGoogleErrorproneAnnotationsInlineMeValidationDisabled> create_ComGoogleErrorproneAnnotationsInlineMeValidationDisabled(NSString *value);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleErrorproneAnnotationsInlineMeValidationDisabled)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleErrorproneAnnotationsInlineMeValidationDisabled")
