//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/platform/libcore/ojluni/src/main/java/java/security/spec/XECPublicKeySpec.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JavaSecuritySpecXECPublicKeySpec")
#ifdef RESTRICT_JavaSecuritySpecXECPublicKeySpec
#define INCLUDE_ALL_JavaSecuritySpecXECPublicKeySpec 0
#else
#define INCLUDE_ALL_JavaSecuritySpecXECPublicKeySpec 1
#endif
#undef RESTRICT_JavaSecuritySpecXECPublicKeySpec

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (JavaSecuritySpecXECPublicKeySpec_) && (INCLUDE_ALL_JavaSecuritySpecXECPublicKeySpec || defined(INCLUDE_JavaSecuritySpecXECPublicKeySpec))
#define JavaSecuritySpecXECPublicKeySpec_

#define RESTRICT_JavaSecuritySpecKeySpec 1
#define INCLUDE_JavaSecuritySpecKeySpec 1
#include "java/security/spec/KeySpec.h"

@class JavaMathBigInteger;
@protocol JavaSecuritySpecAlgorithmParameterSpec;

/*!
 @brief A class representing elliptic curve public keys as defined in RFC 7748,
  including the curve and other algorithm parameters.The public key is a
  particular point on the curve, which is represented using only its
  u-coordinate.
 A u-coordinate is an element of the field of integers modulo
  some value that is determined by the algorithm parameters. This field
  element is represented by a BigInteger which may hold any value. That is,
  the BigInteger is not restricted to the range of canonical field elements.
 @since 11
 */
@interface JavaSecuritySpecXECPublicKeySpec : NSObject < JavaSecuritySpecKeySpec >

#pragma mark Public

/*!
 @brief Construct a public key spec using the supplied parameters and
  u coordinate.
 @param params the algorithm parameters
 @param u the u-coordinate of the point, represented using a BigInteger           which may hold any value
 @throw NullPointerExceptionif <code>params</code> or <code>u</code>
                               is null.
 */
- (instancetype __nonnull)initWithJavaSecuritySpecAlgorithmParameterSpec:(id<JavaSecuritySpecAlgorithmParameterSpec>)params
                                                  withJavaMathBigInteger:(JavaMathBigInteger *)u;

/*!
 @brief Get the algorithm parameters that define the curve and other settings.
 @return the parameters
 */
- (id<JavaSecuritySpecAlgorithmParameterSpec>)getParams;

/*!
 @brief Get the u coordinate of the point.
 @return the u-coordinate, represented using a BigInteger which may hold
           any value
 */
- (JavaMathBigInteger *)getU;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecuritySpecXECPublicKeySpec)

FOUNDATION_EXPORT void JavaSecuritySpecXECPublicKeySpec_initWithJavaSecuritySpecAlgorithmParameterSpec_withJavaMathBigInteger_(JavaSecuritySpecXECPublicKeySpec *self, id<JavaSecuritySpecAlgorithmParameterSpec> params, JavaMathBigInteger *u);

FOUNDATION_EXPORT JavaSecuritySpecXECPublicKeySpec *new_JavaSecuritySpecXECPublicKeySpec_initWithJavaSecuritySpecAlgorithmParameterSpec_withJavaMathBigInteger_(id<JavaSecuritySpecAlgorithmParameterSpec> params, JavaMathBigInteger *u) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JavaSecuritySpecXECPublicKeySpec *create_JavaSecuritySpecXECPublicKeySpec_initWithJavaSecuritySpecAlgorithmParameterSpec_withJavaMathBigInteger_(id<JavaSecuritySpecAlgorithmParameterSpec> params, JavaMathBigInteger *u);

J2OBJC_TYPE_LITERAL_HEADER(JavaSecuritySpecXECPublicKeySpec)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_JavaSecuritySpecXECPublicKeySpec")
