//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/platform/external/icu/android_icu4j/libcore_bridge/src/java/com/android/icu/text/ExtendedDateFormatSymbols.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComAndroidIcuTextExtendedDateFormatSymbols")
#ifdef RESTRICT_ComAndroidIcuTextExtendedDateFormatSymbols
#define INCLUDE_ALL_ComAndroidIcuTextExtendedDateFormatSymbols 0
#else
#define INCLUDE_ALL_ComAndroidIcuTextExtendedDateFormatSymbols 1
#endif
#undef RESTRICT_ComAndroidIcuTextExtendedDateFormatSymbols

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComAndroidIcuTextExtendedDateFormatSymbols_) && (INCLUDE_ALL_ComAndroidIcuTextExtendedDateFormatSymbols || defined(INCLUDE_ComAndroidIcuTextExtendedDateFormatSymbols))
#define ComAndroidIcuTextExtendedDateFormatSymbols_

@class AndroidIcuTextDateFormatSymbols;
@class AndroidIcuUtilULocale;
@class IOSObjectArray;
@class JavaLangInteger;

/*!
 @brief Provides extra data not in <code>DateFormatSymbols</code>.
 */
@interface ComAndroidIcuTextExtendedDateFormatSymbols : NSObject

#pragma mark Public

/*!
 @brief Get the <code>DateFormatSymbols</code>.
 */
- (AndroidIcuTextDateFormatSymbols *)getDateFormatSymbols;

/*!
 @brief Get an instance.
 */
+ (ComAndroidIcuTextExtendedDateFormatSymbols *)getInstanceWithAndroidIcuUtilULocale:(AndroidIcuUtilULocale *)locale;

/*!
 @brief Returns <code>DateFormatSymbols.NARROW</code> quarter strings.
 @param context<code>DateFormatSymbols.FORMAT</code>  or <code>DateFormatSymbols.STANDALONE</code> .
 @throw IllegalArgumentExceptionfor bad context or no data.
 */
- (IOSObjectArray *)getNarrowQuartersWithInt:(jint)context;

// Disallowed inherited constructors, do not use.

- (instancetype __nonnull)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComAndroidIcuTextExtendedDateFormatSymbols)

FOUNDATION_EXPORT ComAndroidIcuTextExtendedDateFormatSymbols *ComAndroidIcuTextExtendedDateFormatSymbols_getInstanceWithAndroidIcuUtilULocale_(AndroidIcuUtilULocale *locale);

J2OBJC_TYPE_LITERAL_HEADER(ComAndroidIcuTextExtendedDateFormatSymbols)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComAndroidIcuTextExtendedDateFormatSymbols")
