//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/junit/build_result/java/org/junit/runner/FilterFactoryParams.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitRunnerFilterFactoryParams")
#ifdef RESTRICT_OrgJunitRunnerFilterFactoryParams
#define INCLUDE_ALL_OrgJunitRunnerFilterFactoryParams 0
#else
#define INCLUDE_ALL_OrgJunitRunnerFilterFactoryParams 1
#endif
#undef RESTRICT_OrgJunitRunnerFilterFactoryParams

#if !defined (OrgJunitRunnerFilterFactoryParams_) && (INCLUDE_ALL_OrgJunitRunnerFilterFactoryParams || defined(INCLUDE_OrgJunitRunnerFilterFactoryParams))
#define OrgJunitRunnerFilterFactoryParams_

@class OrgJunitRunnerDescription;

@interface OrgJunitRunnerFilterFactoryParams : NSObject

#pragma mark Public

- (instancetype)initWithOrgJunitRunnerDescription:(OrgJunitRunnerDescription *)topLevelDescription
                                     withNSString:(NSString *)args;

- (NSString *)getArgs;

- (OrgJunitRunnerDescription *)getTopLevelDescription;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgJunitRunnerFilterFactoryParams)

FOUNDATION_EXPORT void OrgJunitRunnerFilterFactoryParams_initWithOrgJunitRunnerDescription_withNSString_(OrgJunitRunnerFilterFactoryParams *self, OrgJunitRunnerDescription *topLevelDescription, NSString *args);

FOUNDATION_EXPORT OrgJunitRunnerFilterFactoryParams *new_OrgJunitRunnerFilterFactoryParams_initWithOrgJunitRunnerDescription_withNSString_(OrgJunitRunnerDescription *topLevelDescription, NSString *args) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgJunitRunnerFilterFactoryParams *create_OrgJunitRunnerFilterFactoryParams_initWithOrgJunitRunnerDescription_withNSString_(OrgJunitRunnerDescription *topLevelDescription, NSString *args);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitRunnerFilterFactoryParams)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgJunitRunnerFilterFactoryParams")
