//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xml/utils/StringToIntTable.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXmlUtilsStringToIntTable")
#ifdef RESTRICT_OrgApacheXmlUtilsStringToIntTable
#define INCLUDE_ALL_OrgApacheXmlUtilsStringToIntTable 0
#else
#define INCLUDE_ALL_OrgApacheXmlUtilsStringToIntTable 1
#endif
#undef RESTRICT_OrgApacheXmlUtilsStringToIntTable

#if !defined (OrgApacheXmlUtilsStringToIntTable_) && (INCLUDE_ALL_OrgApacheXmlUtilsStringToIntTable || defined(INCLUDE_OrgApacheXmlUtilsStringToIntTable))
#define OrgApacheXmlUtilsStringToIntTable_

@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;

@interface OrgApacheXmlUtilsStringToIntTable : NSObject

#pragma mark Public

- (instancetype)init;

- (instancetype)initWithInt:(jint)blocksize;

- (jboolean)containsWithNSString:(NSString *)key;

- (jint)getWithNSString:(NSString *)key;

- (jint)getIgnoreCaseWithNSString:(NSString *)key;

- (jint)getLength;

- (IOSObjectArray *)keys;

- (void)putWithNSString:(NSString *)key
                withInt:(jint)value;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXmlUtilsStringToIntTable)

inline jint OrgApacheXmlUtilsStringToIntTable_get_INVALID_KEY(void);
#define OrgApacheXmlUtilsStringToIntTable_INVALID_KEY -10000
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlUtilsStringToIntTable, INVALID_KEY, jint)

FOUNDATION_EXPORT void OrgApacheXmlUtilsStringToIntTable_init(OrgApacheXmlUtilsStringToIntTable *self);

FOUNDATION_EXPORT OrgApacheXmlUtilsStringToIntTable *new_OrgApacheXmlUtilsStringToIntTable_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXmlUtilsStringToIntTable *create_OrgApacheXmlUtilsStringToIntTable_init(void);

FOUNDATION_EXPORT void OrgApacheXmlUtilsStringToIntTable_initWithInt_(OrgApacheXmlUtilsStringToIntTable *self, jint blocksize);

FOUNDATION_EXPORT OrgApacheXmlUtilsStringToIntTable *new_OrgApacheXmlUtilsStringToIntTable_initWithInt_(jint blocksize) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXmlUtilsStringToIntTable *create_OrgApacheXmlUtilsStringToIntTable_initWithInt_(jint blocksize);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXmlUtilsStringToIntTable)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXmlUtilsStringToIntTable")
