//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/testing/mockito/build_result/java/org/mockito/internal/debugging/LoggingListener.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalDebuggingLoggingListener")
#ifdef RESTRICT_OrgMockitoInternalDebuggingLoggingListener
#define INCLUDE_ALL_OrgMockitoInternalDebuggingLoggingListener 0
#else
#define INCLUDE_ALL_OrgMockitoInternalDebuggingLoggingListener 1
#endif
#undef RESTRICT_OrgMockitoInternalDebuggingLoggingListener

#if !defined (OrgMockitoInternalDebuggingLoggingListener_) && (INCLUDE_ALL_OrgMockitoInternalDebuggingLoggingListener || defined(INCLUDE_OrgMockitoInternalDebuggingLoggingListener))
#define OrgMockitoInternalDebuggingLoggingListener_

#define RESTRICT_OrgMockitoInternalDebuggingFindingsListener 1
#define INCLUDE_OrgMockitoInternalDebuggingFindingsListener 1
#include "org/mockito/internal/debugging/FindingsListener.h"

@class JavaLangBoolean;
@class JavaLangInteger;
@class OrgMockitoInternalInvocationInvocationMatcher;
@protocol OrgMockitoInvocationInvocation;

@interface OrgMockitoInternalDebuggingLoggingListener : NSObject < OrgMockitoInternalDebuggingFindingsListener >

#pragma mark Public

- (instancetype)initWithBoolean:(jboolean)warnAboutUnstubbed;

- (void)foundStubCalledWithDifferentArgsWithOrgMockitoInvocationInvocation:(id<OrgMockitoInvocationInvocation>)unused
                         withOrgMockitoInternalInvocationInvocationMatcher:(OrgMockitoInternalInvocationInvocationMatcher *)unstubbed;

- (void)foundUnstubbedWithOrgMockitoInternalInvocationInvocationMatcher:(OrgMockitoInternalInvocationInvocationMatcher *)unstubbed;

- (void)foundUnusedStubWithOrgMockitoInvocationInvocation:(id<OrgMockitoInvocationInvocation>)unused;

- (NSString *)getStubbingInfo;

#pragma mark Package-Private

+ (jint)indexOfNextPairWithInt:(jint)collectionSize;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalDebuggingLoggingListener)

FOUNDATION_EXPORT void OrgMockitoInternalDebuggingLoggingListener_initWithBoolean_(OrgMockitoInternalDebuggingLoggingListener *self, jboolean warnAboutUnstubbed);

FOUNDATION_EXPORT OrgMockitoInternalDebuggingLoggingListener *new_OrgMockitoInternalDebuggingLoggingListener_initWithBoolean_(jboolean warnAboutUnstubbed) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalDebuggingLoggingListener *create_OrgMockitoInternalDebuggingLoggingListener_initWithBoolean_(jboolean warnAboutUnstubbed);

FOUNDATION_EXPORT jint OrgMockitoInternalDebuggingLoggingListener_indexOfNextPairWithInt_(jint collectionSize);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalDebuggingLoggingListener)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalDebuggingLoggingListener")
