//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xalan/transformer/XalanProperties.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXalanTransformerXalanProperties")
#ifdef RESTRICT_OrgApacheXalanTransformerXalanProperties
#define INCLUDE_ALL_OrgApacheXalanTransformerXalanProperties 0
#else
#define INCLUDE_ALL_OrgApacheXalanTransformerXalanProperties 1
#endif
#undef RESTRICT_OrgApacheXalanTransformerXalanProperties

#if !defined (OrgApacheXalanTransformerXalanProperties_) && (INCLUDE_ALL_OrgApacheXalanTransformerXalanProperties || defined(INCLUDE_OrgApacheXalanTransformerXalanProperties))
#define OrgApacheXalanTransformerXalanProperties_

@interface OrgApacheXalanTransformerXalanProperties : NSObject

#pragma mark Public

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXalanTransformerXalanProperties)

inline NSString *OrgApacheXalanTransformerXalanProperties_get_SOURCE_LOCATION(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *OrgApacheXalanTransformerXalanProperties_SOURCE_LOCATION;
J2OBJC_STATIC_FIELD_OBJ_FINAL(OrgApacheXalanTransformerXalanProperties, SOURCE_LOCATION, NSString *)

FOUNDATION_EXPORT void OrgApacheXalanTransformerXalanProperties_init(OrgApacheXalanTransformerXalanProperties *self);

FOUNDATION_EXPORT OrgApacheXalanTransformerXalanProperties *new_OrgApacheXalanTransformerXalanProperties_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXalanTransformerXalanProperties *create_OrgApacheXalanTransformerXalanProperties_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXalanTransformerXalanProperties)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXalanTransformerXalanProperties")
