//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/junit/build_result/java/com/tngtech/java/junit/dataprovider/DataProvider.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComTngtechJavaJunitDataproviderDataProvider")
#ifdef RESTRICT_ComTngtechJavaJunitDataproviderDataProvider
#define INCLUDE_ALL_ComTngtechJavaJunitDataproviderDataProvider 0
#else
#define INCLUDE_ALL_ComTngtechJavaJunitDataproviderDataProvider 1
#endif
#undef RESTRICT_ComTngtechJavaJunitDataproviderDataProvider

#if !defined (ComTngtechJavaJunitDataproviderDataProvider_) && (INCLUDE_ALL_ComTngtechJavaJunitDataproviderDataProvider || defined(INCLUDE_ComTngtechJavaJunitDataproviderDataProvider))
#define ComTngtechJavaJunitDataproviderDataProvider_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;
@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangInteger;

@protocol ComTngtechJavaJunitDataproviderDataProvider < JavaLangAnnotationAnnotation >

@property (readonly) IOSObjectArray *value;
@property (readonly) NSString *splitBy;
@property (readonly) jboolean convertNulls;
@property (readonly) jboolean trimValues;
@property (readonly) NSString *format;
@property (readonly) jboolean ignoreEnumCase;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface ComTngtechJavaJunitDataproviderDataProvider : NSObject < ComTngtechJavaJunitDataproviderDataProvider > {
 @public
  IOSObjectArray *value_;
  NSString *splitBy_;
  jboolean convertNulls_;
  jboolean trimValues_;
  NSString *format_;
  jboolean ignoreEnumCase_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(ComTngtechJavaJunitDataproviderDataProvider)

inline NSString *ComTngtechJavaJunitDataproviderDataProvider_get_COMMA(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ComTngtechJavaJunitDataproviderDataProvider_COMMA;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComTngtechJavaJunitDataproviderDataProvider, COMMA, NSString *)

inline NSString *ComTngtechJavaJunitDataproviderDataProvider_get_NULL(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ComTngtechJavaJunitDataproviderDataProvider_NULL;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComTngtechJavaJunitDataproviderDataProvider, NULL, NSString *)

inline NSString *ComTngtechJavaJunitDataproviderDataProvider_get_DEFAULT_FORMAT(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT NSString *ComTngtechJavaJunitDataproviderDataProvider_DEFAULT_FORMAT;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComTngtechJavaJunitDataproviderDataProvider, DEFAULT_FORMAT, NSString *)

FOUNDATION_EXPORT id<ComTngtechJavaJunitDataproviderDataProvider> create_ComTngtechJavaJunitDataproviderDataProvider(jboolean convertNulls, NSString *format, jboolean ignoreEnumCase, NSString *splitBy, jboolean trimValues, IOSObjectArray *value);

J2OBJC_TYPE_LITERAL_HEADER(ComTngtechJavaJunitDataproviderDataProvider)

#endif

#pragma pop_macro("INCLUDE_ALL_ComTngtechJavaJunitDataproviderDataProvider")
