//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/junit/build_result/java/com/tngtech/java/junit/dataprovider/Placeholders.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComTngtechJavaJunitDataproviderPlaceholders")
#ifdef RESTRICT_ComTngtechJavaJunitDataproviderPlaceholders
#define INCLUDE_ALL_ComTngtechJavaJunitDataproviderPlaceholders 0
#else
#define INCLUDE_ALL_ComTngtechJavaJunitDataproviderPlaceholders 1
#endif
#undef RESTRICT_ComTngtechJavaJunitDataproviderPlaceholders

#if !defined (ComTngtechJavaJunitDataproviderPlaceholders_) && (INCLUDE_ALL_ComTngtechJavaJunitDataproviderPlaceholders || defined(INCLUDE_ComTngtechJavaJunitDataproviderPlaceholders))
#define ComTngtechJavaJunitDataproviderPlaceholders_

@protocol JavaUtilList;

@interface ComTngtechJavaJunitDataproviderPlaceholders : NSObject

#pragma mark Public

- (instancetype)init;

+ (id<JavaUtilList>)all;

+ (void)reset;

@end

J2OBJC_STATIC_INIT(ComTngtechJavaJunitDataproviderPlaceholders)

FOUNDATION_EXPORT void ComTngtechJavaJunitDataproviderPlaceholders_init(ComTngtechJavaJunitDataproviderPlaceholders *self);

FOUNDATION_EXPORT ComTngtechJavaJunitDataproviderPlaceholders *new_ComTngtechJavaJunitDataproviderPlaceholders_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComTngtechJavaJunitDataproviderPlaceholders *create_ComTngtechJavaJunitDataproviderPlaceholders_init(void);

FOUNDATION_EXPORT id<JavaUtilList> ComTngtechJavaJunitDataproviderPlaceholders_all(void);

FOUNDATION_EXPORT void ComTngtechJavaJunitDataproviderPlaceholders_reset(void);

J2OBJC_TYPE_LITERAL_HEADER(ComTngtechJavaJunitDataproviderPlaceholders)

#endif

#pragma pop_macro("INCLUDE_ALL_ComTngtechJavaJunitDataproviderPlaceholders")
