//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/testing/truth/build_result/java/com/google/common/truth/FailureMetadata.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonTruthFailureMetadata")
#ifdef RESTRICT_ComGoogleCommonTruthFailureMetadata
#define INCLUDE_ALL_ComGoogleCommonTruthFailureMetadata 0
#else
#define INCLUDE_ALL_ComGoogleCommonTruthFailureMetadata 1
#endif
#undef RESTRICT_ComGoogleCommonTruthFailureMetadata

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonTruthFailureMetadata_) && (INCLUDE_ALL_ComGoogleCommonTruthFailureMetadata || defined(INCLUDE_ComGoogleCommonTruthFailureMetadata))
#define ComGoogleCommonTruthFailureMetadata_

@class ComGoogleCommonCollectImmutableList;
@class ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar;
@class ComGoogleCommonTruthSubject;
@class IOSObjectArray;
@protocol ComGoogleCommonBaseFunction;
@protocol ComGoogleCommonTruthFailureStrategy;

@interface ComGoogleCommonTruthFailureMetadata : NSObject

#pragma mark Package-Private

- (instancetype)initWithComGoogleCommonTruthFailureStrategy:(id<ComGoogleCommonTruthFailureStrategy>)strategy
                    withComGoogleCommonCollectImmutableList:(ComGoogleCommonCollectImmutableList *)messages
                    withComGoogleCommonCollectImmutableList:(ComGoogleCommonCollectImmutableList *)steps;

- (void)failWithComGoogleCommonCollectImmutableList:(ComGoogleCommonCollectImmutableList *)facts;

- (void)failEqualityCheckWithComGoogleCommonCollectImmutableList:(ComGoogleCommonCollectImmutableList *)headFacts
                         withComGoogleCommonCollectImmutableList:(ComGoogleCommonCollectImmutableList *)tailFacts
                                                    withNSString:(NSString *)expected
                                                    withNSString:(NSString *)actual;

+ (ComGoogleCommonTruthFailureMetadata *)forFailureStrategyWithComGoogleCommonTruthFailureStrategy:(id<ComGoogleCommonTruthFailureStrategy>)failureStrategy;

- (ComGoogleCommonTruthFailureMetadata *)updateForCheckCall;

- (ComGoogleCommonTruthFailureMetadata *)updateForCheckCallWithComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar:(ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar *)valuesAreSimilar
                                                                                             withComGoogleCommonBaseFunction:(id<ComGoogleCommonBaseFunction>)descriptionUpdate;

- (ComGoogleCommonTruthFailureMetadata *)updateForSubjectWithComGoogleCommonTruthSubject:(ComGoogleCommonTruthSubject *)subject;

- (ComGoogleCommonTruthFailureMetadata *)withMessageWithNSString:(NSString *)format
                                               withNSObjectArray:(IOSObjectArray *)args;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonTruthFailureMetadata)

FOUNDATION_EXPORT ComGoogleCommonTruthFailureMetadata *ComGoogleCommonTruthFailureMetadata_forFailureStrategyWithComGoogleCommonTruthFailureStrategy_(id<ComGoogleCommonTruthFailureStrategy> failureStrategy);

FOUNDATION_EXPORT void ComGoogleCommonTruthFailureMetadata_initWithComGoogleCommonTruthFailureStrategy_withComGoogleCommonCollectImmutableList_withComGoogleCommonCollectImmutableList_(ComGoogleCommonTruthFailureMetadata *self, id<ComGoogleCommonTruthFailureStrategy> strategy, ComGoogleCommonCollectImmutableList *messages, ComGoogleCommonCollectImmutableList *steps);

FOUNDATION_EXPORT ComGoogleCommonTruthFailureMetadata *new_ComGoogleCommonTruthFailureMetadata_initWithComGoogleCommonTruthFailureStrategy_withComGoogleCommonCollectImmutableList_withComGoogleCommonCollectImmutableList_(id<ComGoogleCommonTruthFailureStrategy> strategy, ComGoogleCommonCollectImmutableList *messages, ComGoogleCommonCollectImmutableList *steps) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonTruthFailureMetadata *create_ComGoogleCommonTruthFailureMetadata_initWithComGoogleCommonTruthFailureStrategy_withComGoogleCommonCollectImmutableList_withComGoogleCommonCollectImmutableList_(id<ComGoogleCommonTruthFailureStrategy> strategy, ComGoogleCommonCollectImmutableList *messages, ComGoogleCommonCollectImmutableList *steps);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonTruthFailureMetadata)

#endif

#if !defined (ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_) && (INCLUDE_ALL_ComGoogleCommonTruthFailureMetadata || defined(INCLUDE_ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar))
#define ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_

#define RESTRICT_JavaLangEnum 1
#define INCLUDE_JavaLangEnum 1
#include "java/lang/Enum.h"

@class IOSObjectArray;

typedef NS_ENUM(jint, ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_Enum) {
  ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_Enum_SIMILAR = 0,
  ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_Enum_DIFFERENT = 1,
};
#if J2OBJC_IMPORTED_BY_JAVA_IMPLEMENTATION
#define ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_ORDINAL jint
#else
#define ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_ORDINAL ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_Enum
#endif


@interface ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar : JavaLangEnum

#pragma mark Public

+ (ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar *)valueOfWithNSString:(NSString *)name;

+ (IOSObjectArray *)values;

#pragma mark Package-Private

- (ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_Enum)toNSEnum;

- (ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_ORDINAL)ordinal;

@end

J2OBJC_STATIC_INIT(ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar)

/*! INTERNAL ONLY - Use enum accessors declared below. */
FOUNDATION_EXPORT ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar *ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_values_[];

inline ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar *ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_get_SIMILAR(void);
J2OBJC_ENUM_CONSTANT(ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar, SIMILAR)

inline ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar *ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_get_DIFFERENT(void);
J2OBJC_ENUM_CONSTANT(ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar, DIFFERENT)

FOUNDATION_EXPORT IOSObjectArray *ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_values(void);

FOUNDATION_EXPORT ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar *ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_valueOfWithNSString_(NSString *name);

FOUNDATION_EXPORT ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar *ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_fromOrdinal(ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar_ORDINAL ordinal);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonTruthFailureMetadata_OldAndNewValuesAreSimilar)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonTruthFailureMetadata")
