//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/testing/truth/build_result/java/com/google/common/truth/TruthFailureSubject.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonTruthTruthFailureSubject")
#ifdef RESTRICT_ComGoogleCommonTruthTruthFailureSubject
#define INCLUDE_ALL_ComGoogleCommonTruthTruthFailureSubject 0
#else
#define INCLUDE_ALL_ComGoogleCommonTruthTruthFailureSubject 1
#endif
#undef RESTRICT_ComGoogleCommonTruthTruthFailureSubject

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonTruthTruthFailureSubject_) && (INCLUDE_ALL_ComGoogleCommonTruthTruthFailureSubject || defined(INCLUDE_ComGoogleCommonTruthTruthFailureSubject))
#define ComGoogleCommonTruthTruthFailureSubject_

#define RESTRICT_ComGoogleCommonTruthThrowableSubject 1
#define INCLUDE_ComGoogleCommonTruthThrowableSubject 1
#include "com/google/common/truth/ThrowableSubject.h"

@class ComGoogleCommonTruthFact;
@class ComGoogleCommonTruthFailureMetadata;
@class ComGoogleCommonTruthIterableSubject;
@class ComGoogleCommonTruthStringSubject;
@class JavaLangAssertionError;
@class JavaLangInteger;
@class JavaLangThrowable;
@protocol ComGoogleCommonTruthSubject_Factory;

@interface ComGoogleCommonTruthTruthFailureSubject : ComGoogleCommonTruthThrowableSubject

#pragma mark Public

- (ComGoogleCommonTruthIterableSubject *)factKeys;

- (ComGoogleCommonTruthStringSubject *)factValueWithNSString:(NSString *)key;

- (ComGoogleCommonTruthStringSubject *)factValueWithNSString:(NSString *)key
                                                     withInt:(jint)index;

+ (id<ComGoogleCommonTruthSubject_Factory>)truthFailures;

#pragma mark Package-Private

- (instancetype)initWithComGoogleCommonTruthFailureMetadata:(ComGoogleCommonTruthFailureMetadata *)metadata
                                 withJavaLangAssertionError:(JavaLangAssertionError *)actual
                                               withNSString:(NSString *)typeDescription;

// Disallowed inherited constructors, do not use.

- (instancetype)initWithComGoogleCommonTruthFailureMetadata:(ComGoogleCommonTruthFailureMetadata *)arg0
                                      withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

- (instancetype)initWithComGoogleCommonTruthFailureMetadata:(ComGoogleCommonTruthFailureMetadata *)arg0
                                      withJavaLangThrowable:(JavaLangThrowable *)arg1
                                               withNSString:(NSString *)arg2 NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(ComGoogleCommonTruthTruthFailureSubject)

inline ComGoogleCommonTruthFact *ComGoogleCommonTruthTruthFailureSubject_get_HOW_TO_TEST_KEYS_WITHOUT_VALUES(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT ComGoogleCommonTruthFact *ComGoogleCommonTruthTruthFailureSubject_HOW_TO_TEST_KEYS_WITHOUT_VALUES;
J2OBJC_STATIC_FIELD_OBJ_FINAL(ComGoogleCommonTruthTruthFailureSubject, HOW_TO_TEST_KEYS_WITHOUT_VALUES, ComGoogleCommonTruthFact *)

FOUNDATION_EXPORT id<ComGoogleCommonTruthSubject_Factory> ComGoogleCommonTruthTruthFailureSubject_truthFailures(void);

FOUNDATION_EXPORT void ComGoogleCommonTruthTruthFailureSubject_initWithComGoogleCommonTruthFailureMetadata_withJavaLangAssertionError_withNSString_(ComGoogleCommonTruthTruthFailureSubject *self, ComGoogleCommonTruthFailureMetadata *metadata, JavaLangAssertionError *actual, NSString *typeDescription);

FOUNDATION_EXPORT ComGoogleCommonTruthTruthFailureSubject *new_ComGoogleCommonTruthTruthFailureSubject_initWithComGoogleCommonTruthFailureMetadata_withJavaLangAssertionError_withNSString_(ComGoogleCommonTruthFailureMetadata *metadata, JavaLangAssertionError *actual, NSString *typeDescription) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT ComGoogleCommonTruthTruthFailureSubject *create_ComGoogleCommonTruthTruthFailureSubject_initWithComGoogleCommonTruthFailureMetadata_withJavaLangAssertionError_withNSString_(ComGoogleCommonTruthFailureMetadata *metadata, JavaLangAssertionError *actual, NSString *typeDescription);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonTruthTruthFailureSubject)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonTruthTruthFailureSubject")
