//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/junit/build_result/java/junit/framework/TestFailure.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JunitFrameworkTestFailure")
#ifdef RESTRICT_JunitFrameworkTestFailure
#define INCLUDE_ALL_JunitFrameworkTestFailure 0
#else
#define INCLUDE_ALL_JunitFrameworkTestFailure 1
#endif
#undef RESTRICT_JunitFrameworkTestFailure

#if !defined (JunitFrameworkTestFailure_) && (INCLUDE_ALL_JunitFrameworkTestFailure || defined(INCLUDE_JunitFrameworkTestFailure))
#define JunitFrameworkTestFailure_

@class JavaLangBoolean;
@class JavaLangThrowable;
@protocol JunitFrameworkTest;

@interface JunitFrameworkTestFailure : NSObject {
 @public
  id<JunitFrameworkTest> fFailedTest_;
  JavaLangThrowable *fThrownException_;
}

#pragma mark Public

- (instancetype)initWithJunitFrameworkTest:(id<JunitFrameworkTest>)failedTest
                     withJavaLangThrowable:(JavaLangThrowable *)thrownException;

- (NSString *)exceptionMessage;

- (id<JunitFrameworkTest>)failedTest;

- (jboolean)isFailure;

- (JavaLangThrowable *)thrownException;

- (NSString *)description;

- (NSString *)trace;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(JunitFrameworkTestFailure)

J2OBJC_FIELD_SETTER(JunitFrameworkTestFailure, fFailedTest_, id<JunitFrameworkTest>)
J2OBJC_FIELD_SETTER(JunitFrameworkTestFailure, fThrownException_, JavaLangThrowable *)

FOUNDATION_EXPORT void JunitFrameworkTestFailure_initWithJunitFrameworkTest_withJavaLangThrowable_(JunitFrameworkTestFailure *self, id<JunitFrameworkTest> failedTest, JavaLangThrowable *thrownException);

FOUNDATION_EXPORT JunitFrameworkTestFailure *new_JunitFrameworkTestFailure_initWithJunitFrameworkTest_withJavaLangThrowable_(id<JunitFrameworkTest> failedTest, JavaLangThrowable *thrownException) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT JunitFrameworkTestFailure *create_JunitFrameworkTestFailure_initWithJunitFrameworkTest_withJavaLangThrowable_(id<JunitFrameworkTest> failedTest, JavaLangThrowable *thrownException);

J2OBJC_TYPE_LITERAL_HEADER(JunitFrameworkTestFailure)

#endif

#pragma pop_macro("INCLUDE_ALL_JunitFrameworkTestFailure")
