//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/testing/mockito/build_result/java/org/mockito/internal/listeners/StubbingLookupEvent.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalListenersStubbingLookupEvent")
#ifdef RESTRICT_OrgMockitoInternalListenersStubbingLookupEvent
#define INCLUDE_ALL_OrgMockitoInternalListenersStubbingLookupEvent 0
#else
#define INCLUDE_ALL_OrgMockitoInternalListenersStubbingLookupEvent 1
#endif
#undef RESTRICT_OrgMockitoInternalListenersStubbingLookupEvent

#if !defined (OrgMockitoInternalListenersStubbingLookupEvent_) && (INCLUDE_ALL_OrgMockitoInternalListenersStubbingLookupEvent || defined(INCLUDE_OrgMockitoInternalListenersStubbingLookupEvent))
#define OrgMockitoInternalListenersStubbingLookupEvent_

@protocol JavaUtilCollection;
@protocol OrgMockitoInvocationInvocation;
@protocol OrgMockitoMockMockCreationSettings;
@protocol OrgMockitoStubbingStubbing;

@protocol OrgMockitoInternalListenersStubbingLookupEvent < JavaObject >

- (id<OrgMockitoInvocationInvocation>)getInvocation;

- (id<OrgMockitoStubbingStubbing>)getStubbingFound;

- (id<JavaUtilCollection>)getAllStubbings;

- (id<OrgMockitoMockMockCreationSettings>)getMockSettings;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalListenersStubbingLookupEvent)

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalListenersStubbingLookupEvent)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalListenersStubbingLookupEvent")
