//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/platform/libcore/ojluni/src/main/java/java/util/concurrent/BlockingDeque.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JavaUtilConcurrentBlockingDeque")
#ifdef RESTRICT_JavaUtilConcurrentBlockingDeque
#define INCLUDE_ALL_JavaUtilConcurrentBlockingDeque 0
#else
#define INCLUDE_ALL_JavaUtilConcurrentBlockingDeque 1
#endif
#undef RESTRICT_JavaUtilConcurrentBlockingDeque

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (JavaUtilConcurrentBlockingDeque_) && (INCLUDE_ALL_JavaUtilConcurrentBlockingDeque || defined(INCLUDE_JavaUtilConcurrentBlockingDeque))
#define JavaUtilConcurrentBlockingDeque_

#define RESTRICT_JavaUtilConcurrentBlockingQueue 1
#define INCLUDE_JavaUtilConcurrentBlockingQueue 1
#include "java/util/concurrent/BlockingQueue.h"

#define RESTRICT_JavaUtilDeque 1
#define INCLUDE_JavaUtilDeque 1
#include "java/util/Deque.h"

@class JavaLangBoolean;
@class JavaLangInteger;
@class JavaLangLong;
@class JavaUtilConcurrentTimeUnit;
@protocol JavaUtilIterator;

/*!
 @brief A <code>Deque</code> that additionally supports blocking operations that wait
  for the deque to become non-empty when retrieving an element, and wait for
  space to become available in the deque when storing an element.
 <p><code>BlockingDeque</code> methods come in four forms, with different ways
  of handling operations that cannot be satisfied immediately, but may be
  satisfied at some point in the future:
  one throws an exception, the second returns a special value (either 
 <code>null</code> or <code>false</code>, depending on the operation), the third
  blocks the current thread indefinitely until the operation can succeed,
  and the fourth blocks for only a given maximum time limit before giving
  up.  These methods are summarized in the following table: 
 <table class="plain">
  <caption>Summary of BlockingDeque methods</caption>
   <tr>
     <th id="First" colspan="5"> First Element (Head)</th>
   </tr>
   <tr>
     <td></td>
     <th id="FThrow" style="font-weight:normal; font-style: italic">Throws exception</th>
     <th id="FValue" style="font-weight:normal; font-style: italic">Special value</th>
     <th id="FBlock" style="font-weight:normal; font-style: italic">Blocks</th>
     <th id="FTimes" style="font-weight:normal; font-style: italic">Times out</th>
   </tr>
   <tr>
     <th id="FInsert" style="text-align:left">Insert</th>
     <td headers="First FInsert FThrow"><code>addFirst(e)</code></td>
     <td headers="First FInsert FValue"><code>offerFirst(e)</code></td>
     <td headers="First FInsert FBlock"><code>putFirst(e)</code></td>
     <td headers="First FInsert FTimes"><code>offerFirst(e, time, unit)</code></td>
   </tr>
   <tr>
     <th id="FRemove" style="text-align:left">Remove</th>
     <td headers="First FRemove FThrow"><code>removeFirst()</code></td>
     <td headers="First FRemove FValue"><code>pollFirst()</code></td>
     <td headers="First FRemove FBlock"><code>takeFirst()</code></td>
     <td headers="First FRemove FTimes"><code>pollFirst(time, unit)</code></td>
   </tr>
   <tr>
     <th id="FExamine" style="text-align:left">Examine</th>
     <td headers="First FExamine FThrow"><code>getFirst()</code></td>
     <td headers="First FExamine FValue"><code>peekFirst()</code></td>
     <td headers="First FExamine FBlock" style="font-style:italic">not applicable</td>
     <td headers="First FExamine FTimes" style="font-style:italic">not applicable</td>
   </tr>
   <tr>
     <th id="Last" colspan="5"> Last Element (Tail)</th>
   </tr>
   <tr>
     <td></td>
     <th id="LThrow" style="font-weight:normal; font-style: italic">Throws exception</th>
     <th id="LValue" style="font-weight:normal; font-style: italic">Special value</th>
     <th id="LBlock" style="font-weight:normal; font-style: italic">Blocks</th>
     <th id="LTimes" style="font-weight:normal; font-style: italic">Times out</th>
   </tr>
   <tr>
     <th id="LInsert" style="text-align:left">Insert</th>
     <td headers="Last LInsert LThrow"><code>addLast(e)</code></td>
     <td headers="Last LInsert LValue"><code>offerLast(e)</code></td>
     <td headers="Last LInsert LBlock"><code>putLast(e)</code></td>
     <td headers="Last LInsert LTimes"><code>offerLast(e, time, unit)</code></td>
   </tr>
   <tr>
     <th id="LRemove" style="text-align:left">Remove</th>
     <td headers="Last LRemove LThrow"><code>removeLast()</code></td>
     <td headers="Last LRemove LValue"><code>pollLast()</code></td>
     <td headers="Last LRemove LBlock"><code>takeLast()</code></td>
     <td headers="Last LRemove LTimes"><code>pollLast(time, unit)</code></td>
   </tr>
   <tr>
     <th id="LExamine" style="text-align:left">Examine</th>
     <td headers="Last LExamine LThrow"><code>getLast()</code></td>
     <td headers="Last LExamine LValue"><code>peekLast()</code></td>
     <td headers="Last LExamine LBlock" style="font-style:italic">not applicable</td>
     <td headers="Last LExamine LTimes" style="font-style:italic">not applicable</td>
   </tr>
  </table>
  
 <p>Like any <code>BlockingQueue</code>, a <code>BlockingDeque</code> is thread safe,
  does not permit null elements, and may (or may not) be
  capacity-constrained. 
 <p>A <code>BlockingDeque</code> implementation may be used directly as a FIFO 
 <code>BlockingQueue</code>. The methods inherited from the 
 <code>BlockingQueue</code> interface are precisely equivalent to 
 <code>BlockingDeque</code> methods as indicated in the following table: 
 <table class="plain">
  <caption>Comparison of BlockingQueue and BlockingDeque methods</caption>
   <tr>
     <td></td>
     <th id="BQueue"> <code>BlockingQueue</code> Method</th>
     <th id="BDeque"> Equivalent <code>BlockingDeque</code> Method</th>
   </tr>
   <tr>
     <th id="Insert" rowspan="4" style="text-align:left; vertical-align:top">Insert</th>
     <th id="add" style="font-weight:normal; text-align:left"><code>add(e)</code></th>
     <td headers="Insert BDeque add"><code>addLast(e)</code></td>
   </tr>
   <tr>
     <th id="offer1" style="font-weight:normal; text-align:left"><code>offer(e)</code></th>
     <td headers="Insert BDeque offer1"><code>offerLast(e)</code></td>
   </tr>
   <tr>
     <th id="put" style="font-weight:normal; text-align:left"><code>put(e)</code></th>
     <td headers="Insert BDeque put"><code>putLast(e)</code></td>
   </tr>
   <tr>
     <th id="offer2" style="font-weight:normal; text-align:left"><code>offer(e, time, unit)</code></th>
     <td headers="Insert BDeque offer2"><code>offerLast(e, time, unit)</code></td>
   </tr>
   <tr>
     <th id="Remove" rowspan="4" style="text-align:left; vertical-align:top">Remove</th>
     <th id="remove" style="font-weight:normal; text-align:left"><code>remove()</code></th>
     <td headers="Remove BDeque remove"><code>removeFirst()</code></td>
   </tr>
   <tr>
     <th id="poll1" style="font-weight:normal; text-align:left"><code>poll()</code></th>
     <td headers="Remove BDeque poll1"><code>pollFirst()</code></td>
   </tr>
   <tr>
     <th id="take" style="font-weight:normal; text-align:left"><code>take()</code></th>
     <td headers="Remove BDeque take"><code>takeFirst()</code></td>
   </tr>
   <tr>
     <th id="poll2" style="font-weight:normal; text-align:left"><code>poll(time, unit)</code></th>
     <td headers="Remove BDeque poll2"><code>pollFirst(time, unit)</code></td>
   </tr>
   <tr>
     <th id="Examine" rowspan="2" style="text-align:left; vertical-align:top">Examine</th>
     <th id="element" style="font-weight:normal; text-align:left"><code>element()</code></th>
     <td headers="Examine BDeque element"><code>getFirst()</code></td>
   </tr>
   <tr>
     <th id="peek" style="font-weight:normal; text-align:left"><code>peek()</code></th>
     <td headers="Examine BDeque peek"><code>peekFirst()</code></td>
   </tr>
  </table>
  
 <p>Memory consistency effects: As with other concurrent
  collections, actions in a thread prior to placing an object into a 
 <code>BlockingDeque</code>
  <a href="package-summary.html#MemoryVisibility"><i>happen-before</i></a>
  actions subsequent to the access or removal of that element from the 
 <code>BlockingDeque</code> in another thread. 
 <p>This interface is a member of the 
 <a href="{@@docRoot}/java.base/java/util/package-summary.html#CollectionsFramework">
  Java Collections Framework</a>.
 @since 1.6
 @author Doug Lea
 */
@protocol JavaUtilConcurrentBlockingDeque < JavaUtilConcurrentBlockingQueue, JavaUtilDeque, JavaObject >

/*!
 @brief Inserts the specified element at the front of this deque if it is
  possible to do so immediately without violating capacity restrictions,
  throwing an <code>IllegalStateException</code> if no space is currently
  available.When using a capacity-restricted deque, it is generally
  preferable to use <code>offerFirst</code>.
 @param e the element to add
 @throw IllegalStateException
 @throw ClassCastException
 @throw NullPointerExceptionif the specified element is null
 @throw IllegalArgumentException
 */
- (void)addFirstWithId:(id)e;

/*!
 @brief Inserts the specified element at the end of this deque if it is
  possible to do so immediately without violating capacity restrictions,
  throwing an <code>IllegalStateException</code> if no space is currently
  available.When using a capacity-restricted deque, it is generally
  preferable to use <code>offerLast</code>.
 @param e the element to add
 @throw IllegalStateException
 @throw ClassCastException
 @throw NullPointerExceptionif the specified element is null
 @throw IllegalArgumentException
 */
- (void)addLastWithId:(id)e;

/*!
 @brief Inserts the specified element at the front of this deque if it is
  possible to do so immediately without violating capacity restrictions,
  returning <code>true</code> upon success and <code>false</code> if no space is
  currently available.
 When using a capacity-restricted deque, this method is generally
  preferable to the <code>addFirst</code> method, which can
  fail to insert an element only by throwing an exception.
 @param e the element to add
 @throw ClassCastException
 @throw NullPointerExceptionif the specified element is null
 @throw IllegalArgumentException
 */
- (jboolean)offerFirstWithId:(id)e;

/*!
 @brief Inserts the specified element at the end of this deque if it is
  possible to do so immediately without violating capacity restrictions,
  returning <code>true</code> upon success and <code>false</code> if no space is
  currently available.
 When using a capacity-restricted deque, this method is generally
  preferable to the <code>addLast</code> method, which can
  fail to insert an element only by throwing an exception.
 @param e the element to add
 @throw ClassCastException
 @throw NullPointerExceptionif the specified element is null
 @throw IllegalArgumentException
 */
- (jboolean)offerLastWithId:(id)e;

/*!
 @brief Inserts the specified element at the front of this deque,
  waiting if necessary for space to become available.
 @param e the element to add
 @throw InterruptedExceptionif interrupted while waiting
 @throw ClassCastExceptionif the class of the specified element
          prevents it from being added to this deque
 @throw NullPointerExceptionif the specified element is null
 @throw IllegalArgumentExceptionif some property of the specified
          element prevents it from being added to this deque
 */
- (void)putFirstWithId:(id)e;

/*!
 @brief Inserts the specified element at the end of this deque,
  waiting if necessary for space to become available.
 @param e the element to add
 @throw InterruptedExceptionif interrupted while waiting
 @throw ClassCastExceptionif the class of the specified element
          prevents it from being added to this deque
 @throw NullPointerExceptionif the specified element is null
 @throw IllegalArgumentExceptionif some property of the specified
          element prevents it from being added to this deque
 */
- (void)putLastWithId:(id)e;

/*!
 @brief Inserts the specified element at the front of this deque,
  waiting up to the specified wait time if necessary for space to
  become available.
 @param e the element to add
 @param timeout how long to wait before giving up, in units of         
 <code>unit</code>
 @param unit a <code>TimeUnit</code>  determining how to interpret the
          <code>timeout</code>  parameter
 @return <code>true</code> if successful, or <code>false</code> if
          the specified waiting time elapses before space is available
 @throw InterruptedExceptionif interrupted while waiting
 @throw ClassCastExceptionif the class of the specified element
          prevents it from being added to this deque
 @throw NullPointerExceptionif the specified element is null
 @throw IllegalArgumentExceptionif some property of the specified
          element prevents it from being added to this deque
 */
- (jboolean)offerFirstWithId:(id)e
                    withLong:(jlong)timeout
withJavaUtilConcurrentTimeUnit:(JavaUtilConcurrentTimeUnit *)unit;

/*!
 @brief Inserts the specified element at the end of this deque,
  waiting up to the specified wait time if necessary for space to
  become available.
 @param e the element to add
 @param timeout how long to wait before giving up, in units of         
 <code>unit</code>
 @param unit a <code>TimeUnit</code>  determining how to interpret the
          <code>timeout</code>  parameter
 @return <code>true</code> if successful, or <code>false</code> if
          the specified waiting time elapses before space is available
 @throw InterruptedExceptionif interrupted while waiting
 @throw ClassCastExceptionif the class of the specified element
          prevents it from being added to this deque
 @throw NullPointerExceptionif the specified element is null
 @throw IllegalArgumentExceptionif some property of the specified
          element prevents it from being added to this deque
 */
- (jboolean)offerLastWithId:(id)e
                   withLong:(jlong)timeout
withJavaUtilConcurrentTimeUnit:(JavaUtilConcurrentTimeUnit *)unit;

/*!
 @brief Retrieves and removes the first element of this deque, waiting
  if necessary until an element becomes available.
 @return the head of this deque
 @throw InterruptedExceptionif interrupted while waiting
 */
- (id)takeFirst;

/*!
 @brief Retrieves and removes the last element of this deque, waiting
  if necessary until an element becomes available.
 @return the tail of this deque
 @throw InterruptedExceptionif interrupted while waiting
 */
- (id)takeLast;

/*!
 @brief Retrieves and removes the first element of this deque, waiting
  up to the specified wait time if necessary for an element to
  become available.
 @param timeout how long to wait before giving up, in units of         
 <code>unit</code>
 @param unit a <code>TimeUnit</code>  determining how to interpret the
          <code>timeout</code>  parameter
 @return the head of this deque, or <code>null</code> if the specified
          waiting time elapses before an element is available
 @throw InterruptedExceptionif interrupted while waiting
 */
- (id)pollFirstWithLong:(jlong)timeout
withJavaUtilConcurrentTimeUnit:(JavaUtilConcurrentTimeUnit *)unit;

/*!
 @brief Retrieves and removes the last element of this deque, waiting
  up to the specified wait time if necessary for an element to
  become available.
 @param timeout how long to wait before giving up, in units of         
 <code>unit</code>
 @param unit a <code>TimeUnit</code>  determining how to interpret the
          <code>timeout</code>  parameter
 @return the tail of this deque, or <code>null</code> if the specified
          waiting time elapses before an element is available
 @throw InterruptedExceptionif interrupted while waiting
 */
- (id)pollLastWithLong:(jlong)timeout
withJavaUtilConcurrentTimeUnit:(JavaUtilConcurrentTimeUnit *)unit;

/*!
 @brief Removes the first occurrence of the specified element from this deque.
 If the deque does not contain the element, it is unchanged.
  More formally, removes the first element <code>e</code> such that 
 <code>o.equals(e)</code> (if such an element exists).
  Returns <code>true</code> if this deque contained the specified element
  (or equivalently, if this deque changed as a result of the call).
 @param o element to be removed from this deque, if present
 @return <code>true</code> if an element was removed as a result of this call
 @throw ClassCastExceptionif the class of the specified element
          is incompatible with this deque
  (<a href="{@@docRoot}/java.base/java/util/Collection.html#optional-restrictions">optional</a>)
 @throw NullPointerExceptionif the specified element is null
  (<a href="{@@docRoot}/java.base/java/util/Collection.html#optional-restrictions">optional</a>)
 */
- (jboolean)removeFirstOccurrenceWithId:(id)o;

/*!
 @brief Removes the last occurrence of the specified element from this deque.
 If the deque does not contain the element, it is unchanged.
  More formally, removes the last element <code>e</code> such that 
 <code>o.equals(e)</code> (if such an element exists).
  Returns <code>true</code> if this deque contained the specified element
  (or equivalently, if this deque changed as a result of the call).
 @param o element to be removed from this deque, if present
 @return <code>true</code> if an element was removed as a result of this call
 @throw ClassCastExceptionif the class of the specified element
          is incompatible with this deque
  (<a href="{@@docRoot}/java.base/java/util/Collection.html#optional-restrictions">optional</a>)
 @throw NullPointerExceptionif the specified element is null
  (<a href="{@@docRoot}/java.base/java/util/Collection.html#optional-restrictions">optional</a>)
 */
- (jboolean)removeLastOccurrenceWithId:(id)o;

/*!
 @brief Inserts the specified element into the queue represented by this deque
  (in other words, at the tail of this deque) if it is possible to do so
  immediately without violating capacity restrictions, returning 
 <code>true</code> upon success and throwing an 
 <code>IllegalStateException</code> if no space is currently available.
 When using a capacity-restricted deque, it is generally preferable to
  use <code>offer</code>.
  
 <p>This method is equivalent to <code>addLast</code>.
 @param e the element to add
 @throw IllegalStateException
 @throw ClassCastExceptionif the class of the specified element
          prevents it from being added to this deque
 @throw NullPointerExceptionif the specified element is null
 @throw IllegalArgumentExceptionif some property of the specified
          element prevents it from being added to this deque
 */
- (jboolean)addWithId:(id)e;

/*!
 @brief Inserts the specified element into the queue represented by this deque
  (in other words, at the tail of this deque) if it is possible to do so
  immediately without violating capacity restrictions, returning 
 <code>true</code> upon success and <code>false</code> if no space is currently
  available.When using a capacity-restricted deque, this method is
  generally preferable to the <code>add</code> method, which can fail to
  insert an element only by throwing an exception.
 <p>This method is equivalent to <code>offerLast</code>.
 @param e the element to add
 @throw ClassCastExceptionif the class of the specified element
          prevents it from being added to this deque
 @throw NullPointerExceptionif the specified element is null
 @throw IllegalArgumentExceptionif some property of the specified
          element prevents it from being added to this deque
 */
- (jboolean)offerWithId:(id)e;

/*!
 @brief Inserts the specified element into the queue represented by this deque
  (in other words, at the tail of this deque), waiting if necessary for
  space to become available.
 <p>This method is equivalent to <code>putLast</code>.
 @param e the element to add
 @throw InterruptedException
 @throw ClassCastExceptionif the class of the specified element
          prevents it from being added to this deque
 @throw NullPointerExceptionif the specified element is null
 @throw IllegalArgumentExceptionif some property of the specified
          element prevents it from being added to this deque
 */
- (void)putWithId:(id)e;

/*!
 @brief Inserts the specified element into the queue represented by this deque
  (in other words, at the tail of this deque), waiting up to the
  specified wait time if necessary for space to become available.
 <p>This method is equivalent to 
 <code>offerLast</code>.
 @param e the element to add
 @return <code>true</code> if the element was added to this deque, else
          <code>false</code>
 @throw InterruptedException
 @throw ClassCastExceptionif the class of the specified element
          prevents it from being added to this deque
 @throw NullPointerExceptionif the specified element is null
 @throw IllegalArgumentExceptionif some property of the specified
          element prevents it from being added to this deque
 */
- (jboolean)offerWithId:(id)e
               withLong:(jlong)timeout
withJavaUtilConcurrentTimeUnit:(JavaUtilConcurrentTimeUnit *)unit;

/*!
 @brief Retrieves and removes the head of the queue represented by this deque
  (in other words, the first element of this deque).
 This method differs from <code>poll()</code> only in that it
  throws an exception if this deque is empty. 
 <p>This method is equivalent to <code>removeFirst</code>.
 @return the head of the queue represented by this deque
 @throw NoSuchElementExceptionif this deque is empty
 */
- (id)remove;

/*!
 @brief Retrieves and removes the head of the queue represented by this deque
  (in other words, the first element of this deque), or returns 
 <code>null</code> if this deque is empty.
 <p>This method is equivalent to <code>pollFirst()</code>.
 @return the head of this deque, or <code>null</code> if this deque is empty
 */
- (id)poll;

/*!
 @brief Retrieves and removes the head of the queue represented by this deque
  (in other words, the first element of this deque), waiting if
  necessary until an element becomes available.
 <p>This method is equivalent to <code>takeFirst</code>.
 @return the head of this deque
 @throw InterruptedExceptionif interrupted while waiting
 */
- (id)take;

/*!
 @brief Retrieves and removes the head of the queue represented by this deque
  (in other words, the first element of this deque), waiting up to the
  specified wait time if necessary for an element to become available.
 <p>This method is equivalent to 
 <code>pollFirst</code>.
 @return the head of this deque, or <code>null</code> if the
          specified waiting time elapses before an element is available
 @throw InterruptedExceptionif interrupted while waiting
 */
- (id)pollWithLong:(jlong)timeout
withJavaUtilConcurrentTimeUnit:(JavaUtilConcurrentTimeUnit *)unit;

/*!
 @brief Retrieves, but does not remove, the head of the queue represented by
  this deque (in other words, the first element of this deque).
 This method differs from <code>peek</code> only in that it throws an
  exception if this deque is empty. 
 <p>This method is equivalent to <code>getFirst</code>.
 @return the head of this deque
 @throw NoSuchElementExceptionif this deque is empty
 */
- (id)element;

/*!
 @brief Retrieves, but does not remove, the head of the queue represented by
  this deque (in other words, the first element of this deque), or
  returns <code>null</code> if this deque is empty.
 <p>This method is equivalent to <code>peekFirst</code>.
 @return the head of this deque, or <code>null</code> if this deque is empty
 */
- (id)peek;

/*!
 @brief Removes the first occurrence of the specified element from this deque.
 If the deque does not contain the element, it is unchanged.
  More formally, removes the first element <code>e</code> such that 
 <code>o.equals(e)</code> (if such an element exists).
  Returns <code>true</code> if this deque contained the specified element
  (or equivalently, if this deque changed as a result of the call). 
 <p>This method is equivalent to 
 <code>removeFirstOccurrence</code>.
 @param o element to be removed from this deque, if present
 @return <code>true</code> if this deque changed as a result of the call
 @throw ClassCastExceptionif the class of the specified element
          is incompatible with this deque
  (<a href="{@@docRoot}/java.base/java/util/Collection.html#optional-restrictions">optional</a>)
 @throw NullPointerExceptionif the specified element is null
  (<a href="{@@docRoot}/java.base/java/util/Collection.html#optional-restrictions">optional</a>)
 */
- (jboolean)removeWithId:(id)o;

/*!
 @brief Returns <code>true</code> if this deque contains the specified element.
 More formally, returns <code>true</code> if and only if this deque contains
  at least one element <code>e</code> such that <code>o.equals(e)</code>.
 @param o object to be checked for containment in this deque
 @return <code>true</code> if this deque contains the specified element
 @throw ClassCastExceptionif the class of the specified element
          is incompatible with this deque
  (<a href="{@@docRoot}/java.base/java/util/Collection.html#optional-restrictions">optional</a>)
 @throw NullPointerExceptionif the specified element is null
  (<a href="{@@docRoot}/java.base/java/util/Collection.html#optional-restrictions">optional</a>)
 */
- (jboolean)containsWithId:(id)o;

/*!
 @brief Returns the number of elements in this deque.
 @return the number of elements in this deque
 */
- (jint)size;

/*!
 @brief Returns an iterator over the elements in this deque in proper sequence.
 The elements will be returned in order from first (head) to last (tail).
 @return an iterator over the elements in this deque in proper sequence
 */
- (id<JavaUtilIterator>)iterator;

/*!
 @brief Pushes an element onto the stack represented by this deque (in other
  words, at the head of this deque) if it is possible to do so
  immediately without violating capacity restrictions, throwing an 
 <code>IllegalStateException</code> if no space is currently available.
 <p>This method is equivalent to <code>addFirst</code>.
 @throw IllegalStateException
 @throw ClassCastException
 @throw NullPointerExceptionif the specified element is null
 @throw IllegalArgumentException
 */
- (void)pushWithId:(id)e;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaUtilConcurrentBlockingDeque)

J2OBJC_TYPE_LITERAL_HEADER(JavaUtilConcurrentBlockingDeque)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_JavaUtilConcurrentBlockingDeque")
