//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/jsr305/build_result/java/javax/annotation/meta/TypeQualifierNickname.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JavaxAnnotationMetaTypeQualifierNickname")
#ifdef RESTRICT_JavaxAnnotationMetaTypeQualifierNickname
#define INCLUDE_ALL_JavaxAnnotationMetaTypeQualifierNickname 0
#else
#define INCLUDE_ALL_JavaxAnnotationMetaTypeQualifierNickname 1
#endif
#undef RESTRICT_JavaxAnnotationMetaTypeQualifierNickname

#if !defined (JavaxAnnotationMetaTypeQualifierNickname_) && (INCLUDE_ALL_JavaxAnnotationMetaTypeQualifierNickname || defined(INCLUDE_JavaxAnnotationMetaTypeQualifierNickname))
#define JavaxAnnotationMetaTypeQualifierNickname_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;

@protocol JavaxAnnotationMetaTypeQualifierNickname < JavaLangAnnotationAnnotation >

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface JavaxAnnotationMetaTypeQualifierNickname : NSObject < JavaxAnnotationMetaTypeQualifierNickname >

@end

J2OBJC_EMPTY_STATIC_INIT(JavaxAnnotationMetaTypeQualifierNickname)

FOUNDATION_EXPORT id<JavaxAnnotationMetaTypeQualifierNickname> create_JavaxAnnotationMetaTypeQualifierNickname(void);

J2OBJC_TYPE_LITERAL_HEADER(JavaxAnnotationMetaTypeQualifierNickname)

#endif

#pragma pop_macro("INCLUDE_ALL_JavaxAnnotationMetaTypeQualifierNickname")
