//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/junit/build_result/java/org/junit/internal/ComparisonCriteria.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgJunitInternalComparisonCriteria")
#ifdef RESTRICT_OrgJunitInternalComparisonCriteria
#define INCLUDE_ALL_OrgJunitInternalComparisonCriteria 0
#else
#define INCLUDE_ALL_OrgJunitInternalComparisonCriteria 1
#endif
#undef RESTRICT_OrgJunitInternalComparisonCriteria

#if !defined (OrgJunitInternalComparisonCriteria_) && (INCLUDE_ALL_OrgJunitInternalComparisonCriteria || defined(INCLUDE_OrgJunitInternalComparisonCriteria))
#define OrgJunitInternalComparisonCriteria_

@interface OrgJunitInternalComparisonCriteria : NSObject

#pragma mark Public

- (instancetype)init;

- (void)arrayEqualsWithNSString:(NSString *)message
                         withId:(id)expecteds
                         withId:(id)actuals;

#pragma mark Protected

- (void)assertElementsEqualWithId:(id)expected
                           withId:(id)actual;

@end

J2OBJC_STATIC_INIT(OrgJunitInternalComparisonCriteria)

FOUNDATION_EXPORT void OrgJunitInternalComparisonCriteria_init(OrgJunitInternalComparisonCriteria *self);

J2OBJC_TYPE_LITERAL_HEADER(OrgJunitInternalComparisonCriteria)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgJunitInternalComparisonCriteria")
