//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/build_result/java/com/google/common/util/concurrent/AbstractFuture.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleCommonUtilConcurrentAbstractFuture")
#ifdef RESTRICT_ComGoogleCommonUtilConcurrentAbstractFuture
#define INCLUDE_ALL_ComGoogleCommonUtilConcurrentAbstractFuture 0
#else
#define INCLUDE_ALL_ComGoogleCommonUtilConcurrentAbstractFuture 1
#endif
#undef RESTRICT_ComGoogleCommonUtilConcurrentAbstractFuture
#ifdef INCLUDE_ComGoogleCommonUtilConcurrentAbstractFuture_TrustedFuture
#define INCLUDE_ComGoogleCommonUtilConcurrentAbstractFuture 1
#define INCLUDE_ComGoogleCommonUtilConcurrentAbstractFuture_Trusted 1
#endif

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (ComGoogleCommonUtilConcurrentAbstractFuture_) && (INCLUDE_ALL_ComGoogleCommonUtilConcurrentAbstractFuture || defined(INCLUDE_ComGoogleCommonUtilConcurrentAbstractFuture))
#define ComGoogleCommonUtilConcurrentAbstractFuture_

#define RESTRICT_ComGoogleCommonUtilConcurrentInternalInternalFutureFailureAccess 1
#define INCLUDE_ComGoogleCommonUtilConcurrentInternalInternalFutureFailureAccess 1
#include "com/google/common/util/concurrent/internal/InternalFutureFailureAccess.h"

#define RESTRICT_ComGoogleCommonUtilConcurrentListenableFuture 1
#define INCLUDE_ComGoogleCommonUtilConcurrentListenableFuture 1
#include "com/google/common/util/concurrent/ListenableFuture.h"

@class JavaLangBoolean;
@class JavaLangLong;
@class JavaLangThrowable;
@class JavaUtilConcurrentTimeUnit;
@protocol JavaLangRunnable;
@protocol JavaUtilConcurrentExecutor;
@protocol JavaUtilConcurrentFuture;

@interface ComGoogleCommonUtilConcurrentAbstractFuture : ComGoogleCommonUtilConcurrentInternalInternalFutureFailureAccess < ComGoogleCommonUtilConcurrentListenableFuture >

#pragma mark Public

- (void)addListenerWithJavaLangRunnable:(id<JavaLangRunnable>)listener
         withJavaUtilConcurrentExecutor:(id<JavaUtilConcurrentExecutor>)executor;

- (jboolean)cancelWithBoolean:(jboolean)mayInterruptIfRunning;

- (id)get;

- (id)getWithLong:(jlong)timeout
withJavaUtilConcurrentTimeUnit:(JavaUtilConcurrentTimeUnit *)unit;

- (jboolean)isCancelled;

- (jboolean)isDone;

- (NSString *)description;

#pragma mark Protected

- (instancetype)init;

- (void)afterDone;

- (void)interruptTask;

- (NSString *)pendingToString;

- (jboolean)setWithId:(id)value;

- (jboolean)setExceptionWithJavaLangThrowable:(JavaLangThrowable *)throwable;

- (jboolean)setFutureWithComGoogleCommonUtilConcurrentListenableFuture:(id<ComGoogleCommonUtilConcurrentListenableFuture>)future;

- (JavaLangThrowable *)tryInternalFastPathGetFailure;

- (jboolean)wasInterrupted;

#pragma mark Package-Private

- (void)maybePropagateCancellationToWithJavaUtilConcurrentFuture:(id<JavaUtilConcurrentFuture>)related;

@end

J2OBJC_STATIC_INIT(ComGoogleCommonUtilConcurrentAbstractFuture)

inline jboolean ComGoogleCommonUtilConcurrentAbstractFuture_get_GENERATE_CANCELLATION_CAUSES(void);
/*! INTERNAL ONLY - Use accessor function from above. */
FOUNDATION_EXPORT jboolean ComGoogleCommonUtilConcurrentAbstractFuture_GENERATE_CANCELLATION_CAUSES;
J2OBJC_STATIC_FIELD_PRIMITIVE_FINAL(ComGoogleCommonUtilConcurrentAbstractFuture, GENERATE_CANCELLATION_CAUSES, jboolean)

FOUNDATION_EXPORT void ComGoogleCommonUtilConcurrentAbstractFuture_init(ComGoogleCommonUtilConcurrentAbstractFuture *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonUtilConcurrentAbstractFuture)

#endif

#if !defined (ComGoogleCommonUtilConcurrentAbstractFuture_Trusted_) && (INCLUDE_ALL_ComGoogleCommonUtilConcurrentAbstractFuture || defined(INCLUDE_ComGoogleCommonUtilConcurrentAbstractFuture_Trusted))
#define ComGoogleCommonUtilConcurrentAbstractFuture_Trusted_

#define RESTRICT_ComGoogleCommonUtilConcurrentListenableFuture 1
#define INCLUDE_ComGoogleCommonUtilConcurrentListenableFuture 1
#include "com/google/common/util/concurrent/ListenableFuture.h"

@protocol ComGoogleCommonUtilConcurrentAbstractFuture_Trusted < ComGoogleCommonUtilConcurrentListenableFuture, JavaObject >

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonUtilConcurrentAbstractFuture_Trusted)

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonUtilConcurrentAbstractFuture_Trusted)

#endif

#if !defined (ComGoogleCommonUtilConcurrentAbstractFuture_TrustedFuture_) && (INCLUDE_ALL_ComGoogleCommonUtilConcurrentAbstractFuture || defined(INCLUDE_ComGoogleCommonUtilConcurrentAbstractFuture_TrustedFuture))
#define ComGoogleCommonUtilConcurrentAbstractFuture_TrustedFuture_

@class JavaLangBoolean;
@class JavaLangLong;
@class JavaUtilConcurrentTimeUnit;
@protocol JavaLangRunnable;
@protocol JavaUtilConcurrentExecutor;

@interface ComGoogleCommonUtilConcurrentAbstractFuture_TrustedFuture : ComGoogleCommonUtilConcurrentAbstractFuture < ComGoogleCommonUtilConcurrentAbstractFuture_Trusted >

#pragma mark Public

- (void)addListenerWithJavaLangRunnable:(id<JavaLangRunnable>)listener
         withJavaUtilConcurrentExecutor:(id<JavaUtilConcurrentExecutor>)executor;

- (jboolean)cancelWithBoolean:(jboolean)mayInterruptIfRunning;

- (id)get;

- (id)getWithLong:(jlong)timeout
withJavaUtilConcurrentTimeUnit:(JavaUtilConcurrentTimeUnit *)unit;

- (jboolean)isCancelled;

- (jboolean)isDone;

#pragma mark Package-Private

- (instancetype)init;

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleCommonUtilConcurrentAbstractFuture_TrustedFuture)

FOUNDATION_EXPORT void ComGoogleCommonUtilConcurrentAbstractFuture_TrustedFuture_init(ComGoogleCommonUtilConcurrentAbstractFuture_TrustedFuture *self);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleCommonUtilConcurrentAbstractFuture_TrustedFuture)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_ComGoogleCommonUtilConcurrentAbstractFuture")
