//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xml/serializer/utils/SerializerMessages_ru.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXmlSerializerUtilsSerializerMessages_ru")
#ifdef RESTRICT_OrgApacheXmlSerializerUtilsSerializerMessages_ru
#define INCLUDE_ALL_OrgApacheXmlSerializerUtilsSerializerMessages_ru 0
#else
#define INCLUDE_ALL_OrgApacheXmlSerializerUtilsSerializerMessages_ru 1
#endif
#undef RESTRICT_OrgApacheXmlSerializerUtilsSerializerMessages_ru

#if !defined (OrgApacheXmlSerializerUtilsSerializerMessages_ru_) && (INCLUDE_ALL_OrgApacheXmlSerializerUtilsSerializerMessages_ru || defined(INCLUDE_OrgApacheXmlSerializerUtilsSerializerMessages_ru))
#define OrgApacheXmlSerializerUtilsSerializerMessages_ru_

#define RESTRICT_JavaUtilListResourceBundle 1
#define INCLUDE_JavaUtilListResourceBundle 1
#include "java/util/ListResourceBundle.h"

@class IOSObjectArray;

@interface OrgApacheXmlSerializerUtilsSerializerMessages_ru : JavaUtilListResourceBundle

#pragma mark Public

- (instancetype)init;

- (IOSObjectArray *)getContents;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXmlSerializerUtilsSerializerMessages_ru)

FOUNDATION_EXPORT void OrgApacheXmlSerializerUtilsSerializerMessages_ru_init(OrgApacheXmlSerializerUtilsSerializerMessages_ru *self);

FOUNDATION_EXPORT OrgApacheXmlSerializerUtilsSerializerMessages_ru *new_OrgApacheXmlSerializerUtilsSerializerMessages_ru_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXmlSerializerUtilsSerializerMessages_ru *create_OrgApacheXmlSerializerUtilsSerializerMessages_ru_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXmlSerializerUtilsSerializerMessages_ru)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXmlSerializerUtilsSerializerMessages_ru")
