//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: android/platform/libcore/ojluni/src/main/java/java/security/interfaces/XECPublicKey.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_JavaSecurityInterfacesXECPublicKey")
#ifdef RESTRICT_JavaSecurityInterfacesXECPublicKey
#define INCLUDE_ALL_JavaSecurityInterfacesXECPublicKey 0
#else
#define INCLUDE_ALL_JavaSecurityInterfacesXECPublicKey 1
#endif
#undef RESTRICT_JavaSecurityInterfacesXECPublicKey

#if __has_feature(nullability)
#pragma clang diagnostic push
#pragma GCC diagnostic ignored "-Wnullability"
#pragma GCC diagnostic ignored "-Wnullability-completeness"
#endif

#if !defined (JavaSecurityInterfacesXECPublicKey_) && (INCLUDE_ALL_JavaSecurityInterfacesXECPublicKey || defined(INCLUDE_JavaSecurityInterfacesXECPublicKey))
#define JavaSecurityInterfacesXECPublicKey_

#define RESTRICT_JavaSecurityInterfacesXECKey 1
#define INCLUDE_JavaSecurityInterfacesXECKey 1
#include "java/security/interfaces/XECKey.h"

#define RESTRICT_JavaSecurityPublicKey 1
#define INCLUDE_JavaSecurityPublicKey 1
#include "java/security/PublicKey.h"

@class JavaMathBigInteger;

/*!
 @brief An interface for an elliptic curve public key as defined by RFC 7748.
 These keys are distinct from the keys represented by <code>ECPublicKey</code>,
  and they are intended for use with algorithms based on RFC 7748 such as the
  XDH <code>KeyAgreement</code> algorithm.
  An XEC public key is a particular point on the curve, which is represented
  using only its u-coordinate as described in RFC 7748. A u-coordinate is an
  element of the field of integers modulo some value that is determined by
  the algorithm parameters. This field element is represented by a BigInteger
  which may hold any value. That is, the BigInteger is not restricted to the
  range of canonical field elements.
 @since 11
 */
@protocol JavaSecurityInterfacesXECPublicKey < JavaSecurityInterfacesXECKey, JavaSecurityPublicKey, JavaObject >

/*!
 @brief Get the u coordinate of the point.
 @return the u-coordinate, represented using a BigInteger which may hold
           any value
 */
- (JavaMathBigInteger *)getU;

@end

J2OBJC_EMPTY_STATIC_INIT(JavaSecurityInterfacesXECPublicKey)

J2OBJC_TYPE_LITERAL_HEADER(JavaSecurityInterfacesXECPublicKey)

#endif


#if __has_feature(nullability)
#pragma clang diagnostic pop
#endif
#pragma pop_macro("INCLUDE_ALL_JavaSecurityInterfacesXECPublicKey")
