//
// JUnit.h
//

#include <junit/extensions/ActiveTestSuite.h>
#include <junit/extensions/RepeatedTest.h>
#include <junit/extensions/TestDecorator.h>
#include <junit/extensions/TestSetup.h>
#include <junit/framework/Assert.h>
#include <junit/framework/AssertionFailedError.h>
#include <junit/framework/ComparisonCompactor.h>
#include <junit/framework/ComparisonFailure.h>
#include <junit/framework/JUnit4TestAdapter.h>
#include <junit/framework/JUnit4TestAdapterCache.h>
#include <junit/framework/JUnit4TestCaseFacade.h>
#include <junit/framework/Protectable.h>
#include <junit/framework/Test.h>
#include <junit/framework/TestCase.h>
#include <junit/framework/TestFailure.h>
#include <junit/framework/TestListener.h>
#include <junit/framework/TestResult.h>
#include <junit/framework/TestSuite.h>
#include <junit/runner/BaseTestRunner.h>
#include <junit/runner/TestRunListener.h>
#include <junit/runner/Version.h>
#include <junit/textui/ResultPrinter.h>
#include <junit/textui/TestRunner.h>
#include <org/junit/After.h>
#include <org/junit/AfterClass.h>
#include <org/junit/Assert.h>
#include <org/junit/Assume.h>
#include <org/junit/AssumptionViolatedException.h>
#include <org/junit/Before.h>
#include <org/junit/BeforeClass.h>
#include <org/junit/ClassRule.h>
#include <org/junit/ComparisonFailure.h>
#include <org/junit/FixMethodOrder.h>
#include <org/junit/Ignore.h>
#include <org/junit/Rule.h>
#include <org/junit/Test.h>
#include <org/junit/TestCouldNotBeSkippedException.h>
#include <org/junit/experimental/ParallelComputer.h>
#include <org/junit/experimental/categories/Categories.h>
#include <org/junit/experimental/categories/Category.h>
#include <org/junit/experimental/categories/CategoryFilterFactory.h>
#include <org/junit/experimental/categories/CategoryValidator.h>
#include <org/junit/experimental/categories/ExcludeCategories.h>
#include <org/junit/experimental/categories/IncludeCategories.h>
#include <org/junit/experimental/max/CouldNotReadCoreException.h>
#include <org/junit/experimental/max/MaxCore.h>
#include <org/junit/experimental/max/MaxHistory.h>
#include <org/junit/experimental/results/FailureList.h>
#include <org/junit/experimental/results/PrintableResult.h>
#include <org/junit/experimental/results/ResultMatchers.h>
#include <org/junit/experimental/runners/Enclosed.h>
#include <org/junit/experimental/theories/DataPoint.h>
#include <org/junit/experimental/theories/DataPoints.h>
#include <org/junit/experimental/theories/FromDataPoints.h>
#include <org/junit/experimental/theories/ParameterSignature.h>
#include <org/junit/experimental/theories/ParameterSupplier.h>
#include <org/junit/experimental/theories/ParametersSuppliedBy.h>
#include <org/junit/experimental/theories/PotentialAssignment.h>
#include <org/junit/experimental/theories/Theories.h>
#include <org/junit/experimental/theories/Theory.h>
#include <org/junit/experimental/theories/internal/AllMembersSupplier.h>
#include <org/junit/experimental/theories/internal/Assignments.h>
#include <org/junit/experimental/theories/internal/BooleanSupplier.h>
#include <org/junit/experimental/theories/internal/EnumSupplier.h>
#include <org/junit/experimental/theories/internal/ParameterizedAssertionError.h>
#include <org/junit/experimental/theories/internal/SpecificDataPointsSupplier.h>
#include <org/junit/experimental/theories/suppliers/TestedOn.h>
#include <org/junit/experimental/theories/suppliers/TestedOnSupplier.h>
#include <org/junit/function/ThrowingRunnable.h>
#include <org/junit/internal/ArrayComparisonFailure.h>
#include <org/junit/internal/AssumptionViolatedException.h>
#include <org/junit/internal/Checks.h>
#include <org/junit/internal/Classes.h>
#include <org/junit/internal/ComparisonCriteria.h>
#include <org/junit/internal/ExactComparisonCriteria.h>
#include <org/junit/internal/InexactComparisonCriteria.h>
#include <org/junit/internal/JUnitSystem.h>
#include <org/junit/internal/MethodSorter.h>
#include <org/junit/internal/RealSystem.h>
#include <org/junit/internal/TextListener.h>
#include <org/junit/internal/Throwables.h>
#include <org/junit/internal/builders/AllDefaultPossibilitiesBuilder.h>
#include <org/junit/internal/builders/AnnotatedBuilder.h>
#include <org/junit/internal/builders/IgnoredBuilder.h>
#include <org/junit/internal/builders/IgnoredClassRunner.h>
#include <org/junit/internal/builders/JUnit3Builder.h>
#include <org/junit/internal/builders/JUnit4Builder.h>
#include <org/junit/internal/builders/NullBuilder.h>
#include <org/junit/internal/builders/SuiteMethodBuilder.h>
#include <org/junit/internal/management/FakeRuntimeMXBean.h>
#include <org/junit/internal/management/FakeThreadMXBean.h>
#include <org/junit/internal/management/ManagementFactory.h>
#include <org/junit/internal/management/ReflectiveRuntimeMXBean.h>
#include <org/junit/internal/management/ReflectiveThreadMXBean.h>
#include <org/junit/internal/management/RuntimeMXBean.h>
#include <org/junit/internal/management/ThreadMXBean.h>
#include <org/junit/internal/matchers/StacktracePrintingMatcher.h>
#include <org/junit/internal/matchers/ThrowableCauseMatcher.h>
#include <org/junit/internal/matchers/ThrowableMessageMatcher.h>
#include <org/junit/internal/matchers/TypeSafeMatcher.h>
#include <org/junit/internal/requests/ClassRequest.h>
#include <org/junit/internal/requests/FilterRequest.h>
#include <org/junit/internal/requests/MemoizingRequest.h>
#include <org/junit/internal/requests/OrderingRequest.h>
#include <org/junit/internal/requests/SortingRequest.h>
#include <org/junit/internal/runners/ClassRoadie.h>
#include <org/junit/internal/runners/ErrorReportingRunner.h>
#include <org/junit/internal/runners/FailedBefore.h>
#include <org/junit/internal/runners/InitializationError.h>
#include <org/junit/internal/runners/JUnit38ClassRunner.h>
#include <org/junit/internal/runners/JUnit4ClassRunner.h>
#include <org/junit/internal/runners/MethodRoadie.h>
#include <org/junit/internal/runners/MethodValidator.h>
#include <org/junit/internal/runners/SuiteMethod.h>
#include <org/junit/internal/runners/TestClass.h>
#include <org/junit/internal/runners/TestMethod.h>
#include <org/junit/internal/runners/model/EachTestNotifier.h>
#include <org/junit/internal/runners/model/MultipleFailureException.h>
#include <org/junit/internal/runners/model/ReflectiveCallable.h>
#include <org/junit/internal/runners/rules/RuleMemberValidator.h>
#include <org/junit/internal/runners/rules/ValidationError.h>
#include <org/junit/internal/runners/statements/ExpectException.h>
#include <org/junit/internal/runners/statements/Fail.h>
#include <org/junit/internal/runners/statements/FailOnTimeout.h>
#include <org/junit/internal/runners/statements/InvokeMethod.h>
#include <org/junit/internal/runners/statements/RunAfters.h>
#include <org/junit/internal/runners/statements/RunBefores.h>
#include <org/junit/matchers/JUnitMatchers.h>
#include <org/junit/rules/DisableOnDebug.h>
#include <org/junit/rules/ErrorCollector.h>
#include <org/junit/rules/ExpectedException.h>
#include <org/junit/rules/ExpectedExceptionMatcherBuilder.h>
#include <org/junit/rules/ExternalResource.h>
#include <org/junit/rules/MethodRule.h>
#include <org/junit/rules/RuleChain.h>
#include <org/junit/rules/RunRules.h>
#include <org/junit/rules/Stopwatch.h>
#include <org/junit/rules/TemporaryFolder.h>
#include <org/junit/rules/TestName.h>
#include <org/junit/rules/TestRule.h>
#include <org/junit/rules/TestWatcher.h>
#include <org/junit/rules/TestWatchman.h>
#include <org/junit/rules/Timeout.h>
#include <org/junit/rules/Verifier.h>
#include <org/junit/runner/Computer.h>
#include <org/junit/runner/Describable.h>
#include <org/junit/runner/Description.h>
#include <org/junit/runner/FilterFactories.h>
#include <org/junit/runner/FilterFactory.h>
#include <org/junit/runner/FilterFactoryParams.h>
#include <org/junit/runner/JUnitCommandLineParseResult.h>
#include <org/junit/runner/JUnitCore.h>
#include <org/junit/runner/OrderWith.h>
#include <org/junit/runner/OrderWithValidator.h>
#include <org/junit/runner/Request.h>
#include <org/junit/runner/Result.h>
#include <org/junit/runner/RunWith.h>
#include <org/junit/runner/Runner.h>
#include <org/junit/runner/manipulation/Filter.h>
#include <org/junit/runner/manipulation/Filterable.h>
#include <org/junit/runner/manipulation/InvalidOrderingException.h>
#include <org/junit/runner/manipulation/NoTestsRemainException.h>
#include <org/junit/runner/manipulation/Orderable.h>
#include <org/junit/runner/manipulation/Orderer.h>
#include <org/junit/runner/manipulation/Ordering.h>
#include <org/junit/runner/manipulation/Sortable.h>
#include <org/junit/runner/manipulation/Sorter.h>
#include <org/junit/runner/notification/Failure.h>
#include <org/junit/runner/notification/RunListener.h>
#include <org/junit/runner/notification/RunNotifier.h>
#include <org/junit/runner/notification/StoppedByUserException.h>
#include <org/junit/runner/notification/SynchronizedRunListener.h>
#include <org/junit/runners/AllTests.h>
#include <org/junit/runners/BlockJUnit4ClassRunner.h>
#include <org/junit/runners/JUnit4.h>
#include <org/junit/runners/MethodSorters.h>
#include <org/junit/runners/Parameterized.h>
#include <org/junit/runners/ParentRunner.h>
#include <org/junit/runners/RuleContainer.h>
#include <org/junit/runners/Suite.h>
#include <org/junit/runners/model/Annotatable.h>
#include <org/junit/runners/model/FrameworkField.h>
#include <org/junit/runners/model/FrameworkMember.h>
#include <org/junit/runners/model/FrameworkMethod.h>
#include <org/junit/runners/model/InitializationError.h>
#include <org/junit/runners/model/InvalidTestClassError.h>
#include <org/junit/runners/model/MemberValueConsumer.h>
#include <org/junit/runners/model/MultipleFailureException.h>
#include <org/junit/runners/model/NoGenericTypeParametersValidator.h>
#include <org/junit/runners/model/RunnerBuilder.h>
#include <org/junit/runners/model/RunnerScheduler.h>
#include <org/junit/runners/model/Statement.h>
#include <org/junit/runners/model/TestClass.h>
#include <org/junit/runners/model/TestTimedOutException.h>
#include <org/junit/runners/parameterized/BlockJUnit4ClassRunnerWithParameters.h>
#include <org/junit/runners/parameterized/BlockJUnit4ClassRunnerWithParametersFactory.h>
#include <org/junit/runners/parameterized/ParametersRunnerFactory.h>
#include <org/junit/runners/parameterized/TestWithParameters.h>
#include <org/junit/validator/AnnotationValidator.h>
#include <org/junit/validator/AnnotationValidatorFactory.h>
#include <org/junit/validator/AnnotationsValidator.h>
#include <org/junit/validator/PublicClassValidator.h>
#include <org/junit/validator/TestClassValidator.h>
#include <org/junit/validator/ValidateWith.h>
#include <com/tngtech/java/junit/dataprovider/DataProvider.h>
#include <com/tngtech/java/junit/dataprovider/DataProviderFilter.h>
#include <com/tngtech/java/junit/dataprovider/DataProviderFrameworkMethod.h>
#include <com/tngtech/java/junit/dataprovider/DataProviderRunner.h>
#include <com/tngtech/java/junit/dataprovider/DataProviders.h>
#include <com/tngtech/java/junit/dataprovider/Placeholders.h>
#include <com/tngtech/java/junit/dataprovider/UseDataProvider.h>
#include <com/tngtech/java/junit/dataprovider/internal/DataConverter.h>
#include <com/tngtech/java/junit/dataprovider/internal/TestGenerator.h>
#include <com/tngtech/java/junit/dataprovider/internal/TestValidator.h>
#include <com/tngtech/java/junit/dataprovider/internal/convert/AbstractObjectConverter.h>
#include <com/tngtech/java/junit/dataprovider/internal/convert/ObjectArrayConverter.h>
#include <com/tngtech/java/junit/dataprovider/internal/convert/SingleArgConverter.h>
#include <com/tngtech/java/junit/dataprovider/internal/convert/StringConverter.h>
#include <com/tngtech/java/junit/dataprovider/internal/placeholder/BasePlaceholder.h>
#include <com/tngtech/java/junit/dataprovider/internal/placeholder/CanonicalClassNamePlaceholder.h>
#include <com/tngtech/java/junit/dataprovider/internal/placeholder/CompleteMethodSignaturePlaceholder.h>
#include <com/tngtech/java/junit/dataprovider/internal/placeholder/IndexPlaceholder.h>
#include <com/tngtech/java/junit/dataprovider/internal/placeholder/ParameterPlaceholder.h>
#include <com/tngtech/java/junit/dataprovider/internal/placeholder/SimpleClassNamePlaceholder.h>
#include <com/tngtech/java/junit/dataprovider/internal/placeholder/SimpleMethodNamePlaceholder.h>
#include <org/hamcrest/BaseDescription.h>
#include <org/hamcrest/BaseMatcher.h>
#include <org/hamcrest/Condition.h>
#include <org/hamcrest/CoreMatchers.h>
#include <org/hamcrest/CustomMatcher.h>
#include <org/hamcrest/CustomTypeSafeMatcher.h>
#include <org/hamcrest/Description.h>
#include <org/hamcrest/DiagnosingMatcher.h>
#include <org/hamcrest/Factory.h>
#include <org/hamcrest/FeatureMatcher.h>
#include <org/hamcrest/Matcher.h>
#include <org/hamcrest/MatcherAssert.h>
#include <org/hamcrest/SelfDescribing.h>
#include <org/hamcrest/StringDescription.h>
#include <org/hamcrest/TypeSafeDiagnosingMatcher.h>
#include <org/hamcrest/TypeSafeMatcher.h>
#include <org/hamcrest/core/AllOf.h>
#include <org/hamcrest/core/AnyOf.h>
#include <org/hamcrest/core/CombinableMatcher.h>
#include <org/hamcrest/core/DescribedAs.h>
#include <org/hamcrest/core/Every.h>
#include <org/hamcrest/core/Is.h>
#include <org/hamcrest/core/IsAnything.h>
#include <org/hamcrest/core/IsCollectionContaining.h>
#include <org/hamcrest/core/IsEqual.h>
#include <org/hamcrest/core/IsInstanceOf.h>
#include <org/hamcrest/core/IsNot.h>
#include <org/hamcrest/core/IsNull.h>
#include <org/hamcrest/core/IsSame.h>
#include <org/hamcrest/core/ShortcutCombination.h>
#include <org/hamcrest/core/StringContains.h>
#include <org/hamcrest/core/StringEndsWith.h>
#include <org/hamcrest/core/StringStartsWith.h>
#include <org/hamcrest/core/SubstringMatcher.h>
#include <org/hamcrest/internal/ArrayIterator.h>
#include <org/hamcrest/internal/ReflectiveTypeFinder.h>
#include <org/hamcrest/internal/SelfDescribingValue.h>
#include <org/hamcrest/internal/SelfDescribingValueIterator.h>
