//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/testing/mockito/build_result/java/org/mockito/internal/exceptions/stacktrace/StackTraceFilter.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalExceptionsStacktraceStackTraceFilter")
#ifdef RESTRICT_OrgMockitoInternalExceptionsStacktraceStackTraceFilter
#define INCLUDE_ALL_OrgMockitoInternalExceptionsStacktraceStackTraceFilter 0
#else
#define INCLUDE_ALL_OrgMockitoInternalExceptionsStacktraceStackTraceFilter 1
#endif
#undef RESTRICT_OrgMockitoInternalExceptionsStacktraceStackTraceFilter

#if !defined (OrgMockitoInternalExceptionsStacktraceStackTraceFilter_) && (INCLUDE_ALL_OrgMockitoInternalExceptionsStacktraceStackTraceFilter || defined(INCLUDE_OrgMockitoInternalExceptionsStacktraceStackTraceFilter))
#define OrgMockitoInternalExceptionsStacktraceStackTraceFilter_

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class IOSObjectArray;
@class JavaLangBoolean;
@class JavaLangLong;

@interface OrgMockitoInternalExceptionsStacktraceStackTraceFilter : NSObject < JavaIoSerializable >

#pragma mark Public

- (instancetype)init;

- (IOSObjectArray *)filterWithJavaLangStackTraceElementArray:(IOSObjectArray *)target
                                                 withBoolean:(jboolean)keepTop;

@end

J2OBJC_STATIC_INIT(OrgMockitoInternalExceptionsStacktraceStackTraceFilter)

inline jlong OrgMockitoInternalExceptionsStacktraceStackTraceFilter_get_serialVersionUID(void);
#define OrgMockitoInternalExceptionsStacktraceStackTraceFilter_serialVersionUID -5499819791513105700LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgMockitoInternalExceptionsStacktraceStackTraceFilter, serialVersionUID, jlong)

FOUNDATION_EXPORT void OrgMockitoInternalExceptionsStacktraceStackTraceFilter_init(OrgMockitoInternalExceptionsStacktraceStackTraceFilter *self);

FOUNDATION_EXPORT OrgMockitoInternalExceptionsStacktraceStackTraceFilter *new_OrgMockitoInternalExceptionsStacktraceStackTraceFilter_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalExceptionsStacktraceStackTraceFilter *create_OrgMockitoInternalExceptionsStacktraceStackTraceFilter_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalExceptionsStacktraceStackTraceFilter)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalExceptionsStacktraceStackTraceFilter")
