//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/testing/mockito/build_result/java/org/mockito/internal/verification/VerificationModeFactory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalVerificationVerificationModeFactory")
#ifdef RESTRICT_OrgMockitoInternalVerificationVerificationModeFactory
#define INCLUDE_ALL_OrgMockitoInternalVerificationVerificationModeFactory 0
#else
#define INCLUDE_ALL_OrgMockitoInternalVerificationVerificationModeFactory 1
#endif
#undef RESTRICT_OrgMockitoInternalVerificationVerificationModeFactory

#if !defined (OrgMockitoInternalVerificationVerificationModeFactory_) && (INCLUDE_ALL_OrgMockitoInternalVerificationVerificationModeFactory || defined(INCLUDE_OrgMockitoInternalVerificationVerificationModeFactory))
#define OrgMockitoInternalVerificationVerificationModeFactory_

@class JavaLangInteger;
@class OrgMockitoInternalVerificationCalls;
@class OrgMockitoInternalVerificationNoMoreInteractions;
@class OrgMockitoInternalVerificationTimes;
@protocol OrgMockitoVerificationVerificationMode;

@interface OrgMockitoInternalVerificationVerificationModeFactory : NSObject

#pragma mark Public

- (instancetype)init;

+ (id<OrgMockitoVerificationVerificationMode>)atLeastWithInt:(jint)minNumberOfInvocations;

+ (id<OrgMockitoVerificationVerificationMode>)atLeastOnce;

+ (id<OrgMockitoVerificationVerificationMode>)atMostWithInt:(jint)maxNumberOfInvocations;

+ (OrgMockitoInternalVerificationCalls *)callsWithInt:(jint)wantedNumberOfInvocations;

+ (id<OrgMockitoVerificationVerificationMode>)description__WithOrgMockitoVerificationVerificationMode:(id<OrgMockitoVerificationVerificationMode>)mode
                                                                                         withNSString:(NSString *)description_;

+ (OrgMockitoInternalVerificationNoMoreInteractions *)noMoreInteractions;

+ (id<OrgMockitoVerificationVerificationMode>)only;

+ (OrgMockitoInternalVerificationTimes *)timesWithInt:(jint)wantedNumberOfInvocations;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalVerificationVerificationModeFactory)

FOUNDATION_EXPORT void OrgMockitoInternalVerificationVerificationModeFactory_init(OrgMockitoInternalVerificationVerificationModeFactory *self);

FOUNDATION_EXPORT OrgMockitoInternalVerificationVerificationModeFactory *new_OrgMockitoInternalVerificationVerificationModeFactory_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalVerificationVerificationModeFactory *create_OrgMockitoInternalVerificationVerificationModeFactory_init(void);

FOUNDATION_EXPORT id<OrgMockitoVerificationVerificationMode> OrgMockitoInternalVerificationVerificationModeFactory_atLeastOnce(void);

FOUNDATION_EXPORT id<OrgMockitoVerificationVerificationMode> OrgMockitoInternalVerificationVerificationModeFactory_atLeastWithInt_(jint minNumberOfInvocations);

FOUNDATION_EXPORT id<OrgMockitoVerificationVerificationMode> OrgMockitoInternalVerificationVerificationModeFactory_only(void);

FOUNDATION_EXPORT OrgMockitoInternalVerificationTimes *OrgMockitoInternalVerificationVerificationModeFactory_timesWithInt_(jint wantedNumberOfInvocations);

FOUNDATION_EXPORT OrgMockitoInternalVerificationCalls *OrgMockitoInternalVerificationVerificationModeFactory_callsWithInt_(jint wantedNumberOfInvocations);

FOUNDATION_EXPORT OrgMockitoInternalVerificationNoMoreInteractions *OrgMockitoInternalVerificationVerificationModeFactory_noMoreInteractions(void);

FOUNDATION_EXPORT id<OrgMockitoVerificationVerificationMode> OrgMockitoInternalVerificationVerificationModeFactory_atMostWithInt_(jint maxNumberOfInvocations);

FOUNDATION_EXPORT id<OrgMockitoVerificationVerificationMode> OrgMockitoInternalVerificationVerificationModeFactory_description__WithOrgMockitoVerificationVerificationMode_withNSString_(id<OrgMockitoVerificationVerificationMode> mode, NSString *description_);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalVerificationVerificationModeFactory)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalVerificationVerificationModeFactory")
