//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/guava/android/build_result/java/com/google/errorprone/annotations/concurrent/GuardedBy.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_ComGoogleErrorproneAnnotationsConcurrentGuardedBy")
#ifdef RESTRICT_ComGoogleErrorproneAnnotationsConcurrentGuardedBy
#define INCLUDE_ALL_ComGoogleErrorproneAnnotationsConcurrentGuardedBy 0
#else
#define INCLUDE_ALL_ComGoogleErrorproneAnnotationsConcurrentGuardedBy 1
#endif
#undef RESTRICT_ComGoogleErrorproneAnnotationsConcurrentGuardedBy

#if !defined (ComGoogleErrorproneAnnotationsConcurrentGuardedBy_) && (INCLUDE_ALL_ComGoogleErrorproneAnnotationsConcurrentGuardedBy || defined(INCLUDE_ComGoogleErrorproneAnnotationsConcurrentGuardedBy))
#define ComGoogleErrorproneAnnotationsConcurrentGuardedBy_

#define RESTRICT_JavaLangAnnotationAnnotation 1
#define INCLUDE_JavaLangAnnotationAnnotation 1
#include "java/lang/annotation/Annotation.h"

@class IOSClass;
@class JavaLangBoolean;
@class JavaLangInteger;

@protocol ComGoogleErrorproneAnnotationsConcurrentGuardedBy < JavaLangAnnotationAnnotation >

@property (readonly) NSString *value;

- (jboolean)isEqual:(id)obj;

- (NSUInteger)hash;

@end

@interface ComGoogleErrorproneAnnotationsConcurrentGuardedBy : NSObject < ComGoogleErrorproneAnnotationsConcurrentGuardedBy > {
 @public
  NSString *value_;
}

@end

J2OBJC_EMPTY_STATIC_INIT(ComGoogleErrorproneAnnotationsConcurrentGuardedBy)

FOUNDATION_EXPORT id<ComGoogleErrorproneAnnotationsConcurrentGuardedBy> create_ComGoogleErrorproneAnnotationsConcurrentGuardedBy(NSString *value);

J2OBJC_TYPE_LITERAL_HEADER(ComGoogleErrorproneAnnotationsConcurrentGuardedBy)

#endif

#pragma pop_macro("INCLUDE_ALL_ComGoogleErrorproneAnnotationsConcurrentGuardedBy")
