//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xml/dtm/Axis.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXmlDtmAxis")
#ifdef RESTRICT_OrgApacheXmlDtmAxis
#define INCLUDE_ALL_OrgApacheXmlDtmAxis 0
#else
#define INCLUDE_ALL_OrgApacheXmlDtmAxis 1
#endif
#undef RESTRICT_OrgApacheXmlDtmAxis

#if !defined (OrgApacheXmlDtmAxis_) && (INCLUDE_ALL_OrgApacheXmlDtmAxis || defined(INCLUDE_OrgApacheXmlDtmAxis))
#define OrgApacheXmlDtmAxis_

@class JavaLangBoolean;
@class JavaLangInteger;

@interface OrgApacheXmlDtmAxis : NSObject

#pragma mark Public

- (instancetype)init;

+ (NSString *)getNamesWithInt:(jint)index;

+ (jint)getNamesLength;

+ (jboolean)isReverseWithInt:(jint)axis;

@end

J2OBJC_STATIC_INIT(OrgApacheXmlDtmAxis)

inline jint OrgApacheXmlDtmAxis_get_ANCESTOR(void);
#define OrgApacheXmlDtmAxis_ANCESTOR 0
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, ANCESTOR, jint)

inline jint OrgApacheXmlDtmAxis_get_ANCESTORORSELF(void);
#define OrgApacheXmlDtmAxis_ANCESTORORSELF 1
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, ANCESTORORSELF, jint)

inline jint OrgApacheXmlDtmAxis_get_ATTRIBUTE(void);
#define OrgApacheXmlDtmAxis_ATTRIBUTE 2
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, ATTRIBUTE, jint)

inline jint OrgApacheXmlDtmAxis_get_CHILD(void);
#define OrgApacheXmlDtmAxis_CHILD 3
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, CHILD, jint)

inline jint OrgApacheXmlDtmAxis_get_DESCENDANT(void);
#define OrgApacheXmlDtmAxis_DESCENDANT 4
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, DESCENDANT, jint)

inline jint OrgApacheXmlDtmAxis_get_DESCENDANTORSELF(void);
#define OrgApacheXmlDtmAxis_DESCENDANTORSELF 5
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, DESCENDANTORSELF, jint)

inline jint OrgApacheXmlDtmAxis_get_FOLLOWING(void);
#define OrgApacheXmlDtmAxis_FOLLOWING 6
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, FOLLOWING, jint)

inline jint OrgApacheXmlDtmAxis_get_FOLLOWINGSIBLING(void);
#define OrgApacheXmlDtmAxis_FOLLOWINGSIBLING 7
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, FOLLOWINGSIBLING, jint)

inline jint OrgApacheXmlDtmAxis_get_NAMESPACEDECLS(void);
#define OrgApacheXmlDtmAxis_NAMESPACEDECLS 8
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, NAMESPACEDECLS, jint)

inline jint OrgApacheXmlDtmAxis_get_NAMESPACE(void);
#define OrgApacheXmlDtmAxis_NAMESPACE 9
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, NAMESPACE, jint)

inline jint OrgApacheXmlDtmAxis_get_PARENT(void);
#define OrgApacheXmlDtmAxis_PARENT 10
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, PARENT, jint)

inline jint OrgApacheXmlDtmAxis_get_PRECEDING(void);
#define OrgApacheXmlDtmAxis_PRECEDING 11
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, PRECEDING, jint)

inline jint OrgApacheXmlDtmAxis_get_PRECEDINGSIBLING(void);
#define OrgApacheXmlDtmAxis_PRECEDINGSIBLING 12
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, PRECEDINGSIBLING, jint)

inline jint OrgApacheXmlDtmAxis_get_SELF(void);
#define OrgApacheXmlDtmAxis_SELF 13
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, SELF, jint)

inline jint OrgApacheXmlDtmAxis_get_ALLFROMNODE(void);
#define OrgApacheXmlDtmAxis_ALLFROMNODE 14
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, ALLFROMNODE, jint)

inline jint OrgApacheXmlDtmAxis_get_PRECEDINGANDANCESTOR(void);
#define OrgApacheXmlDtmAxis_PRECEDINGANDANCESTOR 15
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, PRECEDINGANDANCESTOR, jint)

inline jint OrgApacheXmlDtmAxis_get_ALL(void);
#define OrgApacheXmlDtmAxis_ALL 16
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, ALL, jint)

inline jint OrgApacheXmlDtmAxis_get_DESCENDANTSFROMROOT(void);
#define OrgApacheXmlDtmAxis_DESCENDANTSFROMROOT 17
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, DESCENDANTSFROMROOT, jint)

inline jint OrgApacheXmlDtmAxis_get_DESCENDANTSORSELFFROMROOT(void);
#define OrgApacheXmlDtmAxis_DESCENDANTSORSELFFROMROOT 18
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, DESCENDANTSORSELFFROMROOT, jint)

inline jint OrgApacheXmlDtmAxis_get_ROOT(void);
#define OrgApacheXmlDtmAxis_ROOT 19
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, ROOT, jint)

inline jint OrgApacheXmlDtmAxis_get_FILTEREDLIST(void);
#define OrgApacheXmlDtmAxis_FILTEREDLIST 20
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmAxis, FILTEREDLIST, jint)

FOUNDATION_EXPORT void OrgApacheXmlDtmAxis_init(OrgApacheXmlDtmAxis *self);

FOUNDATION_EXPORT OrgApacheXmlDtmAxis *new_OrgApacheXmlDtmAxis_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXmlDtmAxis *create_OrgApacheXmlDtmAxis_init(void);

FOUNDATION_EXPORT jboolean OrgApacheXmlDtmAxis_isReverseWithInt_(jint axis);

FOUNDATION_EXPORT NSString *OrgApacheXmlDtmAxis_getNamesWithInt_(jint index);

FOUNDATION_EXPORT jint OrgApacheXmlDtmAxis_getNamesLength(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXmlDtmAxis)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXmlDtmAxis")
