//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xml/dtm/ObjectFactory.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXmlDtmObjectFactory")
#ifdef RESTRICT_OrgApacheXmlDtmObjectFactory
#define INCLUDE_ALL_OrgApacheXmlDtmObjectFactory 0
#else
#define INCLUDE_ALL_OrgApacheXmlDtmObjectFactory 1
#endif
#undef RESTRICT_OrgApacheXmlDtmObjectFactory

#if !defined (OrgApacheXmlDtmObjectFactory_) && (INCLUDE_ALL_OrgApacheXmlDtmObjectFactory || defined(INCLUDE_OrgApacheXmlDtmObjectFactory))
#define OrgApacheXmlDtmObjectFactory_

@class IOSClass;
@class JavaLangBoolean;
@class JavaLangClassLoader;

@interface OrgApacheXmlDtmObjectFactory : NSObject

#pragma mark Package-Private

- (instancetype)initPackagePrivate;

+ (id)createObjectWithNSString:(NSString *)factoryId
                  withNSString:(NSString *)fallbackClassName;

+ (id)createObjectWithNSString:(NSString *)factoryId
                  withNSString:(NSString *)propertiesFilename
                  withNSString:(NSString *)fallbackClassName;

+ (JavaLangClassLoader *)findClassLoader;

+ (IOSClass *)findProviderClassWithNSString:(NSString *)className_
                    withJavaLangClassLoader:(JavaLangClassLoader *)cl
                                withBoolean:(jboolean)doFallback;

+ (IOSClass *)lookUpFactoryClassWithNSString:(NSString *)factoryId;

+ (IOSClass *)lookUpFactoryClassWithNSString:(NSString *)factoryId
                                withNSString:(NSString *)propertiesFilename
                                withNSString:(NSString *)fallbackClassName;

+ (NSString *)lookUpFactoryClassNameWithNSString:(NSString *)factoryId
                                    withNSString:(NSString *)propertiesFilename
                                    withNSString:(NSString *)fallbackClassName;

+ (id)newInstanceWithNSString:(NSString *)className_
      withJavaLangClassLoader:(JavaLangClassLoader *)cl
                  withBoolean:(jboolean)doFallback OBJC_METHOD_FAMILY_NONE;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXmlDtmObjectFactory)

FOUNDATION_EXPORT void OrgApacheXmlDtmObjectFactory_initPackagePrivate(OrgApacheXmlDtmObjectFactory *self);

FOUNDATION_EXPORT OrgApacheXmlDtmObjectFactory *new_OrgApacheXmlDtmObjectFactory_initPackagePrivate(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXmlDtmObjectFactory *create_OrgApacheXmlDtmObjectFactory_initPackagePrivate(void);

FOUNDATION_EXPORT id OrgApacheXmlDtmObjectFactory_createObjectWithNSString_withNSString_(NSString *factoryId, NSString *fallbackClassName);

FOUNDATION_EXPORT id OrgApacheXmlDtmObjectFactory_createObjectWithNSString_withNSString_withNSString_(NSString *factoryId, NSString *propertiesFilename, NSString *fallbackClassName);

FOUNDATION_EXPORT IOSClass *OrgApacheXmlDtmObjectFactory_lookUpFactoryClassWithNSString_(NSString *factoryId);

FOUNDATION_EXPORT IOSClass *OrgApacheXmlDtmObjectFactory_lookUpFactoryClassWithNSString_withNSString_withNSString_(NSString *factoryId, NSString *propertiesFilename, NSString *fallbackClassName);

FOUNDATION_EXPORT NSString *OrgApacheXmlDtmObjectFactory_lookUpFactoryClassNameWithNSString_withNSString_withNSString_(NSString *factoryId, NSString *propertiesFilename, NSString *fallbackClassName);

FOUNDATION_EXPORT JavaLangClassLoader *OrgApacheXmlDtmObjectFactory_findClassLoader(void);

FOUNDATION_EXPORT id OrgApacheXmlDtmObjectFactory_newInstanceWithNSString_withJavaLangClassLoader_withBoolean_(NSString *className_, JavaLangClassLoader *cl, jboolean doFallback);

FOUNDATION_EXPORT IOSClass *OrgApacheXmlDtmObjectFactory_findProviderClassWithNSString_withJavaLangClassLoader_withBoolean_(NSString *className_, JavaLangClassLoader *cl, jboolean doFallback);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXmlDtmObjectFactory)

#endif

#if !defined (OrgApacheXmlDtmObjectFactory_ConfigurationError_) && (INCLUDE_ALL_OrgApacheXmlDtmObjectFactory || defined(INCLUDE_OrgApacheXmlDtmObjectFactory_ConfigurationError))
#define OrgApacheXmlDtmObjectFactory_ConfigurationError_

#define RESTRICT_JavaLangError 1
#define INCLUDE_JavaLangError 1
#include "java/lang/Error.h"

@class JavaLangBoolean;
@class JavaLangException;
@class JavaLangLong;
@class JavaLangThrowable;

@interface OrgApacheXmlDtmObjectFactory_ConfigurationError : JavaLangError

#pragma mark Package-Private

- (instancetype)initWithNSString:(NSString *)msg
           withJavaLangException:(JavaLangException *)x;

- (JavaLangException *)getException;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

- (instancetype)initWithJavaLangThrowable:(JavaLangThrowable *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1 NS_UNAVAILABLE;

- (instancetype)initWithNSString:(NSString *)arg0
           withJavaLangThrowable:(JavaLangThrowable *)arg1
                     withBoolean:(jboolean)arg2
                     withBoolean:(jboolean)arg3 NS_UNAVAILABLE;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXmlDtmObjectFactory_ConfigurationError)

inline jlong OrgApacheXmlDtmObjectFactory_ConfigurationError_get_serialVersionUID(void);
#define OrgApacheXmlDtmObjectFactory_ConfigurationError_serialVersionUID 5122054096615067992LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXmlDtmObjectFactory_ConfigurationError, serialVersionUID, jlong)

FOUNDATION_EXPORT void OrgApacheXmlDtmObjectFactory_ConfigurationError_initWithNSString_withJavaLangException_(OrgApacheXmlDtmObjectFactory_ConfigurationError *self, NSString *msg, JavaLangException *x);

FOUNDATION_EXPORT OrgApacheXmlDtmObjectFactory_ConfigurationError *new_OrgApacheXmlDtmObjectFactory_ConfigurationError_initWithNSString_withJavaLangException_(NSString *msg, JavaLangException *x) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXmlDtmObjectFactory_ConfigurationError *create_OrgApacheXmlDtmObjectFactory_ConfigurationError_initWithNSString_withJavaLangException_(NSString *msg, JavaLangException *x);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXmlDtmObjectFactory_ConfigurationError)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXmlDtmObjectFactory")
