//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xml/dtm/SecuritySupport.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXmlDtmSecuritySupport")
#ifdef RESTRICT_OrgApacheXmlDtmSecuritySupport
#define INCLUDE_ALL_OrgApacheXmlDtmSecuritySupport 0
#else
#define INCLUDE_ALL_OrgApacheXmlDtmSecuritySupport 1
#endif
#undef RESTRICT_OrgApacheXmlDtmSecuritySupport

#if !defined (OrgApacheXmlDtmSecuritySupport_) && (INCLUDE_ALL_OrgApacheXmlDtmSecuritySupport || defined(INCLUDE_OrgApacheXmlDtmSecuritySupport))
#define OrgApacheXmlDtmSecuritySupport_

@class JavaIoFile;
@class JavaIoFileInputStream;
@class JavaIoInputStream;
@class JavaLangBoolean;
@class JavaLangClassLoader;
@class JavaLangLong;

@interface OrgApacheXmlDtmSecuritySupport : NSObject

#pragma mark Package-Private

- (instancetype)initPackagePrivate;

- (JavaLangClassLoader *)getContextClassLoader;

- (jboolean)getFileExistsWithJavaIoFile:(JavaIoFile *)f;

- (JavaIoFileInputStream *)getFileInputStreamWithJavaIoFile:(JavaIoFile *)file;

+ (OrgApacheXmlDtmSecuritySupport *)getInstance;

- (jlong)getLastModifiedWithJavaIoFile:(JavaIoFile *)f;

- (JavaLangClassLoader *)getParentClassLoaderWithJavaLangClassLoader:(JavaLangClassLoader *)cl;

- (JavaIoInputStream *)getResourceAsStreamWithJavaLangClassLoader:(JavaLangClassLoader *)cl
                                                     withNSString:(NSString *)name;

- (JavaLangClassLoader *)getSystemClassLoader;

- (NSString *)getSystemPropertyWithNSString:(NSString *)propName;

// Disallowed inherited constructors, do not use.

- (instancetype)init NS_UNAVAILABLE;

@end

J2OBJC_STATIC_INIT(OrgApacheXmlDtmSecuritySupport)

FOUNDATION_EXPORT void OrgApacheXmlDtmSecuritySupport_initPackagePrivate(OrgApacheXmlDtmSecuritySupport *self);

FOUNDATION_EXPORT OrgApacheXmlDtmSecuritySupport *new_OrgApacheXmlDtmSecuritySupport_initPackagePrivate(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXmlDtmSecuritySupport *create_OrgApacheXmlDtmSecuritySupport_initPackagePrivate(void);

FOUNDATION_EXPORT OrgApacheXmlDtmSecuritySupport *OrgApacheXmlDtmSecuritySupport_getInstance(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXmlDtmSecuritySupport)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXmlDtmSecuritySupport")
