//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xalan/templates/ElemWhen.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXalanTemplatesElemWhen")
#ifdef RESTRICT_OrgApacheXalanTemplatesElemWhen
#define INCLUDE_ALL_OrgApacheXalanTemplatesElemWhen 0
#else
#define INCLUDE_ALL_OrgApacheXalanTemplatesElemWhen 1
#endif
#undef RESTRICT_OrgApacheXalanTemplatesElemWhen

#if !defined (OrgApacheXalanTemplatesElemWhen_) && (INCLUDE_ALL_OrgApacheXalanTemplatesElemWhen || defined(INCLUDE_OrgApacheXalanTemplatesElemWhen))
#define OrgApacheXalanTemplatesElemWhen_

#define RESTRICT_OrgApacheXalanTemplatesElemTemplateElement 1
#define INCLUDE_OrgApacheXalanTemplatesElemTemplateElement 1
#include "org/apache/xalan/templates/ElemTemplateElement.h"

@class JavaLangBoolean;
@class JavaLangInteger;
@class JavaLangLong;
@class OrgApacheXalanTemplatesStylesheetRoot;
@class OrgApacheXalanTemplatesXSLTVisitor;
@class OrgApacheXpathXPath;

@interface OrgApacheXalanTemplatesElemWhen : OrgApacheXalanTemplatesElemTemplateElement

#pragma mark Public

- (instancetype)init;

- (void)composeWithOrgApacheXalanTemplatesStylesheetRoot:(OrgApacheXalanTemplatesStylesheetRoot *)sroot;

- (NSString *)getNodeName;

- (OrgApacheXpathXPath *)getTest;

- (jint)getXSLToken;

- (void)setTestWithOrgApacheXpathXPath:(OrgApacheXpathXPath *)v;

#pragma mark Protected

- (void)callChildVisitorsWithOrgApacheXalanTemplatesXSLTVisitor:(OrgApacheXalanTemplatesXSLTVisitor *)visitor
                                                    withBoolean:(jboolean)callAttrs;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXalanTemplatesElemWhen)

inline jlong OrgApacheXalanTemplatesElemWhen_get_serialVersionUID(void);
#define OrgApacheXalanTemplatesElemWhen_serialVersionUID 5984065730262071360LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXalanTemplatesElemWhen, serialVersionUID, jlong)

FOUNDATION_EXPORT void OrgApacheXalanTemplatesElemWhen_init(OrgApacheXalanTemplatesElemWhen *self);

FOUNDATION_EXPORT OrgApacheXalanTemplatesElemWhen *new_OrgApacheXalanTemplatesElemWhen_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXalanTemplatesElemWhen *create_OrgApacheXalanTemplatesElemWhen_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXalanTemplatesElemWhen)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXalanTemplatesElemWhen")
