//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/xalan/third_party/android/platform/external/apache-xml/src/main/java/org/apache/xalan/templates/ElemSort.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgApacheXalanTemplatesElemSort")
#ifdef RESTRICT_OrgApacheXalanTemplatesElemSort
#define INCLUDE_ALL_OrgApacheXalanTemplatesElemSort 0
#else
#define INCLUDE_ALL_OrgApacheXalanTemplatesElemSort 1
#endif
#undef RESTRICT_OrgApacheXalanTemplatesElemSort

#if !defined (OrgApacheXalanTemplatesElemSort_) && (INCLUDE_ALL_OrgApacheXalanTemplatesElemSort || defined(INCLUDE_OrgApacheXalanTemplatesElemSort))
#define OrgApacheXalanTemplatesElemSort_

#define RESTRICT_OrgApacheXalanTemplatesElemTemplateElement 1
#define INCLUDE_OrgApacheXalanTemplatesElemTemplateElement 1
#include "org/apache/xalan/templates/ElemTemplateElement.h"

@class JavaLangInteger;
@class JavaLangLong;
@class OrgApacheXalanTemplatesAVT;
@class OrgApacheXalanTemplatesStylesheetRoot;
@class OrgApacheXpathXPath;
@protocol OrgW3cDomNode;

@interface OrgApacheXalanTemplatesElemSort : OrgApacheXalanTemplatesElemTemplateElement

#pragma mark Public

- (instancetype)init;

- (id<OrgW3cDomNode>)appendChildWithOrgW3cDomNode:(id<OrgW3cDomNode>)newChild;

- (void)composeWithOrgApacheXalanTemplatesStylesheetRoot:(OrgApacheXalanTemplatesStylesheetRoot *)sroot;

- (OrgApacheXalanTemplatesAVT *)getCaseOrder;

- (OrgApacheXalanTemplatesAVT *)getDataType;

- (OrgApacheXalanTemplatesAVT *)getLang;

- (NSString *)getNodeName;

- (OrgApacheXalanTemplatesAVT *)getOrder;

- (OrgApacheXpathXPath *)getSelect;

- (jint)getXSLToken;

- (void)setCaseOrderWithOrgApacheXalanTemplatesAVT:(OrgApacheXalanTemplatesAVT *)v;

- (void)setDataTypeWithOrgApacheXalanTemplatesAVT:(OrgApacheXalanTemplatesAVT *)v;

- (void)setLangWithOrgApacheXalanTemplatesAVT:(OrgApacheXalanTemplatesAVT *)v;

- (void)setOrderWithOrgApacheXalanTemplatesAVT:(OrgApacheXalanTemplatesAVT *)v;

- (void)setSelectWithOrgApacheXpathXPath:(OrgApacheXpathXPath *)v;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgApacheXalanTemplatesElemSort)

inline jlong OrgApacheXalanTemplatesElemSort_get_serialVersionUID(void);
#define OrgApacheXalanTemplatesElemSort_serialVersionUID -4991510257335851938LL
J2OBJC_STATIC_FIELD_CONSTANT(OrgApacheXalanTemplatesElemSort, serialVersionUID, jlong)

FOUNDATION_EXPORT void OrgApacheXalanTemplatesElemSort_init(OrgApacheXalanTemplatesElemSort *self);

FOUNDATION_EXPORT OrgApacheXalanTemplatesElemSort *new_OrgApacheXalanTemplatesElemSort_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgApacheXalanTemplatesElemSort *create_OrgApacheXalanTemplatesElemSort_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgApacheXalanTemplatesElemSort)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgApacheXalanTemplatesElemSort")
