//
//  Generated by the J2ObjC translator.  DO NOT EDIT!
//  source: /Users/nestseraualia/devel/j2objc-aleks/testing/mockito/build_result/java/org/mockito/internal/stubbing/defaultanswers/ReturnsMoreEmptyValues.java
//

#include "J2ObjC_header.h"

#pragma push_macro("INCLUDE_ALL_OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues")
#ifdef RESTRICT_OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues
#define INCLUDE_ALL_OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues 0
#else
#define INCLUDE_ALL_OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues 1
#endif
#undef RESTRICT_OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues

#if !defined (OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues_) && (INCLUDE_ALL_OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues || defined(INCLUDE_OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues))
#define OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues_

#define RESTRICT_OrgMockitoStubbingAnswer 1
#define INCLUDE_OrgMockitoStubbingAnswer 1
#include "org/mockito/stubbing/Answer.h"

#define RESTRICT_JavaIoSerializable 1
#define INCLUDE_JavaIoSerializable 1
#include "java/io/Serializable.h"

@class IOSClass;
@protocol OrgMockitoInvocationInvocationOnMock;

@interface OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues : NSObject < OrgMockitoStubbingAnswer, JavaIoSerializable >

#pragma mark Public

- (instancetype)init;

- (id)answerWithOrgMockitoInvocationInvocationOnMock:(id<OrgMockitoInvocationInvocationOnMock>)invocation;

#pragma mark Package-Private

- (id)returnValueForWithIOSClass:(IOSClass *)type;

@end

J2OBJC_EMPTY_STATIC_INIT(OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues)

FOUNDATION_EXPORT void OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues_init(OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues *self);

FOUNDATION_EXPORT OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues *new_OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues_init(void) NS_RETURNS_RETAINED;

FOUNDATION_EXPORT OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues *create_OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues_init(void);

J2OBJC_TYPE_LITERAL_HEADER(OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues)

#endif

#pragma pop_macro("INCLUDE_ALL_OrgMockitoInternalStubbingDefaultanswersReturnsMoreEmptyValues")
